### ISSUE TITLE
Error Invariant Violation

### ISSUE THREAD

**Issue by Victorcassiano** [nandorojo/moti#101]
I did the step by step to install Moti, using only React Native, without Expo.
returned these errors to me:

<img src="https://i.imgur.com/a551x0W.png" alt="Minha Figura" width="400px">

<img src="https://i.imgur.com/TbOZ8yd.png" alt="Minha Figura" width="900px">

I've remade the step by step several times

**Comment by nandorojo** [comment]
This is an issue with reanimated setup, not Moti

**Comment by nandorojo** [comment]
If you’re installing reanimated, please follow their instructions, and make sure to rebuild afterwards. If you keep having problems, please open an issue on their repo. Thanks!
