### ISSUE TITLE
AnimatePresence and initial={false}

### ISSUE THREAD

**Issue by TommySorensen** [nandorojo/moti#109]
I have a issue with latest version `0.14.2` where initial now is supported https://github.com/nandorojo/moti/pull/102

If you are using [react native tab navigation](https://reactnavigation.org/docs/tab-based-navigation) and open a tab where the elements should be hidden on mount. What happens is that it will run the animation going from "opacity .75" to "opacity 0" while the screen is mounted. The specific screen is mounted when visited. Expected behaviour is that it should not run the animation because of `initial={false}`. I also tried addeding `animateInitialState={false}` to the Something element, but that did not change anything.

```js
const editMode = false;

<AnimatePresence initial={false}>
  {editMode && (
    <Something
      from={{ opacity: 0 }}
      animate={{ opacity: 0.75 }}
      exit={{ opacity: 0 }}
      transition={{
        type: 'timing',
        duration: 250,
      }}
    />
  )}
 </AnimatePresence>

```

Styles (style-components)
```js
import styled from 'styled-components/native';
  
const Something = styled(MotiView)`
  position: absolute;
  background-color: #000000;
  border-radius: 10px;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
`;
```
The styles has nothing to do with it, i just pasted it anyway

**Comment by TommySorensen** [comment]
Hi @nandorojo.
Do you have a idea if this is bug in Moti or somewhere else? I can try to see if i can reproduce this issue in expo.

**Comment by nandorojo** [comment]
Thanks for the issue. I’m having a little trouble following. Can you make a snack (on iOS) reproducing, and explain what should have happened? 

Can you also confirm the same happens with styled components?

**Comment by nandorojo** [comment]
As far as I know, the `initial={false}` is meant for items that exist on the **first render**. However, since edit mode is initially false, this won’t apply.

The purpose of this prop is to let you use a different `key` on the child of animate presence, and trigger an exit animation any time the `key` changes.

**Comment by TommySorensen** [comment]
I have used Framer Motion a lot and the as far as i know the `initial={false}` with `AnimatePresence` will always disable the animations on first render meaning that it go straight to the `initial={{ opacity: 0 }}` like this example. But with the above example Moti will on first render animate from animate to exit because the `editMode` is false. This is not the expected behaviour compared to Framer Motion. But maybe you went with a bit different API here? I will try to create a snack with this issue later today
```js
<AnimatePresence initial={false}>
  {isVisible && (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
    />
  )}
</AnimatePresence>
```

**Comment by nandorojo** [comment]
Interesting. But what would the `from` prop be there for then?

If you can repro it with both then I can investigate. But the purpose was to match their behavior.

**Comment by TommySorensen** [comment]
I see it as

**initial={false}:**
Elements visible should go straight to animate prop. 
Elements not visible should go straight to exit prop.

**initial={true}**
Elements visible should animate from `from` prop to `animate` prop. 
Elements not visible should animate from `animate` prop to `exit` prop.

**Comment by nandorojo** [comment]
So for case 1) why are you setting the `from` prop at all?

**Comment by nandorojo** [comment]
I also don’t think that’s exactly right re: the first one. 

I think if the child key changes, then it animates out and the next one animates in. But the first time, it doesn’t animate in.

**Comment by TommySorensen** [comment]
Found the issue 🙄, it was error 40 🤣. My initial state was true, meaning that it was in first render `true` and then false just after since i got a useEffect that turned it into false.
```js
const [editMode, setEditMode] = useState(true);
```

Thx for helping 👍
