### ISSUE TITLE
Skeleton backgroundSize prop does nothing

### ISSUE THREAD

**Issue by llaver** [nandorojo/moti#112]
Skeleton has a prop backgroundSize, unfortunately, it is then defined inside the component:
`const backgroundSize = 6`

Seems necessary otherwise the skeleton looks something like this:
![image](https://user-images.githubusercontent.com/787028/134579765-eb3f257b-2530-449d-b180-246f470e0d28.png)

**Comment by nandorojo** [comment]
Feel free to PR
