### ISSUE TITLE
 Cannot read property 'MotiView'

### ISSUE THREAD

**Issue by juandl** [nandorojo/moti#114]
Hi, I have this error "TypeError: Cannot read property 'MotiView' of undefined"

```
<MotiView
              from={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{
                type: 'timing',
                duration: 500
              }}
            >
              <View style={styles.loader_container}>
                <View style={styles.loader_backdrop}></View>
                <View
                  style={styles.loader_content}
                  needsOffscreenAlphaCompositing
                >
                  <View style={styles.loader_loading}>
                    <LottieView
                      source={Assets.Animation.loadingCity}
                      autoPlay
                      loop={true}
                      resizeMode="cover"
                      style={{ width: 150 }}
                    />
                    <Text style={styles.loader_text}>Loading...</Text>
                  </View>
                </View>
              </View>
            </MotiView>
```

React-Native: 0.65.1
Moti: 0.15.2
Reanimated: 2.2.2

**Comment by nandorojo** [comment]
Can you post a reproduction?

**Comment by nandorojo** [comment]
Will re-open if there's a reproduction.

**Comment by nextriot** [comment]
@nandorojo here's my repo with the same error: https://github.com/nextriot/huamor-rn

React-Native: 0.66.2
Moti: 0.16.1
Reanimated: 2.3.0-beta.2
Hermes-Engine: 0.9.0

**Comment by nextriot** [comment]
iOS & Android. Sentry reports that it's an issue in `use-map-animate-to-style`

**Comment by nandorojo** [comment]
You're using newer versions I haven't tried yet, so a bit hard to say why. Can you see if an expo init repro works?

**Comment by nextriot** [comment]
The latest version of expo includes version 0.64 of RN. 
It probably does work. I was using this lib with 0.64 a month back and it was fine.

Not applicable to the current issue though I'd imagine. Just tried with Reanimated 2.2.4 and it's also broken.

**Comment by nandorojo** [comment]
If you can make a clear reproduction of what exactly causes the issue (a certain RN version, a certain reanimated version, etc) I can take a look

**Comment by nextriot** [comment]
I linked to my repo which reproduces the error. How would you prefer it?

--
Best regards,
Kyle

**Comment by nandorojo** [comment]
Yeah the repro is good, but I don’t know which one of those issues is the cause (RN, Hermes, or Reanimated)

**Comment by fkazemi5236** [comment]
I have this problem too

"react": "17.0.2",
"react-native": "^0.66.3",
"moti": "^0.17.1"
"hermes-engine": "^0.11.0",
"react-native-reanimated": "^2.4.1",

and show mi this error:
Cannot read property 'MotiView' of undefined

![WhatsApp Image 2022-02-19 at 12 21 00 PM](https://user-images.githubusercontent.com/46262018/154794094-2b38cb18-c7fd-4989-8156-8c37904cb3c1.jpeg)

**Comment by tperich** [comment]
Same problem here. React Native v0.67.2, react-native-reanimated v2.4.1, moti v0.17.1.

**Comment by nandorojo** [comment]
> Adding import 'react-native-reanimated' in App.js (or .ts) resolves the issue. It might be smart to add this to the installation documentation.

This actually is on there: https://moti.fyi/installation#using-inline-requires

Maybe we should specify to do that for newer versions of RN. Or I just say to do it in general to get around it?

**Comment by tperich** [comment]
I think doing it in general would be a good approach if more people have this issue. I haven't written any inline requires in the app, it's a fresh slate.

**Comment by nandorojo** [comment]
I’d happily merge a PR!

**Comment by juandl** [comment]
> I’d happily merge a PR!

Please check mentioned or
