### ISSUE TITLE
Animation only happen until i keep pressed

### ISSUE THREAD

**Issue by siddharth-kt** [nandorojo/moti#115]
Great library,

I was trying/exploring this library but what I found that in <MotiPressable/> animate(animation) works only when I keep it pressed,
if I just press and move my finger away then animation stops in between and goes back (on Android).

Is there any way to complete the animation even if finger is removed ?

**Comment by nandorojo** [comment]
I'm not sure I get what you're saying. Is this about `MotiPressable`? Could you make a simple Expo snack demonstrating?

**Comment by siddharth-kt** [comment]
Yeah, i forgot to mention i was saying about MotiPressable.
Here is the snack for demonstration :
https://snack.expo.dev/@siddharth-tyagi/moti-pressable

**Comment by nandorojo** [comment]
I see, that’s interesting.

Looking at your code, the behavior is correct. It’s stateful.

You’re telling it to do one thing when it’s pressed, and that’s what it’s doing. When it’s no longer pressed, then it changes the style. I’m not sure what else could be expected. 

So what you’re looking for is essentially a way to time a given animation based on the press event: not style based on the current `pressed` state…

**Comment by siddharth-kt** [comment]
Yeah, i mean when i pressed(single click), then the animations should start and get completed till end.
Currently For animation to complete we need to keep the white box pressed.

**Comment by nandorojo** [comment]
Okay here's what I think you should do. There's a hook called `useMotiPressableTransition`, which lets you set the transition (and thus the delay) based on the interaction state.

Snack: https://snack.expo.dev/@beatgig/moti-pressable

```tsx
import React, { useReducer, useCallback } from 'react';
import { StyleSheet } from 'react-native';
import { View } from 'moti';
import {
  MotiPressable,
  useMotiPressableTransition,
  useMotiPressable,
} from '@motify/interactions';
import { useSharedValue } from 'react-native-reanimated';

const Box = () => {
  const state = useMotiPressable(({ pressed }) => {
    'worklet';

    return {
      scale: pressed ? [0, 1.5, { value: 1, delay: 200 }] : 1,
    };
  }, []);
  const transition = useMotiPressableTransition(({ pressed }) => {
    'worklet';

    return {
      delay: pressed ? 100 : 1500, // play with this delay here
    };
  }, []);
  return <View style={styles.shape} state={state} transition={transition} />;
};

export default function HelloWorld() {
  return (
    <View style={styles.container}>
      <MotiPressable>
        <Box />
      </MotiPressable>
    </View>
  );
}

const styles = StyleSheet.create({
  shape: {
    justifyContent: 'center',
    height: 250,
    width: 250,
    // borderRadius: 25,
    marginRight: 10,
    backgroundColor: 'white',
  },
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    backgroundColor: '#9c1aff',
  },
});
```

In this video, I'm just tapping:

https://user-images.githubusercontent.com/13172299/135329254-ebb3c811-052e-40dd-ace9-f74403f40543.MP4

**Comment by siddharth-kt** [comment]
Its working like a charm thankyou very much. 👍

**Comment by siddharth-kt** [comment]
I suggest you to also make it more simpler like by adding a onSinglePress prop on MotiPressable. to do complete animation on single tap. Thanks

**Comment by nandorojo** [comment]
I think that would be best achieved with a custom usage of the `onPressIn` prop, and one of the other hooks exported from `@motify/interactions`. You could also use Reanimated directly. Moti aims to be a more react-like, declarative approach to animations.

**Comment by siddharth-kt** [comment]
> I think that would be best achieved with a custom usage of the `onPressIn` prop, and one of the other hooks exported from `@motify/interactions`. You could also use Reanimated directly. Moti aims to be a more react-like, declarative approach to animations.

ok 👍
