### ISSUE TITLE
Bug (spring): combining opacity with translate will hide element on web after animation

### ISSUE THREAD

**Issue by hirbod** [nandorojo/moti#116]
Combining opacity with translate will hide element on web after animation. (opacity will be set back to 0)
This only happens with `spring` (also tried `overshootClamping: false`)
I also tried the old way (without transform array) and the result is the same. It does the animation and hides it afterwards. 

Works fine with `type: "timing"`

```tsx
<MotiView
    from={{ opacity: 0, transform: [{ translateY: 100 }] }}
    animate={{ opacity: 1, transform: [{ translateY: 0 }] }}
    style={styles.title}
>
```

This works fine:

```tsx
<MotiView
    from={{ opacity: 0, transform: [{ translateY: 100 }] }}
    animate={{ opacity: 1, transform: [{ translateY: 0 }] }}
    style={styles.title}
    transition={{ type: "timing" }}
>
```

Using `opacity` or transform alone, nothing breaks (even on spring). It just happens when combining them.

**Comment by Hirbod** [comment]
@nandorojo what I can tell you for sure is that it doesn't break on Native (iOS and Android working fine).
It just happens on web.
