### ISSUE TITLE
MotiView from animation freezes

### ISSUE THREAD

**Issue by judastheo** [nandorojo/moti#119]
Hello,

First of all, thank you so much for the `moti` library, I love using it!

In my app, I used custom card components that have an animation when appearing. I use a `MotiView`.

The issue I face is that often, when arriving on the screen, the animation seems to freeze and the card is blocked in an intermediate state.

The issue arises also when adding a new card element, it doesn't appear. (A toast is displayed at the same time)

Below is a code snippet

```
        <MotiView
          from={{
            opacity: 0,
            scale: 0.9,
          }}
          animate={{
            opacity: 1,
            scale: 1,
          }}
        >
         <Box backgroundColor="tomato" />
       </MotiView>
```

Inside the `MotiView`, I use a `Box` created using `createBox` from `@shopify/restyle` (1.4.0) and the navigation between screens is native as I use `react-native-navigation` (7.23.1). I use the `moti` 0.16.1.

Do you need more information? 

Thanks in advance!

**Comment by nandorojo** [comment]
This usage doesn’t look correct. The _children_ of AnimatePresense need to conditionally render. But in your case, you’re always rendering its child.

https://www.framer.com/docs/animate-presence/

In your case, the exit animation will never get fired, so you can remove `AnimatePresence` (and the `exit` prop)

**Comment by judastheo** [comment]
Thank you for this quick response! I removed AnimatePresence and exit prop, so the usage is seems correct now. But the issue still rises. I updated the opening message with the code left (also here below)

```
        <MotiView
          from={{
            opacity: 0,
            scale: 0.9,
          }}
          animate={{
            opacity: 1,
            scale: 1,
          }}
        >
         <Box backgroundColor="tomato" />
       </MotiView>
```

**Comment by nandorojo** [comment]
Can you send a video? What if you memoize this?

**Comment by judastheo** [comment]
I'm having a hard time to reproduce (even when using back the bad usage).

I won't use your time anymore for now, I'll reopen the issue if it comes back and I have a record and better insight!

Thanks, have a good week-end!
