### ISSUE TITLE
Access 'pressed' state in MotiPressable transition?

### ISSUE THREAD

**Issue by hugo-chq** [nandorojo/moti#120]
Hi thanks for making this library, it makes animating really simple

Is it possible to access the "pressed" state in MotiPressable in the transition prop, without wrapping around a view and using a hook?

Currently trying to make a PressableOpacity that animates quickly on press, and slowly on release, similar to iOS native topBar buttons

The preference for not using an inner view is to avoid potential issues with handling nested flex styles

iOS button (fast on press, slow on release):
![ezgif-6-a5dedf0c1506](https://user-images.githubusercontent.com/55731698/142350761-92216d9e-638c-4de5-aa50-f6deca91e388.gif)

**Comment by nandorojo** [comment]
A container view is better to avoid transforms affecting the animation. For instance, if you hover over an element, and it translates up 10px, it will no longer be hovered. 

By trapping interactions in the container, we isolate transforms to a separate View.

The feature you want is currently possible using the `useMotiPressableTransition` hook on children of `MotiPressable` components. It isn’t currently implemented for `transition` of `MotiPressable` itself, though I could implement this.

Using this hook, you could return a delay if pressed is false: https://moti.fyi/interactions/use-pressable-transition

**Comment by nandorojo** [comment]
I opened a PR that should add this feature:

```tsx
<MotiPressable
  transition={useMemo(
    () => ({ pressed }) => {
      return {
        delay: pressed ? 0 : 150
      }
    },
    []
  )}
/>
```

**Comment by hugo-chq** [comment]
Great thankyou! that PR solution is perfect 🙏 

`useMotiPressableTransition` is also working totally fine + has helpful docs,  thanks, 

not sure why I assumed flex/absolute-positon styles etc would break in the wrapped view

Here's the solution using `useMotiPressableTransition` 
```ts
type Props = ComponentProps<typeof DripsyMotiPressable> & {
  pressedOpacity?: number;
};

function HandleInnerTransition({animate, pressedOpacity, ...props}: Props) {
  const transition = useMotiPressableTransition(({pressed}) => {
    'worklet';

    return pressed
      ? {type: 'timing', duration: 50}
      : {type: 'spring', stiffness: 100, damping: 35};
  });
  const state = useMotiPressable(interaction => {
    'worklet';

    return mergeAnimateProp(interaction, animate, {
      opacity: interaction.pressed ? pressedOpacity : 1,
    });
  });

  return (
    <DripsyMotiView {...props} transition={transition} state={state}>
      {props.children}
    </DripsyMotiView>
  );
}

export default function PressableOpacity({
  pressedOpacity = 0.7,
  onPress,
  ...props
}: Props) {
  return (
    <MotiPressable onPress={onPress}>
      <HandleInnerTransition pressedOpacity={pressedOpacity} {...props} />
    </MotiPressable>
  );
}
```

the transition prop should also simplify the code quite a bit


Appreciate the quick reply and PR, thanks

**Comment by nandorojo** [comment]
Looks great! Happy to help.

PS I recommend using dependency arrays in the hooks for ideal performance. More future-proof too.

I'm also considering a `MotiPressableChild` feature, so that you can animate based on the parent without needing to make a new component.

```tsx
<MotiPressable>
  <MotiPressableChild 
    animate={({ hovered }) => ({ opacity: hovered ? 0.9 : 1 })} 
    transition={({ hovered }) => ({ delay: hovered ? 0 : 100 })} 
  >
    <SomeView />
  </MotiPressableChild>
</MotiPressable>
```
