### ISSUE TITLE
Accessibility props for MotiPressable

### ISSUE THREAD

**Issue by hugo-chq** [nandorojo/moti#124]
Would it be possible to support accessibility props for MotiPressable?

One use case is to prevent screen readers from seeing disabled/hidden buttons

I've added a PR [here](https://github.com/nandorojo/moti/pull/123) that passes the accessibility props directly, but not sure if a more generic 'pass all props' solution would be preferred?

thanks

**Comment by nandorojo** [comment]
Commented on your PR, seems reasonable to me

**Comment by nandorojo** [comment]
Added in #123
