### ISSUE TITLE
Issues with react-native key in package.json

### ISSUE THREAD

**Issue by breynolds-dev** [nandorojo/moti#126]
I ran into an issue while trying to use a lerna monorepo containing both my bare react native code and libraries one of which consumed `@motify/interactions` and `@motify/core`.

![image](https://user-images.githubusercontent.com/13542564/144514234-da2d81ee-1f4e-4afc-9ff0-edfe9266cb81.png)

These errors revolved around the `import type ...` in the source directory.  Looking into the `package.json` files I found that the keyword for `react-native` was pointing to the original source instead of the modules in the lib folder.  Changing these resolved all of my compilation errors and allowed me to use the packages again.

I'm not sure if this will break anything else, I ran the example in a forked repo and it worked fine.  If needed I can try to create a barebones example showing the issue and let you experiment with it, but I couldn't figure out how to resolve it without these changes.  Hoping a solution can be found so I can use these awesome animation libraries on my new project.

**Comment by breynolds-dev** [comment]
I'm going to close this and say sorry!  I might have found something that will fix it w/o any changes here

**Comment by nandorojo** [comment]
Be sure that all your Moti packages are installed at the same exact version.
