### ISSUE TITLE
Wrong transition types

### ISSUE THREAD

**Issue by mc-petry** [nandorojo/moti#129]
![image](https://user-images.githubusercontent.com/8122711/145169438-aabfefdf-c3fe-4bb9-8c62-484b79a197c7.png)

Problem:
`
Namespace 'Animated' has no exported member 'WithSpringConfig'.
Namespace 'Animated' has no exported member 'WithTimingConfig'.
`

moti: 0.16.1
reanimated: 2.3.0-beta.3 and 2.3.0-beta.4

**Comment by nandorojo** [comment]
Seems like 2.3.0 has some breaking changes for types. Will look into this once 2.3.0 releases some stability fixes for Web.

**Comment by nandorojo** [comment]
Fixed in the upcoming release from #137

```sh
yarn add moti@canary
```
