### ISSUE TITLE
Weird glitch with maxWidth prop

### ISSUE THREAD

**Issue by danielkv** [nandorojo/moti#130]
I'm building an animated Step component. It goes like this:
![image](https://user-images.githubusercontent.com/5912401/145217646-725699ba-a9a9-4b7a-8fbc-3fa888de33fa.png)

I'm trying to animate with the `maxWidth` property, since I don't have the total component width. But using this property I'm having a weird glitch right in the middle: https://photos.app.goo.gl/zEAXwxCRf88aQqgL8
As you can see in the **video** the bullet jumps to the center and restarts the animation till the end as if I had animated twice. I tried to change to `width` prop, it works fine, but since I don't have the width of the component, it's not gonna work properly.

Obs: This happes in all platforms: ios, android and web. 

This is the code of the `Step` component:

```jsx
        <StepsContainer>
            {steps.map((step, index) => {
                const isCurrent = index === current;
                const stepNumber = index + 1;
                return (
                    <Fragment key={index}>
                        <StepsStep
                            onPress={() => onStepPress?.(index)}
                            style={index > 0 && { marginLeft: BULLET_MARGIN }}
                        >
                            <StepsStepCircleLabel>{stepNumber}</StepsStepCircleLabel>
                        </StepsStep>

                        <MotiView
                            style={[{ overflow: 'hidden', flex: 1 }]}
                            animate={{ maxWidth: isCurrent ? screenWidth : 0 }}
                            transition={{ type: 'timing', duration: 3000 }}
                        >
                            <StepsLineContainer>
                                {step.label && <StepsStepLabel>{step.label}</StepsStepLabel>}
                                <StepsStepLine />
                            </StepsLineContainer>
                        </MotiView>
                    </Fragment>
                );
            })}
        </StepsContainer>
```

**Comment by nandorojo** [comment]
This seems expected. You're using flex to animate which is probably affecting the position of other elements. It would be better if you could measure the container/items, and use transform.

> I tried to change to width prop, it works fine, but since I don't have the width of the component, it's not gonna work properly.

You could utilize `onLayout` and fade components in once you've measured. It's an unfortunate reality, until we have synchronous measure in React Native.
