### ISSUE TITLE
Reanimated 2 failed to create a worklet

### ISSUE THREAD

**Issue by RohithBhandaru** [nandorojo/moti#132]
Hello,

I'm trying to use Moti and I seem to be hitting a wall with "Reanimated 2 failed to create a worklet, maybe you forgot to add Reanimated's babel plugin?" error. 

I've tried a couple of work arounds found on wild web like adding reanimated plugin to babel config and reset metro cache and run. Unfortunately none of them worked. Strange thing is I'm able to run native Animated transitions. Only when I try to use Moti, I'm getting this error. Any thoughts?

I'm trying to animate height of a horizontal scroll view which doesn't seem to be supported by native animations right now.

FYI,
"moti": "^0.16.1",
"react": "17.0.1",
"react-native": "0.64.2",
"react-native-reanimated": "^2.1.0",

babel.config.js :
module.exports = {
    presets: ['module:metro-react-native-babel-preset'],
    plugins: ['react-native-reanimated/plugin'],
};

**Comment by nandorojo** [comment]
I probably need more info about your setup and stuff. Can you create a minimal repro? Maybe try reanimated 2.2.2?

**Comment by RohithBhandaru** [comment]
I don't know why, but when I was running `npm run start --reset-cache`, cache wasn't getting cleared. But when I ran `npx react-native start --reset-cache`, cache cleared and Moti animations were working. So, I'm closing this issue. Thanks.
