### ISSUE TITLE
Support for Next and other SSR frameworks

### ISSUE THREAD

**Issue by fergusmeiklejohn** [nandorojo/moti#134]
Is the SSR support specific to Next or is it generic SSR support? I'd like to use Moti with Remix https://remix.run

thanks!

**Comment by nandorojo** [comment]
I’ve never tried with remix, but that’s cool that you are! I assume it should work, as long as remix can use the reanimated Babel plug-in. You may need the equivalent of next-transpile-modules to apply the Babel plug-in to moti too. Let me know how it goes, curious to see if it works.

**Comment by nandorojo** [comment]
If you get it working with remix, I'd be happy to add it to the docs btw
