### ISSUE TITLE
[question] useAnimationState support for transition configuration

### ISSUE THREAD

**Issue by jakobo** [nandorojo/moti#139]
Looking at the docs for `useAnimationState` and `useDynamicAnimationState` it appears they don't expose the same properties as elements like `MotiView`. Is there a preferred way to control the static animation timings? Here's what I was hoping to do in order to slow down a preconfigured animation:

```ts
const tagState = useAnimationState({
  from: {
    opacity: 1,
  },
  to: {
    opacity: 1,
  },
}, {
  transition: {
    type: "timing",
    duration: 250
  }
});
```

**Comment by nandorojo** [comment]
You can just pass `transition` to the component!

**Comment by markmccoid** [comment]
Is it possible to have each animation state have its own transition setting?

**Comment by nandorojo** [comment]
good question. I don't believe that's currently an option, although there may be some workarounds depending on what you're trying to do.
