### ISSUE TITLE
[iOS] Example app won’t start

### ISSUE THREAD

**Issue by nandorojo** [nandorojo/moti#146]
can't seem to run with-expo on iOS. I just get a blank screen. maybe we could make a new example app and copy over the files or something? @cmaycumber you mostly handled this if i recall correctly, would you be able to see if the example runs on iOS for you?

**Comment by cmaycumber** [comment]
Yeah definitely. I'll see if everything is running.

**Comment by nandorojo** [comment]
appreciate it thanks

**Comment by cmaycumber** [comment]
@nandorojo Were you getting it to build? Also was it a black blank screen? After getting it running it looked like the container for Moti.Pressable.tsx was styled as a black screen. I was able to get it built. 

I am having trouble getting Moti pressable to work, but the HelloWorld example does work as expected.

**Comment by nandorojo** [comment]
I'm just seeing a blank white screen, even when I just export a RN view. did you change anything for hello world, or did it work as is?

**Comment by nandorojo** [comment]
oh i was using regular expo start. i’ll try a dev client.

**Comment by nandorojo** [comment]
`expo run:ios` did fix this, thanks @cmaycumber!

**Comment by nandorojo** [comment]
Oof I have this issue again lol

**Comment by nandorojo** [comment]
Ignore that, it works.
