### ISSUE TITLE
<MotiPressable> box shadow not working on Android

### ISSUE THREAD

**Issue by agrawal-rohit** [nandorojo/moti#149]
# Issue
Shadows do not appear when using the `<MotiPressable />` component on Android (iOS works fine). However, when I use the original `Pressable` component from `react-native`, shows work fine.

## Configuration
- Expo: `44.0.4`
- Moti: `0.17.1`

### MotiPressable

**IOS**
<img src="https://user-images.githubusercontent.com/29514438/148696142-7d0a7e8d-656f-46fc-907a-4a2891c5bf95.png" width="200" />

**Android**
<img src="https://user-images.githubusercontent.com/29514438/148696316-745e7993-a29c-4219-85dc-bc9ecbfce0e5.png" width="200" />

### React Native Pressable

**IOS**
<img src="https://user-images.githubusercontent.com/29514438/148696267-9c8173bf-741d-4032-a641-90a505efaac2.png" width="200" />

**Android**
<img src="https://user-images.githubusercontent.com/29514438/148696286-40e2c264-5e7a-4c3f-8f98-fdfc04b6c45d.png" width="200" />

## Code
```jsx
<MotiPressable
  style={{
    padding: 20,
    overflow: "visible",
    backgroundColor: "white",
    shadowColor: "#1A2138",
    shadowOffset: {
      width: 0,
      height: 28,
    },
    shadowOpacity: 0.16,
    shadowRadius: 28,
    elevation: 28,
  }}
>
  <Text>Hello</Text>
</MotiPressable>
```

**Comment by nandorojo** [comment]
try containerStyle?

**Comment by agrawal-rohit** [comment]
Tried using `containerStyle`, didn't work.

```jsx
<MotiPressable
  containerStyle={{
    backgroundColor: "white",
    shadowColor: "#1A2138",
    shadowOffset: {
      width: 0,
      height: 28,
    },
    shadowOpacity: 0.16,
    shadowRadius: 28,
    elevation: 28,
    padding: 20,
  }}
>
  <Text>Hello</Text>
</MotiPressable>
```

**Comment by nandorojo** [comment]
is it a reanimated issue? did you wrap your app in the root gesture handler view?

**Comment by agrawal-rohit** [comment]
Yup, I've wrapped all the contents in `App` using the root gesture handler view like this:

```jsx
<GestureHandlerRootView style={{ flex: 1 }}>
    {/*  Rest of the components */}
</GestureHandlerRootView>
```

**Comment by nandorojo** [comment]
not sure, maybe try wrapping moti pressable with a normal view and put the shadow there. or make sure it works on an Animated.View too

**Comment by agrawal-rohit** [comment]
Here's what I've tried till now:

## 1. Shadow on `<View />` (Working)
```jsx
<View
  style={{
    backgroundColor: "white",
    shadowColor: "#1A2138",
    shadowOffset: {
      width: 0,
      height: 28,
    },
    shadowOpacity: 0.16,
    shadowRadius: 28,
    elevation: 28,
  }}
>
  <MotiPressable
    containerStyle={{
      backgroundColor: "white",
      padding: 20,
    }}
  >
    <Text>Hello</Text>
  </MotiPressable>
</View>
```

## 2. Shadow on `<Animated.View />` (Working)
```jsx
<Animated.View
  style={{
    backgroundColor: "white",
    shadowColor: "#1A2138",
    shadowOffset: {
      width: 0,
      height: 28,
    },
    shadowOpacity: 0.16,
    shadowRadius: 28,
    elevation: 28,
  }}
>
  <MotiPressable
    containerStyle={{
      backgroundColor: "white",
      padding: 20,
    }}
  >
    <Text>Hello</Text>
  </MotiPressable>
</Animated.View>
```

## 3. Shadow on `<MotiView />` (Working)
```jsx
<MotiView
  style={{
    backgroundColor: "white",
    shadowColor: "#1A2138",
    shadowOffset: {
      width: 0,
      height: 28,
    },
    shadowOpacity: 0.16,
    shadowRadius: 28,
    elevation: 28,
  }}
>
  <MotiPressable
    containerStyle={{
      backgroundColor: "white",
      padding: 20,
    }}
  >
    <Text>Hello</Text>
  </MotiPressable>
</MotiView>
```

**Comment by agrawal-rohit** [comment]
I think I've got a fix for this, it seems to be happening because of the use of `containerStyle` on the `AnimatedTouchable` in the `<MotiPressable />` component

# Updated Code

```jsx
const AnimatedTouchable = Animated.createAnimatedComponent(
  TouchableWithoutFeedback
);

const App = () => {
  return (
   <GestureHandlerRootView style={{ flex: 1 }}>
        <AnimatedTouchable
          style={{
            padding: 20,
            overflow: "visible",
            backgroundColor: "white",
            shadowColor: "#1A2138",
            shadowOffset: {
              width: 0,
              height: 28,
            },
            shadowOpacity: 0.16,
            shadowRadius: 28,
            elevation: 28,
          }}
        >
          <MotiView>
            <Text>Hello</Text>
          </MotiView>
        </AnimatedTouchable>
   </GestureHandlerRootView>
  );
};
```

# Output

## IOS 

<img src="https://user-images.githubusercontent.com/29514438/148748278-3ee84931-03eb-49cb-acbf-8c0c589f57d9.png" width="200" />

## Android 

<img src="https://user-images.githubusercontent.com/29514438/148749198-f16e646d-29d9-4e3c-b969-728d50a33bf3.png" width="200" />

# Further Comments
I'm skeptical about having the current implementation of`MotiPressable` from a styling perspective. Wouldn't it be easier if we wrote it as:
 
```jsx
const MotiTouchable = motify(TouchableWithoutFeedback)();

const MotiPressable = (props) => {
   // ... methods and state management

  return (
      <MotiTouchable {...props}>
          {props.children}
     </MotiTouchable>
  )
}
```
