### ISSUE TITLE
Moti Interaction on Expo Storybook ?

### ISSUE THREAD

**Issue by fortezhuo** [nandorojo/moti#150]
Hi, 

Can moti interaction work on expo storybook ? I have created expo snack and animation is not working based on https://snack.expo.dev/@siddharth-tyagi/moti-pressable

Please find : https://snack.expo.dev/@fortezhuo/df633d

**Comment by nandorojo** [comment]
not sure tbh, @axeldelafosse do you have this working with story book?

**Comment by axeldelafosse** [comment]
Yeah!

**Comment by fortezhuo** [comment]
@axeldelafosse 

Please elaborate how to make moti working on storybook 🙏

**Comment by axeldelafosse** [comment]
Here is an example: https://github.com/axeldelafosse/storybook-rnw-monorepo/tree/main/apps/storybook-react-native

**Comment by nandorojo** [comment]
@axeldelafosse thanks! would be good to upgrade to the latest Moti/remove the extra skeleton

**Comment by nandorojo** [comment]
closing since this looks solved!
