### ISSUE TITLE
Animation on exit works but component doesn't unmount

### ISSUE THREAD

**Issue by cdedreuille** [nandorojo/moti#153]
I'm having an issue when animating components when they unmount. Some components unmount after the exit animation but some don't and I'm not sure why. In this case, when I change the state from `thankYou` to `null`, the `ThankYouBreakpoint` component animate on exit correctly but stay at the end. The component should be unmounted but I'm not sure why it is not.

Here is my code:
```
const [breakpoint, setBreakpoint] = useState(null);

<AnimatePresence>
  {breakpoint === 'thankYou' && <ThankYouBreakpoint />}
  {breakpoint === 'goodJob' && <WellDoneBreakpoint />}
  {breakpoint === 'doneForToday' && <ComeBackBreakpoint />}
</AnimatePresence>
```
In each component (ThankYouBreakpoint, WellDoneBreakpoint, ComeBackBreakpoint):
```
<MotiView
  transition={{
    type: 'timing',
    duration: theme.animations.discoverOverlay.duration,
  }}
  from={{ opacity: 0 }}
  animate={{ opacity: 1 }}
  exit={{ opacity: 0 }}>
  <Background
    source={backgroundImage}
    imageStyle={{
      height: backgroundImageHeight,
    }}>
    <ScreenContainer>
      <Header />
      <StyledScreenContainer>{content}</StyledScreenContainer>
      <ActionsContainer>{actions}</ActionsContainer>
    </ScreenContainer>
  </Background>
</MotiView>
```

Any idea why this is happening?

**Comment by nandorojo** [comment]
You need to add a unique key prop to each child of `AnimatePresence`

**Comment by cdedreuille** [comment]
That fixes it. Thanks a lot @nandorojo
