### ISSUE TITLE
animate prop and background color not working with reanimated version 2.3.1

### ISSUE THREAD

**Issue by sanborN93** [nandorojo/moti#154]
Since we have upgraded to reanimated 2.3.1 the animate prop doesn't support backgroundcolor anymore.

`
<MotiView
 from={{ opacity: 0 }}
animate={{
opacity: 1,
backgroundColor: isTest ? colors.canvasPrimary : colors.secondaryMain,
 }}>
          <Text>Test
</MotiView>`

Guess it is related to changes with that version. Has anyone more information about it?

**Comment by nandorojo** [comment]
this is a reanimated issue: https://github.com/software-mansion/react-native-reanimated/issues/2751
