### ISSUE TITLE
View breaks when `shadowOffset` property is passed to the `animate` property

### ISSUE THREAD

**Issue by agrawal-rohit** [nandorojo/moti#155]
# Description

When I'm trying to add the `shadowOffset` style property value to the `animate` property in `MotiView`, the view doesn't render anymore. I'm assuming it could be because `shadowOffset` has an object-based value and that is breaking something under the hood.

# Steps to Reproduce

## Code 

```jsx
<MotiView
  from={{ opacity: 0 }}
  animate={{
    opacity: 1,
    shadowColor: "#1A2138",
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.5,
    shadowRadius: 20,
  }}
  style={{
    width: 200,
    height: 400,
    backgroundColor: "aqua",
  }}
/>
```

## Screenshot
<img src="https://user-images.githubusercontent.com/29514438/149845236-df1b9fa4-9571-45f8-a653-2e42e1f68f57.png" width="300" />

# Expected Behaviour

Ideally, the shadow should appear as below (when applied to the regular `style` property).

## Code 

```jsx
<MotiView
  from={{ opacity: 0 }}
  animate={{
    opacity: 1,
  }}
  style={{
    width: 200,
    height: 400,
    backgroundColor: "aqua",
    shadowColor: "#1A2138",
    shadowOffset: {
      width: 40,
      height: 40,
    },
    shadowOpacity: 0.5,
    shadowRadius: 20,
  }}
/>
```

## Screenshot
<img src="https://user-images.githubusercontent.com/29514438/149845383-d13598ac-87e5-4474-a241-922faec625f4.png" width="300" />

**Comment by nandorojo** [comment]
does reanimated support animating this property?

**Comment by agrawal-rohit** [comment]
It seems like `reanimated` doesn't support the `shadowOffset` property by default ([supported props list](https://github.com/software-mansion/react-native-reanimated/blob/688a244b3826b0f6cde52e9490eee5fe0d3e9bf9/src/ConfigHelper.ts)), but it can be supported by explicitly whitelisting it (Check out [this issue](https://github.com/software-mansion/react-native-reanimated/issues/634#issuecomment-671494047) on `reanimated`)

Something like the following:

```jsx
import Animated from 'react-native-reanimated';
Animated.addWhitelistedUIProps({shadowOffset:true});

const X = () => {
  return <Animated.View
    style={[
      {
        shadowOffset: {
          height: 2
          width: 0,
        },
      },
    ]}
  />
}
```

**Comment by nandorojo** [comment]
does that fix it for moti?

**Comment by agrawal-rohit** [comment]
Ahh my bad, apparently [the issue](https://github.com/software-mansion/react-native-reanimated/issues/634#issuecomment-671494047) I mentioned before is from Reanimated V1. `shadowOffset` seems to be supported by default in Reanimated V2.

The issue, I think, is occurring when `shadowOffset` is being used with the animation hooks (`withTiming`, `withSpring`, etc). This is because these hooks expect `number | string` values only, while `shadowOffset` is an `object` ([reference](https://docs.swmansion.com/react-native-reanimated/docs/api/animations/withTiming) in Reanimated docs).

Following are a couple of examples of what I'm talking about:

# Working Example 1 (without Animation hooks)

![2022-01-22 04 34 01](https://user-images.githubusercontent.com/29514438/150611268-e1c2670e-e38e-4b70-b7ab-02f25013345e.gif)

## Code

```jsx
import Animated, {
  useAnimatedStyle,
  withTiming,
} from "react-native-reanimated";
import { View } from "react-native";

const App = () => {
  const [shadowFlag, setShadowFlag] = useState(false);

  const AnimatedView = Animated.createAnimatedComponent(View);

  const animatedStyles = useAnimatedStyle(() => {
    return {
      shadowOpacity: withTiming(shadowFlag ? 1 : 0.5, { duration: 200 }),
      shadowOffset: disabled
        ? {
            width: 50,
            height: 50,
          }
        : {
            width: 10,
            height: 10,
          },
    };
  });

  return (
     <>
        <AnimatedView
          style={[
            {
              width: 200,
              height: 200,
              backgroundColor: "aqua",
              shadowColor: "#1A2138",
              shadowRadius: 20,
            },
            animatedStyles,
          ]}
        />

        <Button
          from={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          mt="xl"
          isFullWidth
          transition={{ type: "timing" }}
          onPress={() => setShadowFlag(!shadowFlag)}
        >
          Toggle Shadow
        </Button>
      <>
  );
};
```

# Working Example 2 (with Animation hooks)

When I apply `withTiming` to the individual properties of `shadowOffset`, the animation works as expected.

![2022-01-22 04 28 27](https://user-images.githubusercontent.com/29514438/150610918-db0ec431-c088-4043-8090-842d988d5cd4.gif)

## Code

```jsx
import Animated, {
  useAnimatedStyle,
  withTiming,
} from "react-native-reanimated";
import { View } from "react-native";

const App = () => {
  const [shadowFlag, setShadowFlag] = useState(false);

  const AnimatedView = Animated.createAnimatedComponent(View);

  const animatedStyles = useAnimatedStyle(() => {
    return {
      shadowOpacity: withTiming(shadowFlag ? 1 : 0.5, { duration: 200 }),
      shadowOffset: {
        width: withTiming(shadowFlag ? 50 : 10, { duration: 200 }),
        height: withTiming(shadowFlag ? 50 : 10, { duration: 200 }),
      },
    };
  });

  return (
     <>
        <AnimatedView
          style={[
            {
              width: 200,
              height: 200,
              backgroundColor: "aqua",
              shadowColor: "#1A2138",
              shadowRadius: 20,
            },
            animatedStyles,
          ]}
        />

        <Button
          from={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          mt="xl"
          isFullWidth
          transition={{ type: "timing" }}
          onPress={() => setShadowFlag(!shadowFlag)}
        >
          Toggle Shadow
        </Button>
      <>
  );
};
```

# Example with issues

I get several type errors when I wrap the `withTiming` hook around the `shadowOffset` object.

<img src="https://user-images.githubusercontent.com/29514438/150611625-8c0d47be-7164-458c-8d11-3571a8c2f33b.png" width="500" />
<img src="https://user-images.githubusercontent.com/29514438/150611705-befc1293-e74e-4774-a498-91350fcf34fb.png" width="200" />

## Code

```jsx
import Animated, {
  useAnimatedStyle,
  withTiming,
} from "react-native-reanimated";
import { View } from "react-native";

const App = () => {
  const [shadowFlag, setShadowFlag] = useState(false);

  const AnimatedView = Animated.createAnimatedComponent(View);

  const animatedStyles = useAnimatedStyle(() => {
    return {
      shadowOpacity: withTiming(shadowFlag ? 1 : 0.5, { duration: 200 }),
      shadowOffset: withTiming(
        disabled
          ? {
              width: 50,
              height: 50,
            }
          : {
              width: 10,
              height: 10,
            },
        {
          duration: 500,
        }
      ),
    };
  });

  return (
     <>
        <AnimatedView
          style={[
            {
              width: 200,
              height: 200,
              backgroundColor: "aqua",
              shadowColor: "#1A2138",
              shadowRadius: 20,
            },
            animatedStyles,
          ]}
        />

        <Button
          from={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          mt="xl"
          isFullWidth
          transition={{ type: "timing" }}
          onPress={() => setShadowFlag(!shadowFlag)}
        >
          Toggle Shadow
        </Button>
      <>
  );
};
```

**Comment by nandorojo** [comment]
Yeah that seems like a fair feature to add if reanimated supports it

**Comment by nandorojo** [comment]
I oddly thought I was doing a check for objects inside that function, but I never tested shadows much. I'd review a PR

**Comment by agrawal-rohit** [comment]
Awesome, I'll open a PR for this. I'm guessing all the code related to this issue lives inside the [use-map-animate-to-style.tsx](https://github.com/nandorojo/moti/blob/master/packages/core/src/use-map-animate-to-style.ts) file. 

Could you point me towards a particular part of the flow where this fix should occur? (This particular file is quite hard to decipher)

**Comment by nandorojo** [comment]
yeah let me see. i know it can be a bit tough, there's some magic going on in there haha

**Comment by nandorojo** [comment]
line 531 is what you want. that basically says, if the `value` for a given style is an object, then go through and apply `final[key] = animation(value)`, where `animation` is `withTiming`/`withSpring`

**Comment by agrawal-rohit** [comment]
Awesome! I'll check that part out. Thanks! 😇

**Comment by nandorojo** [comment]
feel free to reference the `perf` branch if you want to work on this still. going to close for now though.
