### ISSUE TITLE
Animate from a list

### ISSUE THREAD

**Issue by cdedreuille** [nandorojo/moti#158]
I'm not sure this is an issue related to Moti but I can't find a way to animate an array of cards. All our code is doing is updating a state called `currentDiscoverIndex` to update a list of artworks. I have a correct animation on mount but when I update the state the animation is very junky. I'm not sure if this is due to keys not being added correctly. I just can't figure out what I'm doing wrong.

Here is my code:

Container
```tsx
const Wrapper = styled(AnimatePresence)<{ containerHeight: number }>(
  ({ containerHeight }) => ({
    width: '100%',
    height: containerHeight,
  }),
);

const newArtworks = useMemo(
  () => artworks.slice(currentDiscoverIndex, currentDiscoverIndex + count),
  [artworks, currentDiscoverIndex],
);

return (
  <Wrapper containerHeight={containerHeight}>
    {newArtworks.map((card) => (
      <Card
        key={card.id}
        artwork={card}
        containerHeight={containerHeight}
      />
    ))}
  </Wrapper>
)
```

Card component
```tsx
const Wrapper = styled(MotiView)({
  width: '100%',
  height: '100%',
});

<Wrapper
  key={artwork.id}
  from={{
    opacity: 0,
    translateX: -40,
  }}
  animate={{
    opacity: 1,
    translateX: 0,
  }}
  exit={{
    opacity: 0,
    translateX: -40,
  }}>
{ ... }
</Wrapper>
```

Any chance someone has an idea where I could do something wrong?

**Comment by nandorojo** [comment]
Yeah plenty of this looks off. `exit` only works as child of an `AnimatedPresence` component. And each So you should wrap your array of `newArtworks` with `<AnimatePresence>`

**Comment by cdedreuille** [comment]
@nandorojo It is wrapped with `<AnimatePresence>`

```tsx
const Wrapper = styled(AnimatePresence)<{ containerHeight: number }>(
  ({ containerHeight }) => ({
    width: '100%',
    height: containerHeight,
  }),
);
```

But I'll try without applying some styles to it. My thoughts are that the array for some reason doesn't unmount the correct elements or that React doesn't recognise that this is the right one. Still investigating.

PS: Thansk for the tip on ```tsx. Looks indeed much better.

**Comment by nandorojo** [comment]
I see. For starters, AnimatePresence doesn't accept styles, so that doesn't apply

**Comment by nandorojo** [comment]
Also, is there a reason you're applying a key in the Card component too? I don't see why that's there.

**Comment by cdedreuille** [comment]
It is indeed working correctly now 👍 Thanks a lot for your help.
