### ISSUE TITLE
On state change and component re-rendering animation becomes junky.

### ISSUE THREAD

**Issue by umairbutt088** [nandorojo/moti#159]
First of all thanks for providing this wonderful library.

**ISSUE**

I am using `MotiView` for creating Waves animation and every time the component mounts it is working fine and on state update, the animation becomes junky and stops working at the end.
I have also wrapped my animation component into the `AnimatePresence` but still no success.

**Code Sample**

```tsx
     <AnimatePresence style={[styles.dot, styles.center]}>
        {[...Array(5).keys()].map(index => {
          return (
            <MotiView
              from={{opacity: 1, scale: 0}}
              animate={{opacity: 0, scale: 9}}
              transition={{
                type: 'timing',
                duration: durationCal,
                easing: Easing.inOut(Easing.ease),
                delay: index * 400,
                repeatReverse: false,
                loop: true,
              }}
              key={index}
              style={[StyleSheet.absoluteFillObject, styles.dot]}
            />
          );
        })}
     </AnimatePresence>
```
      
**Demo Video**
 
https://user-images.githubusercontent.com/67545083/151162365-ed8ec682-f8ff-4472-9e6d-f8e28f690bb4.mov

**Comment by usamaabutt** [comment]
I am also facing the same issue. Any chance to get help on it @nandorojo. Thanks!

**Comment by nandorojo** [comment]
what's the point of animate presence here if you don't have an exit prop?

**Comment by nandorojo** [comment]
also animate presence doesn't accept styles

**Comment by umairbutt088** [comment]
@nandorojo As I have shown in the attached video I am trying to create waves that will never end to animate and I have control their frequency dynamically for that I am using a local state. But every time the state change the animation becomes junky in the start and then stops. 

I have shown this behavior in the above-attached video and thanks for helping out me.


```
<AnimatePresence>
        <View style={[styles.dot, styles.center]}>
          {[...Array(5).keys()].map(index => {
            return (
              <MotiView
                key={(Math.random() + 1).toString(36).substring(7)}
                from={{opacity: 1, scale: 0}}
                animate={{opacity: 0, scale: 9}}
                exit={{opacity: 1, scale: 0}}
                transition={{
                  type: 'timing',
                  duration: durationCal,
                  easing: Easing.inOut(Easing.ease),
                  delay: index * 400,
                  repeatReverse: false,
                  loop: true,
                }}
                key={index}
                style={[StyleSheet.absoluteFillObject, styles.dot]}
              />
            );
          })}
        </View>
      </AnimatePresence>
```

**Comment by nandorojo** [comment]
This code isn't proper. `AnimatePresence` requires components with unique keys as direct children. Also, if you want an infinite loop, there's no reason to use `AnimatePresence` or `exit`.

**Comment by nandorojo** [comment]
As for potentially weird behavior with state changes + loops, if they persist, I recommend memoizing your moti components. To avoid them changing from parent state components.

```tsx
const animation = useMemo(() => {
  ;[...Array(5).keys()].map((index) => {
    return (
      <MotiView
        key={(Math.random() + 1).toString(36).substring(7)}
        from={{ opacity: 1, scale: 0 }}
        animate={{ opacity: 0, scale: 9 }}
        exit={{ opacity: 1, scale: 0 }}
        transition={{
          type: 'timing',
          duration: durationCal,
          easing: Easing.inOut(Easing.ease),
          delay: index * 400,
          repeatReverse: false,
          loop: true
        }}
        key={index}
        style={[StyleSheet.absoluteFillObject, styles.dot]}
      />
    )
  })
}, [])
```

**Comment by nandorojo** [comment]
Is the issue that changing `duration` breaks it?

**Comment by umairbutt088** [comment]
Alright, I will remove `AnimatePresence` and `exit` prop then what will be the solution to my issue. And thanks for the suggestion to use `useMemo` I am actually using it like this:

```
const normal_speed = 2000;
```

```
  const [waveCounter, setWaveCounter] = useState(100);
```

```
const onSwipe = () => {
    setIsBackground(true);
    setWaveCounter(waveCounter + 100);
  };
  
  ```

```
const durationCal = useMemo(() => {
    const durationValue = JSON.parse(normal_speed) - waveCounter;
    return JSON.stringify(durationValue);
  }, [waveCounter]);
  
```

```
const BottomMotiView = useMemo(
    () => (
      <AnimatePresence>
        <View style={[styles.dot, styles.center]}>
          {[...Array(5).keys()].map(index => {
            return (
              <MotiView
                key={(Math.random() + 1).toString(36).substring(7)}
                from={{opacity: 1, scale: 0}}
                animate={{opacity: 0, scale: 9}}
                exit={{opacity: 1, scale: 0}}
                transition={{
                  type: 'timing',
                  duration: durationCal,
                  easing: Easing.inOut(Easing.ease),
                  delay: index * 400,
                  repeatReverse: false,
                  loop: true,
                }}
                key={index}
                style={[StyleSheet.absoluteFillObject, styles.dot]}
              />
            );
          })}
        </View>
      </AnimatePresence>
    ),
    [waveCounter],
  );
  ```

**Comment by nandorojo** [comment]
why is `durationCal` using `JSON.parse` and `JSON.stringify`? Shouldn't it just be this?

```tsx
const durationCal = Number(normal_speed) - waveCounter
```

Is `normal_speed` a string or something?

PS you can format your code if you add backticks like this: ```tsx at the start of your code block.

**Comment by nandorojo** [comment]
<img width="528" alt="Screen Shot 2022-01-26 at 10 21 53 AM" src="https://user-images.githubusercontent.com/13172299/151191822-b6a1321b-9323-4763-9f44-1431f7f1f86d.png">

I just saw an issue with your code here. You're using random numbers for `key` here. That is guaranteed to break code in react. It should always be a stable ID, or an index if indices are stable. This is guaranteeing a full re-render and random behavior. I'm almost certain this is never what you should do.

> @nandorojo `normal_speed` is a number.

In this case, your code should just be this:

```ts
const durationCal = normal_speed - waveCounter
```

Also, rather than a state change, use a shared value. Moti lets you pass the result of `useDerivedValue` to `transition`, meaning you don't have to trigger re-renders and get better performance. You'll have to split each item into its own component, and then you can do something like this:

```tsx
const waveCounter = useSharedValue(100)
const onSwipe = () => {
  'worklet'

  // change your waveCounter here somehow
  waveCounter.value = 200
}

// then return each item

// then inside of each item

const transition = useDerivedValue(() => ({
  type: 'timing',
  duration: normal_speed - waveCounter.value,
  easing: Easing.inOut(Easing.ease),
  delay: index * 400,
  repeatReverse: false,
  loop: true
}))

return <MotiView transition={transition} />
```

Do not use `exit` or `AnimatePresence`, they don't make sense here.

**Comment by umairbutt088** [comment]
Thanks, @nandorojo let me try this one and I will be back to you shortly.

**Comment by usamaabutt** [comment]
@nandorojo  I have the same issue and it's not fixed by following what you have suggested!

**Comment by nandorojo** [comment]
Please create a reproducible snack, I can't help with that.

**Comment by usamaabutt** [comment]
Sure I will try to reproduce it and share it with you today.

**Comment by usamaabutt** [comment]
Hi @nandorojo actually I am not able to create a reproducible snack because of reanimated2 and gesture-handler version issue.
By the way, I have created a sample class which is having the code for this whole scenario. Hopefully, this will be helpful to reproduce this issue on your side.


```
import {View, StyleSheet} from 'react-native';
import React from 'react';
import {MotiView} from 'moti';
import {Easing, useDerivedValue, useSharedValue} from 'react-native-reanimated';

const Test = () => {
  return (
    <View style={styles.container}>
      <View style={{alignSelf: 'center'}}>
        {[...Array(5).keys()].map(index => {
          return <MotiViewShow index={index} />;
        })}
      </View>
    </View>
  );
};

const MotiViewShow = ({index}) => {
  const waveCounter = useSharedValue(2000);
  React.useEffect(() => {
    setInterval(() => {
      onValueChange();
    }, 3000);
  }, []);

  React.useEffect(() => {
    console.log('value', waveCounter.value);
  }, [waveCounter.value]);

  const onValueChange = () => {
    'worklet';

    // change your waveCounter here somehow
    waveCounter.value = waveCounter.value - 50;
  };

  const transition = useDerivedValue(() => ({
    type: 'timing',
    duration: waveCounter.value.toString(),
    easing: Easing.inOut(Easing.ease),
    delay: index * 400,
    repeatReverse: false,
    loop: true,
  }));
  return (
    <MotiView
      from={{opacity: 1, scale: 0}}
      animate={{opacity: 0, scale: 9}}
      transition={transition}
      style={[StyleSheet.absoluteFillObject, styles.dot]}
    />
  );
};

export default Test;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  dot: {
    width: 52,
    height: 52,
    borderRadius: 50,
    backgroundColor: '#417040', //'#417040',
  },
});
```

And here is the demo video attached for this scenario.

https://user-images.githubusercontent.com/44516486/154840512-609534da-7bd7-4537-aadc-6f4f1f3e90f2.mp4

**Comment by usamaabutt** [comment]
Hi @nandorojo did you able to get some time to reproduce it on your side?

**Comment by nandorojo** [comment]
> Hi @nandorojo actually I am not able to create a reproducible snack because of reanimated2 and gesture-handler version issue.

I believe these do work on Snack for iOS
