### ISSUE TITLE
App crashed on reanimated 2.0.0-rc.3 and RN64 android 

### ISSUE THREAD

**Issue by zifahm** [nandorojo/moti#16]
I have ported all my code to RN64 and reanimated 2.0.0-rc.3. My app crashes on simply calling  ```<MotiView/>```

## Crash Logs
![Screenshot from 2021-02-10 15-00-48](https://user-images.githubusercontent.com/3761062/107491285-f1330180-6bb0-11eb-911e-347e731caa59.png)

**Comment by nandorojo** [comment]
Moti is only tested on `2.0.0-rc.0`.

Please search the reanimated issues for this. The stack trace clearly shows a reanimated issue.

**Comment by zifahm** [comment]
Alright Closing the issue
