### ISSUE TITLE
List Items and Callback. 

### ISSUE THREAD

**Issue by etiennelacoursiere** [nandorojo/moti#160]
Hi, i've been trying to do something in Moti that i can quite figure out. 

I have a vertical list of Choices. When i pressed one of the Choices i want it to scale down and then i want to trigger a function. 

I tried something with`onDidAnimate` but im not sure it's the best way. I saw in another issue that i should animate based on the app state rather than reacting to animation. Would love to know how to go about that? 

Right now i have something like this but i don't like it i would like to separate the Choice Component from the AnimatedWrapper. To have it as a children. 

``` 
const SingleChoiceQuestion = () => {
  return (
    <Column space="sm">
      {choices.map((choice) => (
        <AnimatedChoice
          choice={choice}
          onPress={() => alert('This should trigger after the animation')}
        />
      ))}
    </Column>
  )
}


const AnimatedChoice = ({ choice, onPress }) => {
  const scaleTo = 0.95

  const animationState = useAnimationState({
    from: { scale: 1 },
    pressed: { scale: scaleTo },
  })

  return (
    <MotiView
      state={animationState}
      onDidAnimate={(_style, finisehd, _value, { attemptedValue }) => {
        if (finisehd && attemptedValue === scaleTo) {
          onPress()
        }
      }}
    >
      <Choice
        id={choice.id}
        onPress={() => animationState.transitionTo('pressed')}
      >
        {choice.text}
      </Choice>
    </MotiView>
  )
}
```

EDIT: 

To clarify, how can i make a pressable animation reusable. Like if i want another component to do the same thing?
I saw there's a MotiPressable but my choice component is already a pressable and i don't always want it to animate. 

Don't know if i'm making any sense at all :P 

Sorry it's not really an issue i know.

**Comment by nandorojo** [comment]
I would recommend using `MotiPressable`, since it handles this for you. It's made for this use case. Alternatively, you could do this maybe?

```tsx
const AnimatedChoice = ({ choice, onPress }) => {
  const scaleTo = 0.95

  const animationState = useAnimationState({
    from: { scale: 1 },
    pressed: { scale: scaleTo }
  })

  return (
    <MotiView state={animationState}>
      <Choice
        id={choice.id}
        onPressIn={() => animationState.transitionTo('pressed')}
        onPressOut={() => animationState.transitionTo('from')}
        onPress={onPress}
      >
        {choice.text}
      </Choice>
    </MotiView>
  )
}
```

PS please add `tsx` to your code sample back ticks to make it easier to read, like this: ```tsx

Let me know if that works!

**Comment by etiennelacoursiere** [comment]
Hi, i tried both solutions and they both don't give me the result i'm looking for. 

`onPress` is always called before the animation end. 

What i really need is for a button scale down then back to original size and after this animation is done trigger the `onPress` callback. 

Looking at the doc i thought this code would do that. But onPress is called as soon as i pressed and the animation doesn't have time to finish. 

```tsx
export default (props: ChoiceProps & any) => {
  const animate = React.useMemo(
    () =>
      ({ pressed }) => {
        'worklet'

        return {
          scale: pressed ? 0.95 : 1,
        }
      },
    [],
  )

  const transition = React.useMemo(
    () =>
      ({ pressed }) => {
        'worklet'

        return {
          delay: pressed ? 0 : 100,
        }
      },
    [],
  )

  return (
    <MotiPressable
      onPress={props.onPress}
      animate={animate}
      transition={transition}
    >
      ...
    </MotiPressable>
  )
}
```

Any idea? Is this possible with Moti or would i have to use Reanimated2 for this particular use case?

**Comment by nandorojo** [comment]
it’s a bit unusual to do that, since delaying a press event that isn’t properly cancellable could lead to bugs for the user, and makes the app feel slow. Given that, it may be best to use a reanimated 2 callback if it better suits your needs for this case.
