### ISSUE TITLE
Looping / repeating animations stop playing when native prompt are shown

### ISSUE THREAD

**Issue by IljaDaderko** [nandorojo/moti#162]
Attached video demonstrates the problem. Essentially any looping / repeating animation stops playing when some sort of native ui is shown (in this case apple sign in prompt, but it also happens with react-native Alert).

https://user-images.githubusercontent.com/3154053/151843698-0fb9f0e2-8ef6-48f2-bcbd-12052ea47da8.mov

**Comment by nandorojo** [comment]
I don't think this is related to `moti`, is it? My guess is it's a Reanimated issue.

**Comment by IljaDaderko** [comment]
> I don't think this is related to `moti`, is it? My guess is it's a Reanimated issue.

Started discussion about this in reanimated repo https://github.com/software-mansion/react-native-reanimated/discussions/2912 hopefully they can confirm whats going on. I'll close this issue once they do or if you are 100% sure it's not related to Moti, feel free to do so as well 👍

**Comment by nandorojo** [comment]
thanks!
