### ISSUE TITLE
Animation break in wrap component

### ISSUE THREAD

**Issue by devzucca** [nandorojo/moti#169]
Why is it that if I wrap an animated component with moti, the animation is deactivated?

**Comment by nandorojo** [comment]
probably because Moti Views are already Animated views.

**Comment by devzucca** [comment]
thanks for answering fernando... a question and excuse me there is not an example of hover animation for moti? what can i use for web expo? like the one at the top of the moti documentation page but creating a custom animation?

**Comment by nandorojo** [comment]
that may be a native base issue.

check out the dropdown menu from the examples

**Comment by devzucca** [comment]
Thank you very much for your time, greetings from Venezuela, I hope to collaborate with your work one day, since I think the same about the multiplatform, that is, your approach, I am still learning, I hope to be able to contribute soon. I admire your job.

and I find myself studying that example, thanks

**Comment by nandorojo** [comment]
good luck! I was a React beginner not long ago 😎 keep at it
