### ISSUE TITLE
framer-motion dependency

### ISSUE THREAD

**Issue by gut4** [nandorojo/moti#17]
Looks like framer-motion dependency adds around 90kb to js bundle. It's critical for web usage.
Is it necessary?

**Comment by nandorojo** [comment]
Hmm that's interesting, I didn't know that. 

@mattgperry curious if you have thoughts here. I'm using the `usePresence` hook in each component, so I'm assuming that's importing all of framer motion. Is there a better way to do this?

Tree shaking on React Native Web is incredibly hard to maintain. It takes very little to mess it up, so it's not very reliable.

**Comment by mattgperry** [comment]
I actually just added `sideEffects: false` to `package.json` in the latest version, will that help?

**Comment by nandorojo** [comment]
Yeah it should do it in principle. I'll update and try pushing that out, thanks for the quick response here.

**Comment by gut4** [comment]
https://bundlephobia.com/result?p=framer-motion@3.5.2  
Hmm ```sideEffects: false``` doesn't help. Each export has the same size as whole bundle.

**Comment by mattgperry** [comment]
That's odd, it's the same with `popmotion`. I don't know enough about this to be able to fix it right away, will have to do some debugging.

**Comment by nandorojo** [comment]
Webpack's tree shaking is something I've had trouble finding good content on. Besides a short explanation on their docs saying that you should use `sideEffects: true`, I haven't seen too much. I also don't know enough about this.

@mattgperry if you need any help figuring this out for Framer, let me know.

**Comment by mattgperry** [comment]
I've published new versions of `popmotion` and `framer-motion` with the `preserveModules: true` which helps Webpack code-splitting ES modules. So `3.8.0` should have a minimal footprint for `AnimatePresence` (about 2.5kb)

**Comment by nandorojo** [comment]
Thanks to @mattgperry's update, `moti` is now down to 4.4kb gzipped: https://bundlephobia.com/result?p=moti@0.5.4

`yarn add moti`

@gut4 thanks for bringing this to my attention.
