### ISSUE TITLE
Skeleton randomly fails to hide

### ISSUE THREAD

**Issue by kickbk** [nandorojo/moti#171]
Using `@motify/skeleton` v. 0.16.1
```js
<Skeleton
      show={true}
      radius={skeletonRadius !== undefined ? skeletonRadius : 4}
      height={skeletonHeight}
    >
      ...
</Skeleton>
```
If I replace `show={true}` with `show={false}` and save, it sometimes hides, sometimes not.
So I dug deeper. [show](https://github.com/nandorojo/moti/blob/master/packages/skeleton/src/skeleton.tsx#L151) does update correctly which means `<MotiView>` is removed. In fact, deleting it and saving the file makes no difference... the skeleton is still there. So I figured something else lingers, and indeed removing `<AnimatePresence>` manually hides the skeleton.
@nandorojo, could you please advise?

**Comment by nandorojo** [comment]
what `moti` version

**Comment by nandorojo** [comment]
there is no such `hide` prop so idk what you mean. it’s only `show`

**Comment by kickbk** [comment]
Ahhh I meant `show`. Also linked to it

**Comment by nandorojo** [comment]
can you reproduce on snack? 

also 

> what `moti` version

**Comment by kickbk** [comment]
Moti v.0.16.1, same as the skeleton. Probably cannot reproduce with snack. It's a monorepo that uses a custom dev client.

**Comment by nandorojo** [comment]
What if you add a resolution in the root of your monorepo that points to `framer-motion` 5, and upgrade moti?

**Comment by nandorojo** [comment]
Are you still facing this issue? I'm not entirely sure what I can actionably to do help here. Weird that I've had no such issue and I use the moti skeleton a lot.

**Comment by nandorojo** [comment]
can you set a yarn resolution to framer motion 6 and see if that helps? going to close for now since I’m not sure what else to do
