### ISSUE TITLE
Animate backgroundColor not work

### ISSUE THREAD

**Issue by lklima** [nandorojo/moti#176]
I'm trying to animate the background but it doesn't work.
`useDynamicAnimation` and `useAnimationState` doesn't work either.

`expo: 44.0.0`
`moti: 0.17.1`
`react-native-reanimated: 2.3.1`

```javascript
<MotiView
   from={{ backgroundColor: "red", scale: 0 }}
   animate={{ backgroundColor: "gray", scale: 1 }}
   transition={{ type: "timing", duration: 2000 }}
/>
```

**Comment by nandorojo** [comment]
this is a duplicate. it’s a reanimated issue, not a moti issue. i believe they fixed it in 2.4

**Comment by lklima** [comment]
@nandorojo using `useAnimatedState` works, so i think it's not a reanimated issue.

**Comment by nandorojo** [comment]
It still may be a reanimated issue. It's possible you have to wrap your component with `useMemo`. `useAnimationState` is memoized for you, so this isn't a problem.
