### ISSUE TITLE
MotiView's "from" and "animate" not working on Expo Go

### ISSUE THREAD

**Issue by ddanielsantos** [nandorojo/moti#181]
I've created [this repo](https://github.com/ddanielsantos/moti-expo-go-issue),  when previewing on the Web all work as expected, but when using Expo Go, the properties 'from' and 'animate' doesn't seem to work

**Comment by alexandreandriesse** [comment]
Same problem. But it do animate when I manually change the state on which depend the animation in the code, then save (and trigger hot reload)

**Comment by nandorojo** [comment]
Fast Refresh is a separate reanimated bug that isn’t related here. I already opened an reanimated issue for that.
