### ISSUE TITLE
Testing with jest

### ISSUE THREAD

**Issue by vjmanlapaz-nuskin** [nandorojo/moti#182]
I'm writing some test for my component using jest, and i came across an issue that says `Jest encountered an unexpected token` and it's pointing to my `moti` import.

Im not sure how to fix this. please help.

<img width="809" alt="Screen Shot 2022-03-10 at 10 58 44 PM" src="https://user-images.githubusercontent.com/87377212/157689207-8d678fa9-e40f-4ebf-8218-31be0bdfd5f3.png">

**Comment by nandorojo** [comment]
I’ve never used Jest so I’m not sure, but did your search the other issues? I think this came up before. You might need to transpile Moti.

**Comment by vjmanlapaz-nuskin** [comment]
i did find the previous issue related to this and tried it out but did not work, i still get the same error.

https://github.com/nandorojo/moti/issues/156

**Comment by nandorojo** [comment]
the error message says you need to add libs to transform. did you try that?

**Comment by rvieceli** [comment]
I think you aren't testing the animation, then you need to mock it creating `__mocks__/moti.ts` with 

```
import { View as MotiView } from 'react-native';
export { MotiView };
```

If you are using other components or hooks, you need to mock them as well.

**Comment by kvntzn** [comment]
late to the party but here's how  I did it. 

```
jest.mock('moti', () => {
    MotiView: () => 'MotiView';
});
```
