### ISSUE TITLE
Sequences still don't work

### ISSUE THREAD

**Issue by damian-balas** [nandorojo/moti#183]
Same as: https://github.com/nandorojo/moti/issues/140
Is this still a bug in `react-native-reanimated`?

I don't think this solved it: https://github.com/software-mansion/react-native-reanimated/pull/2851
Could you give the v2.5.0 a try?

```
    "react-native-reanimated": "2.5.0",
    "moti": "0.17.1",
    "react-native": "0.67.3",
```

**Comment by nandorojo** [comment]
can you make a reproduction using the starter template? if you want to use the newer reanimated version, simply use `expo run:ios` to create a custom dev client.

```sh
npx create-react-native-app -t with-moti
```

**Comment by msantang78** [comment]
@nandorojo 
FYI: I'm still getting having the same issue, even with the latest version of reanimated (2.8.0)
Since reanimated 2.3.0 I can't use sequences anymore https://github.com/nandorojo/moti/issues/131
I'm not using expo by the way

Let me know if I can help with the reproduction of the issue

**Comment by nandorojo** [comment]
hm, do they work with reanimated?

**Comment by msantang78** [comment]
It seems to be working fine with the expo v44 and the latest version of moti.

We are using react-native v0.66.3 and a bare workflow with some expo dependencies

I will try to create a small repro project
