### ISSUE TITLE
Adding Moti to an existing app doesn't work

### ISSUE THREAD

**Issue by heroic** [nandorojo/moti#186]
I tried setting up Moti on snack and it works, but adding it to our existing app dies with the error: `TypeError: Cannot read property 'useContext' of null`. 

Not sure if I'm missing something in the setup

**Comment by nandorojo** [comment]
doesn’t look like a moti issue. also i don’t have enough info to help here

**Comment by heroic** [comment]
@nandorojo I made a test app to repro the issue: [here](https://github.com/heroic/test-moti)

Reanimated is included as the first import too since we do use inline requires in our main app.

**Comment by nandorojo** [comment]
does Animated.View work?

**Comment by heroic** [comment]
Yes. We're using it in multiple animations

**Comment by heroic** [comment]
Added a branch that is using reanimated to rotate the view: https://github.com/heroic/test-moti/tree/feature/reanimated

**Comment by heroic** [comment]
Narrowed down the problem to reanimated 2.5.0. The sample app works if downgraded to 2.3.1

**Comment by nandorojo** [comment]
to clarify, Animated.View works, but swapping in MotiView breaks it?

**Comment by heroic** [comment]
yes. using reanimated 2.3.1 makes MotiView work too. something with 2.5.0 breaks MotiView

**Comment by nandorojo** [comment]
good to know, thanks for finding that. @hirbod did it work for you on 2.5? re #185

**Comment by hirbod** [comment]
@nandorojo I am on 2.5.0 and I don't have any issues with MotiView. I have direct imports and usage with `styled` - working fine (both iOS and Android)

**Comment by nandorojo** [comment]
@heroic what if you import reanimated at the top before importing moti?

**Comment by hirbod** [comment]
My App.tsx imports are like that:

```
import 'react-native-gesture-handler';
import 'react-native-reanimated';
....
...
```

**Comment by nandorojo** [comment]
Yeah we might have to make this part of the installation guide for iOS/Android.

**Comment by hirbod** [comment]
But his index.js import looks fine so far:
https://github.com/heroic/test-moti/blob/main/index.js

I did not test his repro though.

**Comment by nandorojo** [comment]
true, i wonder if the import should come in the TSX file though

**Comment by nandorojo** [comment]
@heroic maybe add the gesture handler root view? i’m not totally sure yet what could be off

**Comment by hirbod** [comment]
I remember that I had issues with the old monorepo example where reanimated was imported inside the index.js but worked correctly when swapped over to App.tsx

```
import { GestureHandlerRootView } from 'react-native-gesture-handler';
```

**Comment by hirbod** [comment]
Some other things to consider:

1) He is using RN 0.66.3 - we're expo / dev client users, so running 0.64.3

But since I am on custom dev client I upgraded to REA 2.5.0 and RNGH 2.1.1
So I can't tell for sure if a newer RN version breaks something.

**Comment by heroic** [comment]
@hirbod, as i mentioned when I switch to 2.3.1 with RN 0.66.3 moti works. so it's probably 2.5.0 with 0.66.3 thats the cause?

@nandorojo I do have `RNGestureHandlerEnabledRootView` in the mainactivity. Do you want me to add the JS side view too?

**Comment by hirbod** [comment]
@heroic give it a try please. It has to be included on the js side, see my example. If thats not working out, the combinatin 0.66.3 with 2.5.0 might be the real reason. I had a testproject with 0.67* though, which was working.

**Comment by heroic** [comment]
@hirbod no change. Tried it here: https://github.com/heroic/test-moti/tree/feature/rngesture

**Comment by hirbod** [comment]
Whats the exact error message? Could you provide a screenshot please?

**Comment by heroic** [comment]
@hirbod attached

![Screenshot_1648932960](https://user-images.githubusercontent.com/523335/161400959-0bd1a144-9311-426c-a31d-c5a6d1d1f9a4.png)

**Comment by heroic** [comment]
```
 ERROR  Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem. 
    at Moti (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=in.galaxycard.android.debug&modulesOnly=false&runModule=true:146070:27)
    at RNGestureHandlerRootView
    at GestureHandlerRootView
    at PayInEmiButton (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=in.galaxycard.android.debug&modulesOnly=false&runModule=true:133802:21)
    at RCTView
    at View
    at RCTView
    at View
    at AppContainer (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=in.galaxycard.android.debug&modulesOnly=false&runModule=true:77816:36)
    at GalaxyCard(RootComponent) (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=in.galaxycard.android.debug&modulesOnly=false&runModule=true:84211:28)
 ERROR  Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem. 
    at Moti (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=in.galaxycard.android.debug&modulesOnly=false&runModule=true:146070:27)
    at RNGestureHandlerRootView
    at GestureHandlerRootView
    at PayInEmiButton (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=in.galaxycard.android.debug&modulesOnly=false&runModule=true:133802:21)
    at RCTView
    at View
    at RCTView
    at View
    at AppContainer (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=in.galaxycard.android.debug&modulesOnly=false&runModule=true:77816:36)
    at GalaxyCard(RootComponent) (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=in.galaxycard.android.debug&modulesOnly=false&runModule=true:84211:28)
 ERROR  TypeError: Cannot read property 'useContext' of null

This error is located at:
    in Moti (at PayInEmi.tsx:39)
    in RNGestureHandlerRootView (at GestureHandlerRootView.android.tsx:17)
    in GestureHandlerRootView (at PayInEmi.tsx:38)
    in PayInEmiButton (at renderApplication.js:50)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:92)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:43)
    in GalaxyCard(RootComponent) (at renderApplication.js:60), js engine: hermes
 ERROR  TypeError: Cannot read property 'useContext' of null

This error is located at:
    in Moti (at PayInEmi.tsx:39)
    in RNGestureHandlerRootView (at GestureHandlerRootView.android.tsx:17)
    in GestureHandlerRootView (at PayInEmi.tsx:38)
    in PayInEmiButton (at renderApplication.js:50)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:92)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:43)
    in GalaxyCard(RootComponent) (at renderApplication.js:60), js engine: hermes
```

**Comment by nandorojo** [comment]
ok i think the issue is you have multiple react versions or something. please make an empty repro without all the delendencies

**Comment by heroic** [comment]
@nandorojo  That would be almost impossible as the moment I change reanimated to 2.3.1 the same code shared above works, unless reanimated is bringing another react somehow with 2.5.0 and rn 0.66.3

**Comment by hirbod** [comment]
@heroic try to delete package-lock and delete your node_modules folder and call "yarn" and try again please.

**Comment by heroic** [comment]
@hirbod trying to see if removing all packages from package.json makes a diff first. Will try your suggestion right after.

**Comment by nandorojo** [comment]
in general for a minimal reproduction, you should make an empty project only with the libraries in question to remove other things that could impact it

**Comment by hirbod** [comment]
Yeah. I couldn't even run your repro because of

```
react-native-linear-gradient
react-native-settings
react-native-signature-capture
```

**Comment by heroic** [comment]
@hirbod i think this is ios you're testing on. I haven't tested ios. This is android, I'm getting the issue on.

@nandorojo point taken. stripping away the code

**Comment by hirbod** [comment]
Yes, I am an Apple guy :P

**Comment by hirbod** [comment]
@nandorojo you should add issue templates :D

**Comment by heroic** [comment]
@hirbod we don't have an apple version of the app yet, so I'm not even sure if the repro will even build. It's a stripper version of our main app

**Comment by heroic** [comment]
@nandorojo @hirbod here's the stripped version https://github.com/heroic/test-moti/tree/feature/stripped

**Comment by heroic** [comment]
I also rm -rf node_modules and package-lock.json

**Comment by hirbod** [comment]
Not stripped enough....

```
Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  /Users/hirbod/Github/issues/test-moti/android/app/src/nullnull/debug/google-services.json
  /Users/hirbod/Github/issues/test-moti/android/app/src/debug/nullnull/google-services.json
  /Users/hirbod/Github/issues/test-moti/android/app/src/nullnull/google-services.json
  /Users/hirbod/Github/issues/test-moti/android/app/src/debug/google-services.json
  /Users/hirbod/Github/issues/test-moti/android/app/src/nullnullDebug/google-services.json
  /Users/hirbod/Github/issues/test-moti/android/app/google-services.json
```

**Comment by heroic** [comment]
@hirbod the branch is building for me. Let me see where it's doing this for you.

**Comment by hirbod** [comment]
Well its building for you because your google-services file is present ;)

**Comment by heroic** [comment]
@hirbod I did delete the file from the code. It's not here. probably a cache or something. Try now please. I've removed everything GMS

**Comment by heroic** [comment]
Also, thank you so much for spending your weekend on this! I'm sorry for taking up your weekend!!!

**Comment by hirbod** [comment]
@heroic always include the RN template keystore inside android/app
https://raw.githubusercontent.com/facebook/react-native/master/template/android/app/debug.keystore

**Comment by hirbod** [comment]
Your project is building for me without any issues. Working absolutely fine.

**Comment by heroic** [comment]
I'm gonna try another system tmr. Still throws an error on mine.

**Comment by hirbod** [comment]
```
 watchman watch-del-all && rm -rf $TMPDIR/react-* &&
 rm -rf node_modules/ && npm cache clean && yarn
npx react-native run-android
```

Issue can be closed, working as expected.
