### ISSUE TITLE
App crashes when turning on debugging (turbomoduleregistry.getenforcing(...) 'native reanimated' could not be found)

### ISSUE THREAD

**Issue by walterholohan** [nandorojo/moti#20]
## Description

After installing `moti 0.4.1` and `react-reanimated 2.0.0-rc.3` the app crashes when I turn on debugging via the dev menu. The below error message is displayed:

```
turbomoduleregistry.getenforcing(...) 'native reanimated' could not be found
```

### Screenshots

![image](https://user-images.githubusercontent.com/5293650/108589441-30eaad80-7356-11eb-98f4-9354380ab2c2.png)

## Package versions

- React: `16.13.1`
- React Native: `0.63.4`
- React Native Reanimated: `2.0.0-rc.3`
- NodeJS: `15.1.0`

**Comment by nandorojo** [comment]
This is a reanimated bug, not moti. It works with RC 2.
