### ISSUE TITLE
Expo SDK 46 - Tried to synchronously call anonymous function from a different thread

### ISSUE THREAD

**Issue by abanobboles** [nandorojo/moti#218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![Simulator Screen Shot - iPhone 13 Pro - 2022-08-03 at 13 26 22](https://user-images.githubusercontent.com/9078953/182596811-fab1dfb8-f62a-4c03-a5d0-40ba06f01f83.png)

Same Code working with SDK 45 and "react-native-reanimated": "~2.8.0" 
but with SDK 46 the error "Tried to synchronously call anonymous function
from a different thread." show up

### Versions

```markdown
- Moti: ^0.18.0
- Reanimated:~2.9.1
- React Native:0.69.3
```

### Reproduction

expo start --dev-client

**Comment by nandorojo** [comment]
this looks like a reanimated issue, not a moti one
