### ISSUE TITLE
Uncaught TypeError: createAnimatedComponent is not a function

### ISSUE THREAD

**Issue by makhataibar** [nandorojo/moti#222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="510" alt="Screen Shot 2022-08-22 at 17 27 53" src="https://user-images.githubusercontent.com/27006656/185910665-8f2ea516-8190-493a-9f66-5c7d1e61c82c.png">

### Expected Behavior

Stable work on all platform: web, ios, android

### Steps To Reproduce

<img width="761" alt="Screen Shot 2022-08-22 at 17 32 47" src="https://user-images.githubusercontent.com/27006656/185911456-7e8a7c46-33d2-4faa-85b8-6540521a1a6b.png">

### Versions

```markdown
- Moti: 0.19.0-alpha.6
- Reanimated: ~2.9.1
- React Native: 0.69.4
```

### Reproduction

https://snack.expo.dev/@makhataibar/eaa888?platform=web

**Comment by nandorojo** [comment]
I don't see that error on the Snack. Here is a working Snack: https://snack.expo.dev/@beatgig/eaa888?platform=web

SDK 46 Expo Snack doesn't work with Reanimated, but SDK 45 does. Is it possible you don't have the reanimated babel plugin in your `babel.config.js`?

**Comment by nandorojo** [comment]
If you just upgraded, you'll have to clear your Babel cache / node modules with `expo start --clear`

**Comment by crutch12** [comment]
Same error after upgrade to expo **SDK 47** (released 5 days ago)

`expo start --clear` doesn't help. (`expo@47.0.1`)

😭

**Comment by nandorojo** [comment]
can you try things like `yarn why react-native-reanimated` and make sure there’s only one

**Comment by crutch12** [comment]
@nandorojo

> can you try things like yarn why react-native-reanimated and make sure there’s only one

Yeah, I tried `npm ls react-native-reanimated`, there are no duplicates. (`react-native-reanimated@2.12.0`)

**Comment by rafakwolf** [comment]
@crutch12 Did you solve the issue? I'm facing the same here

**Comment by nandorojo** [comment]
are you using npm? try `npm i —legacy-peer-deps`

**Comment by crutch12** [comment]
Expo uses `--legacy-peer-deps` by default

**Comment by rafakwolf** [comment]
> are you using npm? try `npm i --legacy-peer-deps`

Hey Fernando, thank you for the response, sorry, by installing using `--legacy-peer-deps` will solve the error `Uncaught TypeError: createAnimatedComponent is not a function`?
Sorry, I'm not following you

**Comment by nandorojo** [comment]
Did you try it? It’s possible multiple versions are getting installed of Reanimated due to peer dependencies.

**Comment by nandorojo** [comment]
> Expo uses `--legacy-peer-deps` by default

Do you mean with `expo install`?

**Comment by nandorojo** [comment]
If someone can reproduce this I can take a look. It shouldn’t be on Expo Snack though. Expo has a broken integration with Reanimated, which means Moti isn’t working properly on Snack.

**Comment by rafakwolf** [comment]
Just to add one more piece of information, I tried using yarn, same error.

**Comment by rafakwolf** [comment]
![image](https://user-images.githubusercontent.com/2060578/213954154-722d526b-4f64-41ca-838d-2fd55475f097.png)

**Comment by rafakwolf** [comment]
@nandorojo @crutch12  I think I managed to make it work 
https://github.com/rafakwolf/expo-moti-web

**Comment by crutch12** [comment]
@rafakwolf 

I've tested same configs with my project - and it works now!

Here is the dramatic difference:

```js
// babel.config.js
plugins: [
  [
    'module-resolver',
    {
      extensions: ['.js', '.ts', '.tsx'],
      alias: {
        'react': './node_modules/react',
        'react-native': './node_modules/react-native-web',
      },
    },
  ],
  '@babel/plugin-proposal-export-namespace-from',
  // ...
],
```

My previous babel.config.js:

```js
// babel.config.js
module.exports = function (api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: [
      'react-native-reanimated/plugin',
    ],
  };
};
```

Here is my webpack.config.js (I didn't change it, it works fine with new babel.config.js):
```js
// webpack.config.js
const createExpoWebpackConfigAsync = require('@expo/webpack-config');

module.exports = async function (env, argv) {
  const config = await createExpoWebpackConfigAsync(
    {
      ...env,
      babel: {
        dangerouslyAddModulePathsToTranspile: ['moti', '@motify'],
      },
    },
    argv
  );

  config.resolve.alias['framer-motion'] = 'framer-motion/dist/framer-motion';

  return config;
}
```

So I think that adding `react-native-reanimated` in **dangerouslyAddModulePathsToTranspile** section is unnecessary

**Comment by rafakwolf** [comment]
@crutch12 thank you for the details
