### ISSUE TITLE
Web animations break when StrictMode is enabled

### ISSUE THREAD

**Issue by jaivinwylde** [nandorojo/moti#224]
Reanimated for web uses findDOMNode in AnimatedComponent which is depreciated in StrictMode. This causes the Moti animation to fail during its initial animate transition.

I looked at Reanimated's issues and it doesn't seem like anyone has mentioned the use of findDOMNode being an issue with their web implementation. Does anyone know if this is actually something they're aware of and fixing or should I bring up this issue there as well?

And the reason I'm asking here is that I'm just wondering if anyone else using Moti has experienced this and if they've found a good workaround.

**Comment by nandorojo** [comment]
Can you give more details about when this breaks?

**Comment by nandorojo** [comment]
> Reanimated for web uses findDOMNode in AnimatedComponent

Are you referring to `findNodeHandle`? Because I don't see `findDOMNode` [anywhere in the reanimated codebase.](https://github.com/software-mansion/react-native-reanimated/search?q=finddomnode)

Presumably `findNodeHandle` uses `findDOMNode` under the hood...

**Comment by nandorojo** [comment]
It would help if you shared all the versions you're using, since I haven't faced this issue yet myself.

**Comment by jaivinwylde** [comment]
My bad, I'll provide versions and work on a minimal reproduction tomorrow

**Comment by nandorojo** [comment]
thanks! appreciate it

**Comment by jaivinwylde** [comment]
To answer your previous question the animations break because of a runtime error. There is also a depreciation warning for the use of setNativeProps.

![image](https://user-images.githubusercontent.com/46613979/187502601-695284ce-3f41-4328-a979-89ab6c570c43.png)
![image](https://user-images.githubusercontent.com/46613979/187502761-9c8fe2d6-5b4d-41bd-bed7-8135bd7e4c54.png)

moti=0.18.0
reanimated=2.10.0 (also happens with 2.9.1)
react-native-web=0.18.7
next=12

I'm also going to try and recreate the problem in a minimal repo

**Comment by jaivinwylde** [comment]
I just created a base Solito example project and the same thing happens.

All I did was this:
`npx create-solito-app@latest strictmode`
`cd strictmode && yarn web`

And got this StrictMode warning again:
![image](https://user-images.githubusercontent.com/46613979/187509210-48ec651c-08a7-4825-adbe-f6674d1df465.png)

The difference is that this animation did not break and I think that's because in my use case I was using AnimatePresence and had the MotiView be conditionally rendered from a toggle state. When the toggle state changed, the MotiView was created and the error happened so it didn't do its initial animation, but it did do its exit animation.

**Comment by jaivinwylde** [comment]
[RNW pr](https://github.com/necolas/react-native-web/pull/2330)
Seems like this is a known issue with react-native-web and a fix hasn't been merged yet

**Comment by nandorojo** [comment]
This is fixed on reanimated 3.3 fyi

**Comment by dammafra** [comment]
Hello, I didn't understand if I can  put `reactStrictMode` to true now.
My version of reanimated is 3.3, but I have still the `findDOMNode is deprecated in StrictMode error`.

**Comment by nandorojo** [comment]
I think you’d need a newer version of it. But I’m not up to date with it. Strict mode causes a lot of issues for me and I always disable it

**Comment by dammafra** [comment]
Ok, never mind 😃 

I needed it because in `next-international` docs (here https://next-international.vercel.app/docs#typescript-config) it's stated that works better with strict mode, but having it disabled don't cause issues.

I managed to have a shared setup of localization by using `react-i18next` on expo and `next-international` on next (`next-i18next` gave me a lot of troubles).

Have you ever faced this need?

Btw, thank you for your work and for your time 🙏
