### ISSUE TITLE
Accordion (New!) section in the doc is blank

### ISSUE THREAD

**Issue by galacoder** [nandorojo/moti#235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi @nandorojo. I found this accordion page in the doc is blank and doesn't show any example or text. Please update as I would love to try it out in my app. Tks :)

### Versions

```markdown
- Moti:
- Reanimated:
- React Native:
```

### Reproduction

https://moti.fyi/examples/auto-height

**Comment by galacoder** [comment]
Somehow, I refreshed a few times and then it worked.

**Comment by nandorojo** [comment]
Might be that expo snack is just slow...
