### ISSUE TITLE
Animation issue (some delay appears)

### ISSUE THREAD

**Issue by b0n1q** [nandorojo/moti#238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Some animations have bigger delay than expected

### Expected Behavior

No animation delay

### Steps To Reproduce

```
import { View as AnimationView } from 'moti'

const showBlock = () => {
    const [isExpanded, setIsExpanded] = useState(false)

<Pressable
				onPress={() => {
					setIsExpanded(!isExpanded)
				}}
			>
				<Box>
					<Text>External Block</Text>
				</Box>
				{isExpanded && (
					<AnimationView
						from={{ opacity: 0 }}
						animate={{ opacity: 1 }}
						transition={{ type: 'timing', duration: 180 }}
					>
						<Box>
							<Text>Internal Block</Text>
						</Box>
					</AnimationView>
				)}
			</Pressable>
}
```

### Versions

```markdown
- Moti: 0.20
- Reanimated: 2.9.1
- React Native: 0.69.6
```

### Screenshots

https://user-images.githubusercontent.com/26281760/197521394-7878f201-c3e3-407b-941f-494e5482087e.mov

### Reproduction

Reproducible very often

**Comment by nandorojo** [comment]
I’ve never seen this before. Curious if there’s something else wrong with your setup.

**Comment by b0n1q** [comment]
Hm, I honestly don't have any ideas what can be wrong
I see that reanimated has some bug https://github.com/software-mansion/react-native-reanimated/issues/3296, but as I understand very few people have it and no any fix for that even that are mentioned there

it would be nice to hear someone's ideas

**Comment by b0n1q** [comment]
I could be wrong, but it might appeared after upgrading from expo 44 to expo 46 (also reanimated was updated because of it from 2.3.1 to 2.9.1)

**Comment by nandorojo** [comment]
hmm that could indicate it’s due to reanimated versions. always kinda hard for me to say

**Comment by pochampagne** [comment]
I'm having a similar issue. I created a simple component to reproduce. As seen on the video, sometime when I toggle my state to switch the visible component, the animation isn't trigger, so the AnimatesView component remain in the "from" state, so with an opacity of 0. 

```
const AnimatedView = ({ children }) => (
  <MotiView
    from={{
      opacity: 0,
      translateY: 20,
    }}
    animate={{
      opacity: 1,
      translateY: 0,
    }}
    exit={{
      opacity: 0,
      translateY: 20,
    }}
    transition={{
      type: 'timing',
      duration: 200,
    }}
  >
    {children}
  </MotiView>
)

export default () => {
  const [isOn, setIsOn] = React.useState<boolean>(true)

  const toggle = () => setIsOn((on) => !on)

  return (
    <View>
      <Pressable onPress={toggle}>
        <Text>Click me to toggle</Text>
      </Pressable>
      <AnimatePresence exitBeforeEnter>
        {isOn && (
          <>
            <Text pb={4}>Toggle on outside MotiView</Text>
            <AnimatedView key="on">
              <Text>Toggle is on baby</Text>
            </AnimatedView>
          </>
        )}
        {!isOn && (
          <>
            <Text pb={4}>Toggle off outside MotiView</Text>
            <AnimatedView key="off">
              <Text>Toggle is off sadly</Text>
            </AnimatedView>
          </>
        )}
      </AnimatePresence>
    </View>
  )
}
```


- moti 0.20.0
- reanimated 2.9.1
- react-native 0.69.6
- expo 46

https://user-images.githubusercontent.com/84029335/202496942-cf1f05ba-9a97-498a-9dc7-169916029ab0.MP4

**Comment by nandorojo** [comment]
Your example using `AnimatePresence` is missing a `key` prop for children, so it's expected not to work properly @pochampagne

**Comment by nandorojo** [comment]
Is this still happening? I can't reproduce it, so I'm assuming there could be some other issue, such as using Flashlist with Reanimated, or perhaps improper list keys. Going to close for now, but if you can give a reproduction repository I'll take a look.
