### ISSUE TITLE
Add transformOrigin support

### ISSUE THREAD

**Issue by nandorojo** [nandorojo/moti#24]
Could use `transformOrigin` from redash, thanks to @wcandillon.

```jsx
<View 
  animate={{ scale: 3 }}
  transformOrigin={{ x: 0, y: 100 }}
/>
```

**Comment by nandorojo** [comment]
going to leave this for now

**Comment by nandorojo** [comment]
https://twitter.com/browniefed/status/1373706158574243842?s=20

**Comment by Stevemoretz** [comment]
There is a library which does this actually I saw it there and converted it to worklet for myself as well, the trick is to use translation once before and once after the main transform you do.

But that doesn't work here does it?
We can pass multiple stuff to transform but here we can't anymore because of making the api simpler, so I suppose either there should be a feature for that or this can't happen.

**Comment by Stevemoretz** [comment]
> https://twitter.com/browniefed/status/1373706158574243842?s=20

That's exactly what I've done and that's the same library. But we can't do it here, because we can't pass an array of transforms.

**Comment by nandorojo** [comment]
It's certainly interesting...maybe the redash function could work?

I haven't found myself needing this yet on beatgig.com, which is why I haven't spent time on it 😬

**Comment by Stevemoretz** [comment]
Redash doesn't have this function as far as I'm aware of.
I can provide the function and worklets if you are interested in making it into core, but can be done outside of core if we could have :
`Transform :{{translateY : 500,...,translateY : - 500}} `
Basic geometry nothing complex, but not possible with your artichecture, and not possible with those functions either.

**Comment by nandorojo** [comment]
I think this PR could fix it: 

https://github.com/nandorojo/moti/pull/54

It allows you to pass a derived value as the `animate` prop, meaning you could use worklets inside of it.

**Comment by Stevemoretz** [comment]
That PR is sure interesting and useful in other cases, I got it installed but still not possible.

```js
    const isPressed = useSharedValue(false);
    const animate = useDerivedValue(() => ({
        opacity: isPressed.value ? 0.5 : 1,
        transform: [
            {
                translateY: 20,
            },
        ],
    }));
```

Since this doesn't work on translateY still this can not happen.

**Comment by Stevemoretz** [comment]
I tried to fix this with a PR but I guess that's not a good idea, you should decide yourself how you want to implement this, this is a limitation in architecture.But I suggest this for an example.

we should have a transform key as well, for when not using simple apis, it could be like this :

```ts
type transform = {
   ...all transform properties
}[]
|
[
       {
            ...all transform properties
       }[]
]
|
[
    {
       value :  {
            ...all transform properties
       }[],
      ...other stuff about transition
    }
]
```

The second case and the third case is for the sequences.
I bet this is really easy for you to implement, but first of all I was messing your code and also I wan't sure if you would like this at all, so I decided to just suggest this to you.
It's a little bigger than a simple PR and I didn't want to mess up your code with inconsistencies.

**Comment by Stevemoretz** [comment]
> It's certainly interesting...maybe the redash function could work?
> 
> I haven't found myself needing this yet on [beatgig.com](https://beatgig.com), which is why I haven't spent time on it 😬

On an unrelated note, I've checked your website and it looks amazing.
I Really never considered react native, for building a website. It doesn't even allow for normal css.
Could not be used with reactjs in combination the last time I went for it, is it possible now?

Don't get me wrong, your website looks great but why would you use react native for web development?

----

Also about what you said, using multiple transforms happen on complex animations and not in every project, you may not need that on this project at all, but it my basic framework that I've written for my company we use it for a couple of stuff, such as text letter animations and ...

Well it just wouldn't hurt to have this amazing feature.
Having the transformOrigin object maybe is a little overkill but having simple transform array makes sense,
after having that we don't even need a worklet as your library supports states it just simply works with that other library that was mentioned in the twitter.


Sorry for the wall of text lol.

**Comment by Stevemoretz** [comment]
Here's another reason why transform needs a good refactor :
https://github.com/nandorojo/moti/issues/65

**Comment by nandorojo** [comment]
Your derived value code sample would work if you just used translateY directly.

I don't think you need pure CSS besides responsive design. In that case, I maintain another library called Dripsy for styles.

Using React Native for Web has many benefits. For starters, it lets you use the same code on native. That's a huge boost. Also, it handles a lot of the problems with web nicely. Finally, it lets you use nice RN primitives like Text and View, with props like onLayout, etc.

Moti also supports Web.

**Comment by Stevemoretz** [comment]
> Your derived value code sample would work if you just used translateY directly.
> 
> I don't think you need pure CSS besides responsive design. In that case, I maintain another library called Dripsy for styles.
> 
> Using React Native for Web has many benefits. For starters, it lets you use the same code on native. That's a huge boost. Also, it handles a lot of the problems with web nicely. Finally, it lets you use nice RN primitives like Text and View, with props like onLayout, etc.
> 
> Moti also supports Web.

That's the point you can't use translateY directly you need to have two translateYs and two translateXs and in the middle your other transforms.

You need multiple transforms and some of them are with the same key this is not possible to be handled right now.


Thanks for the explanation about react native web
