### ISSUE TITLE
moti doesn't work with Expo Web

### ISSUE THREAD

**Issue by b0n1q** [nandorojo/moti#243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I've got bunch of errors in console related to framer-motion while launching Expo Web

I see that moti has framer-motion in dependencies, so I suspect that problem is here

### Expected Behavior

No errors in console. Project should be launched in Web

### Versions

```markdown
- Moti: ^0.21.0
- Reanimated: ~2.12.0
- React Native: 0.70.5"
```

### Screenshots

<img width="544" alt="image" src="https://user-images.githubusercontent.com/26281760/203546848-65841505-f5fc-49b8-9d4d-5619e4248e6e.png">

<img width="718" alt="image" src="https://user-images.githubusercontent.com/26281760/203549985-46063962-cd41-4df8-8457-edd3ff16d9e6.png">

### Reproduction

no link

**Comment by onk-mickael** [comment]
Add this Babel plugin to your config for expo to work on web: `@babel/plugin-proposal-export-namespace-from](https://babeljs.io/docs/en/babel-plugin-proposal-export-namespace-from#installation` 
As explain in Expo docs [https://docs.expo.dev/versions/latest/sdk/reanimated/#web-support](https://docs.expo.dev/versions/latest/sdk/reanimated/#web-support)


```
module.exports = function (api) {
  api.cache(true);
  return {
    presets: ["babel-preset-expo"],
    plugins: [
      "@babel/plugin-proposal-export-namespace-from",
      "react-native-reanimated/plugin",
    ],
  };
};

```
