### ISSUE TITLE
Action Menu Demo broke

### ISSUE THREAD

**Issue by mrzmyr** [nandorojo/moti#247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://moti.fyi/examples/action-menu

![CleanShot 2022-12-03 at 20 26 57](https://user-images.githubusercontent.com/746429/205458406-561cb74a-7193-46f8-9f24-3b0d3bf1a7af.png)

![CleanShot 2022-12-03 at 20 26 51](https://user-images.githubusercontent.com/746429/205458409-cd356873-b8a3-4fff-a14d-0f17c5b27e29.png)

### Versions

```markdown
https://moti.fyi/examples/action-menu
```

### Reproduction

https://moti.fyi/examples/action-menu

**Comment by nandorojo** [comment]
Yeah Expo snack is broken for Moti. I'm not sure why.
