### ISSUE TITLE
(Workaround) Next.js without SWC plugin

### ISSUE THREAD

**Issue by nandorojo** [nandorojo/moti#252]
Making an issue here for visibility.
 

## Workaround

- `yarn add moti@swc` (This installs `0.21.1-alpha.6` at the time of writing)

- Add this at the top of `pages/_app.tsx`:

```tsx
import { enableSwcHack } from 'moti'
enableSwcHack()
```

- Remove the Reanimated SWC plugin from `next.config.js` (until it's fixed).

## Overview

I created a reproduction here of Reanimated not working with SWC: https://github.com/nandorojo/reanimated-next13-issue

Here's the Next.js issue: https://github.com/vercel/next.js/issues/43886
And the Reanimated issue: https://github.com/software-mansion/react-native-reanimated/issues/3971

### Expected Behavior

Reanimated should work on Next.js. Due to its architecture, this requires an SWC plugin. However, the plugin is not working.

If you use Reanimated without a plugin, it doesn't break anything, but animations don't usually run. However, On the `swc-hack` branch, I figured out a way to get Reanimated working on Web _without_ a plugin.

The result will not affect native, only Web (when enabled). The solution adds re-renders to power animations. It shouldn't be noticeable.

### Versions

```markdown
Next.js 13, Reanimated 2.12.0, Moti `0.21.1-alpha.6`
```

### Screenshots

<img width="1643" alt="Screenshot 2023-01-18 at 2 42 34 PM" src="https://user-images.githubusercontent.com/13172299/213279607-e3b61934-2b06-422b-b44d-53ce7a711f6a.png">

### Reproduction

https://github.com/nandorojo/reanimated-next13-issue

**Comment by nandorojo** [comment]
Another update is live at `0.21.1-alpha.9`, which adds fixes for `MotiPressable`.

**Comment by nandorojo** [comment]
Hermes support was pulled in as well.

**Comment by chrisarts** [comment]
will this bring back the bundle size problem ?

**Comment by nandorojo** [comment]
It shouldn’t affect that. That all lies in how they tree shake Reanimated

**Comment by nandorojo** [comment]
I opened a PR to fix this at reanimated once and for all: https://github.com/software-mansion/react-native-reanimated/pull/3997
