### ISSUE TITLE
Skeleton flicker on mount

### ISSUE THREAD

**Issue by pontusab** [nandorojo/moti#26]
Love the library and also the new Skeleton component 🥇 

Using the Skeleton component gives me a initial flicker on mount, it's because of the `onLayout` and state change, I can see three different solutions for this:

1. Add opacity until we have the width calculated
2. Enforce fixed width with `px`
3. Get `measure ` from Reanimated to work as we want: https://github.com/software-mansion/react-native-reanimated/issues/1497

Let me know how we should tackle this and I can make a PR.

**Comment by nandorojo** [comment]
Interesting, could you send a video? I assume a fade-in should work fine, but I’m curious to see. I don't see a flicker visually on web, since the background behind the gradient matches the gradient.

**Comment by pontusab** [comment]
Im using RN:


https://user-images.githubusercontent.com/655158/109826764-68e9ce80-7c3b-11eb-9731-1f1d7a45f00e.mov

**Comment by nandorojo** [comment]
Ah, I see. Let’s make the animated gradient fade in then. It’ll start at 0 opacity, and if measured width is none, it’ll have opacity 0. Otherwise, opacity 1.

**Comment by pontusab** [comment]
Alright, will create a PR for that!

Thanks! Currently changing all animations to moti https://wrench.cc (both nextjs and RN)

**Comment by nandorojo** [comment]
Awesome, same here for https://beatgig.com

**Comment by nandorojo** [comment]
https://github.com/nandorojo/moti/blob/1b938622d61d514aa408ab03b70d3b0c8250ebfa/packages/skeleton/src/skeleton.tsx#L197

This is the line to remove. We can update the opacity in animate below.

**Comment by pontusab** [comment]
Closing with a PR: https://github.com/nandorojo/moti/pull/27

**Comment by nandorojo** [comment]
Published in `0.6.x`
