### ISSUE TITLE
Module '"moti/interactions"' has no exported member 'MotiPressable'.

### ISSUE THREAD

**Issue by DaLukasTI** [nandorojo/moti#262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

As stated above when installing the latest Moti version my IDE throws the stated error.
However it functions as it should only typescript is not happy with the exported types

### Expected Behavior

'"moti/interactions"' should have an exported member "MotiPressable"

### Steps To Reproduce

yarn add moti

import { MotiPressable, MotiPressableProps } from 'moti/interactions';

### Versions

```markdown
- Moti:^0.23.2
- Reanimated:~2.12.0
- React Native: 0.70.5
```

### Reproduction

/

**Comment by nandorojo** [comment]
i must have messed something up, does 0.22.x fix it?

**Comment by DaLukasTI** [comment]
Yes indeed, I downgraded to 0.22.x now and this is working fine.
If I look at the index.d.ts from moti/interactions it is only exporting the types of the newly added svg logic.

**Comment by nandorojo** [comment]
thanks for the heads up, will be an easy fix

**Comment by nandorojo** [comment]
Fixed in 0.23.3
