### ISSUE TITLE
MotiView with NativeWind throws redundant  errors when tansfroming

### ISSUE THREAD

**Issue by Ipicon** [nandorojo/moti#263]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using styled version of MotiView using NativeWind,
I'm using the dynamic hook `useDynamicAnimation`, and trying to move it when the page mounts from point A to point B.
The behavior is as expected but the in the console you can see a lot of errors like so:
`styleq: transform typeof [object Object] is not "string".`
I think maybe the way I'm passing props through the `styled` method have something to do with it, I've tried to play around with it and couldn't solve it.

### Expected Behavior

No errors in the console.

### Steps To Reproduce

1. Make a styled view with NativeWind using `export const AnimatedView = styled(MotiView)`(I've tried to pass the style props like you do in MotiLink and it didn't work too - the error went away but no styles were applied`
2.  declare a default dynamicStateAnimation by using either of the `transform` properties.
3. Animate it.
4. cHECK THE LOGS.

### Versions

```markdown
- Moti: 0.19.0-alpha.6
- Reanimated: 0.69.6
- React Native: 2.9.1
```

### Screenshots

![image](https://user-images.githubusercontent.com/43734511/218190677-4abe3ef5-f5ea-414c-8305-d7db7a5c91b6.png)
![image](https://user-images.githubusercontent.com/43734511/218190697-83596470-3d55-49ff-b0e7-f7198e4a95df.png)
![image](https://user-images.githubusercontent.com/43734511/218190746-11420c0d-9e19-4dc8-bbef-a811703e81c8.png)
![image](https://user-images.githubusercontent.com/43734511/218190783-004a3de5-afe5-4219-b44e-197033f8044f.png)

### Reproduction

.

**Comment by nandorojo** [comment]
you should probably separate the views, i’m not sure how nativewind works.

**Comment by saeedblanchette** [comment]
@Ipicon  did you find any workaround? for this, I'm having the same error!

**Comment by nandorojo** [comment]
> you should probably separate the views, i’m not sure how nativewind works.

**Comment by Ipicon** [comment]
> @Ipicon did you find any workaround? for this, I'm having the same error!

I did exactly what @nandorojo suggested, covered the whole styled View with regular one, shouldn't be so hard...

**Comment by nandorojo** [comment]
animated views usually don't work well when wrapped with design systems like nativewind and tamagui since they perform magic.

**Comment by saeedblanchette** [comment]
Sorry guys for replaying late, I'm having the same issue now but with MotiPressable when I wrap styled from tailwind. is there a workaround? for this too. 

![code](https://github.com/nandorojo/moti/assets/33104967/7f50f1de-7deb-4ead-b41e-13cda3b4b37d)

**Comment by nandorojo** [comment]
i highly recommend separating the views, as mentioned before

**Comment by nandorojo** [comment]
in your case, for those very minimal opacity styles, consider using react context and pass the dark variable to the animate function.

maybe nativewind has a hook to resolve string styles into objects for these cases if you’d prefer that

**Comment by saeedblanchette** [comment]
Thank you @nandorojo,  your advice worked for me (separating the views)
