### ISSUE TITLE
Exit Animation not showing in FlatList

### ISSUE THREAD

**Issue by n-ii-ma** [nandorojo/moti#269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to animate the mounting/unmounting of a list of items, the mounting animation (`from`) works as expected but the unmounting animation (`exit`) isn't.

### Expected Behavior

Unmount item with exiting animation.

### Steps To Reproduce

Just try to animate the rendering of a list of items with `FlatList` and notice the item's behavior upon deleting an item:

```
<MotiView 
  from={{ opacity: 0, translateX: -ms(25) }}
  animate={{ opacity: 1, translateX: 0 }}
  exit={{ opacity: 0, translateX: -ms(25) }}
  transition={{ type: 'spring' }}
>
```
.....
</MotiView>

### Versions

```markdown
- Moti: v0.23.7
- Reanimated: v2.14.4
- React Native: v0.71.3
```

### Reproduction

```
const data = [
  {
    id: 1,
    name: 'Jack'
  },
  {
    id: 2,
    name: 'John'
  },
  {
    id: 3,
    name: 'Joe'
  },
]  

// Render item
  const renderItem = ({ item }) => (
    <AnimatePresence>
      <Sample item={item} />
    </AnimatePresence>
  );

<FlatList
  data={data}
  extraData={data}
  renderItem={renderIncomingOrderCard}
  keyExtractor={item => item.id}
  horizontal={false}
/>
```

**Comment by nandorojo** [comment]
that kind of behavior isn’t possible, since the animate presence element is getting unmounted too. you could try reanimated layout animations if you’re on reanimated v3.

**Comment by nandorojo** [comment]
alternatively, you can do a normal list instead of a flatlist, have a single animate presence at the root, and give each direct child a unique key. that’ll work too.

**Comment by n-ii-ma** [comment]
I see.

Would love to see Moti integrating reanimated v3 soon.

**Comment by nandorojo** [comment]
moti should work with it out of the box

**Comment by lucaspereirasouzat** [comment]
> alternatively, you can do a normal list instead of a flatlist, have a single animate presence at the root, and give each direct child a unique key. that’ll work too.
with this code not working 
` <AnimatePresence>
          
          <FlatList
            ItemSeparatorComponent={() => (
              <View className="h-0.5 bg-slate-500" />
            )}
            className="flex-1 h-full"
            data={filterFolders}
            keyExtractor={item => item.id}
            renderItem={({ item }) => (
              <MotiView
                key={item.id}
                from={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.8 }}
                transition={{ type: "timing", duration: 300 }}
                className="w-full"
                // style={styles.item}
              >
                <FlatItem
                  workSpaceId={id}
                  duplicateRequest={duplicateRequest}
                  setOpenRequest={setOpenRequest}
                  setOpenFolder={setOpenFolder}
                  removeFolder={removeFolder}
                  removeRequest={removeRequest}
                  item={item}
                  pinRequest={pinRequest}
                />
              </MotiView>
            )}
          />
        </AnimatePresence>`
