### ISSUE TITLE
Examples on Stakblitz do not work

### ISSUE THREAD

**Issue by efstathiosntonas** [nandorojo/moti#272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

StackBlitz throws this:

![Screenshot 2023-03-03 at 08 41 19](https://user-images.githubusercontent.com/717975/222650072-62df3e1a-15da-4036-a4d0-c1f561b0754c.png)

### Versions

```markdown
non related

- Moti:
- Reanimated:
- React Native:
```

### Reproduction

https://moti.fyi/examples/action-menu

**Comment by efstathiosntonas** [comment]
After checking this: https://developer.stackblitz.com/platform/webcontainers/browser-support#firefox 

it seems that using Firefox (in my case Developer Edition) is not supported. Closing this as unrelated but I think it could be nice to update the documentation that you need Chrome to see the examples.

**Comment by efstathiosntonas** [comment]
The Exit Before Enter example loads README instead of `pages/index.tsx`

**Comment by nandorojo** [comment]
PRs welcome

**Comment by efstathiosntonas** [comment]
@nandorojo done

https://github.com/nandorojo/moti/pull/274
https://github.com/nandorojo/moti/pull/273
