### ISSUE TITLE
Module not found error. 

### ISSUE THREAD

**Issue by etiennelacoursiere** [nandorojo/moti#280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have an expo project on SDK 46 with Moti and everything is working great. Today i am trying to upgrade to expo SDK 48 and i'm encountering some error related to Moti and prevent the app from building. I only tried web for now by pressing `w` in the terminal so i didn't start a new dev-client built as web don't use it (i think? 🤔 ). I'm sure these errors are config errors but i can't find what i'm doing wrong. 

### Expected Behavior

The project build. 

### Versions

```markdown
- Moti: ^0.24.2
- Reanimated: ~3.0.2
- React Native: 0.71.6
```

### Screenshots

![image](https://user-images.githubusercontent.com/12648647/230493622-3162cd88-70f9-4a00-adfb-91606a901fef.png)

### Reproduction
https://github.com/etiennelacoursiere/moti-web-crash

**Comment by etiennelacoursiere** [comment]
I added a reproduction. 

I started with `npx create-react-native-app -t with-moti` then added `npx expo install @expo/webpack-config` and added a webpack config file like described in the docs. I tried with both `@motify` and without it in the `dangerouslyAddModulePathsToTranspile` as the doc says it's not needed for moti 0.19+.  

In this reproduction, when i tried to start the web app, i got the error in the screenshot below.

**Comment by etiennelacoursiere** [comment]
If anyone have the same problem, setting `@expo/webpack-config` to `0.17.4` instead of the latest `18.0.3` seems to fix the problem for now. Also from what I understand, webpack config will be deprecated in favor of using metro bundler soon.

**Comment by nandorojo** [comment]
hmm, can you try `yarn why moti` and `yarn why framer-motion`?

**Comment by nandorojo** [comment]
did you follow the expo web docs? https://moti.fyi/web#expo-web-support

can I see your webpack config?

**Comment by nandorojo** [comment]
oh i see, it says there’s no dist/framer-motion…interesting

**Comment by nandorojo** [comment]
Okay I solved it. To fix it, I **deleted the webpack.config.js file.** It seems that it's no longer needed.

I just did the following:

```sh
npx create-react-native-app -t with-moti
# cd into it
yarn add  @expo/webpack-config moti
yarn web
```

I got a Reanimated error in the console and added this to my `App.js`:

```ts
import { Platform, Pressable, StyleSheet } from "react-native";
if (Platform.OS === "web") {
  window._frameTimestamp = null;
}
```

I'll update the docs.

**Comment by etiennelacoursiere** [comment]
Yes i confirm that fixes it! Thanks!
