### ISSUE TITLE
does not work with react-native-web 0.19

### ISSUE THREAD

**Issue by macrozone** [nandorojo/moti#281]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

moti does not work with react-native-web 0.19.x, it yields `TypeError: Cannot convert undefined or null to object`

upstream issue: https://github.com/software-mansion/react-native-reanimated/issues/4335

there is a closed issue, but since it is closed, i think its better to reopen a new one (https://github.com/nandorojo/moti/issues/103)

i can confirm it works properly with react-native-web 0.18.0.

### Expected Behavior

should work with the latest react-native-web

### Versions

```markdown
- Moti:0.24.2
- Reanimated: 3.10
- React Native: 0.71.6
```

### Reproduction

todo

**Comment by nandorojo** [comment]
looks like this fixes it https://github.com/software-mansion/react-native-reanimated/pull/4352/files

**Comment by macrozone** [comment]
> looks like this fixes it https://github.com/software-mansion/react-native-reanimated/pull/4352/files

could not test it though, i currently downgraded react-native-web

**Comment by nandorojo** [comment]
You could patch reanimated if you want, but yeah that also works for now

**Comment by nandorojo** [comment]
I think reanimated 3.3 fixes this.
