### ISSUE TITLE
Skeleton Animation - cannot find module moti/skeleton

### ISSUE THREAD

**Issue by LeoAnt02** [nandorojo/moti#285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The import from the docs for the skeleton loading is not working on my expo project 
All other import works, and other animations are working with no issues

Also there is no existing npm package called moti/skeleton - I also tried motify/skeleton which  seems to be the old version, the npm install but it's not working either in import

```
import { MotiView, AnimatePresence, View } from "moti";
import { Skeleton } from 'moti/skeleton';

export default function Skeleton() {

  const colorMode = 'light';

  return (
      <MotiView
        transition={{
          type: 'timing',
        }}
        style={[styles.container, styles.padded]}
        animate={{ backgroundColor: '#ffffff' }}
      >
        <Skeleton colorMode={colorMode} width={250} />
      </MotiView>

  )
};

```

### Expected Behavior

-

### Versions

```markdown
"expo": "~47.0.14",
 "react-native-reanimated": "^2.14.4",
 "moti": "^0.8.0",
 "react-native": "0.70.8",
 "react-native-web": "~0.18.12",
```

### Screenshots

-

### Reproduction

-

**Comment by LeoAnt02** [comment]
I've found a working solution by adding this config to my webpack, not sure if this is the right way to go


```
const config = await createExpoWebpackConfigAsync(
    {
      ...env,
      babel: {
        dangerouslyAddModulePathsToTranspile: ["moti"],
      },
    },
    argv
  );
  
   config.module.rules.push({
    test: /\.mjs$/,
    include: /node_modules/,
    type: "javascript/auto",
  });
```

**Comment by nandorojo** [comment]
Are you on the latest moti?

**Comment by nandorojo** [comment]
Maybe add `moti/skeleton` to `dangerouslyAddModulePathsToTranspile`?

**Comment by nandorojo** [comment]
> I've found a working solution by adding this config to my webpack, not sure if this is the right way to go
> 
> ```
> const config = await createExpoWebpackConfigAsync(
>     {
>       ...env,
>       babel: {
>         dangerouslyAddModulePathsToTranspile: ["moti"],
>       },
>     },
>     argv
>   );
>   
>    config.module.rules.push({
>     test: /\.mjs$/,
>     include: /node_modules/,
>     type: "javascript/auto",
>   });
> ```

This looks like what the docs recommend.
