### ISSUE TITLE
[Question] Web Compat - Would there a possiblity to support className ? 

### ISSUE THREAD

**Issue by Twiggeh** [nandorojo/moti#292]
Is there a possiblity, that for web support, it would be possible to pass className?

A lot of the css-in-js solutions use className to style components like what moti exports : 

E.g.
```js
styled(MotiView)`
css...
```

**Comment by nandorojo** [comment]
Moti forwards down all props already. I believe RNW doesn’t support className prior to 0.19.

**Comment by Twiggeh** [comment]
Hmm maybe I did someting wrong, because 

```tsx
import { motion } from 'framer-motion';
import { MotiView as View } from 'moti';
import styled from '@emotion/styled';
const MyComponent = styled(View)`
	border: 100px solid red;
`;
```

doesn't work for `View`, but it does work for `motion.div`
