### ISSUE TITLE
[MotiPressable]: rendering breaks using animate prop

### ISSUE THREAD

**Issue by araujobarret** [nandorojo/moti#304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you want this issue prioritized?

- [ ] Yes, I have sponsored
- [X] Not urgent

### Current Behavior

After bumping the reanimated to `3.3.0` `MotiPressable` `animate` throws an error(see screenshot) when rendering the component.

This is ONLY happening in `dev` mode, `release` mode shows no crash/error from what we've seen.

Nothing fancy was used as the animation, just the `opacity` animation when pressed.
```jsx
animate={useMemo(
() =>
  ({ hovered, pressed }) => {
      return {
        opacity: hovered || pressed ? 0.5 : 1,
      }
    },
  []
)}


### Expected Behavior

MotiPressable animates without breaking.

### Steps To Reproduce

This PR https://github.com/artsy/palette-mobile/pull/134 commit fixes the error by removing the animation, trying MotiPressable with reanimated v3.3.0, and MotiPressable `animate` throws the error.

### Versions

```markdown
- Moti: 0.24.2
- Reanimated: 3.3.0
- React Native: 0.69.12
```

### Screenshots

<img width="320" alt="Screenshot 2023-08-02 at 13 10 58" src="https://github.com/nandorojo/moti/assets/15792853/9e77c50b-2de9-429a-b5d9-c596e1110593">

### Reproduction

https://stackblitz.com/edit/nextjs-wfhfwc?file=pages%2Findex.tsx

only happening in native, looks fine on web.

**Comment by nandorojo** [comment]
Remember to  add `‘worklet’` at the top of the `animate` function.
