### ISSUE TITLE
'duration‘ not working with type: 'spring' -> defaults to ~1000ms

### ISSUE THREAD

**Issue by Johkade** [nandorojo/moti#31]
Thanks for this great library! I'm very excited to see it grow.

-> see the title for issue - occurs both with vanilla RN and expo. 
The animation works fine but duration only works with type: 'timing'

**environment:**
- RN 0.63.2 / expo@40.0.1
- moti 0.6.0 and reanimated-2.0.0
- (expo built with the starter project (npx create-react-native-app -t with-moti))

````
//...
import {View as MotiView} from 'moti';

export default function App() {
    const [visible, setVisible] = useState(true);

    return (
        <Pressable onPress={()=> setVisible(prev => !prev)}>
            <MotiView
                animate={{
                    rotate: visible ? '90deg' : '0deg',
                }}
                style={{height: 30, width: 30, backgroundColor: 'darkred'}}
                transition={{
                    duration: 100,
                    type: 'spring', //works with 'timing' 
                }}
            />
        </Pressable>
    );
}
````

**Comment by nandorojo** [comment]
Durations only work for timings. There's no concept of duration with springs. You can use the other spring configurations, such as damping and mass: https://docs.swmansion.com/react-native-reanimated/docs/next/api/withSpring/

**Comment by Johkade** [comment]
Thanks a lot! 
For anyone else looking for a solution - this is how you can pass the spring-config to moti:

`<MotiView
                animate={{
                    rotate: visible ? '90deg' : '0deg',
                }}
                ...
                transition={{
                    damping: 6,
                    mass: 0.5,
                    stiffness: 200,
                    type: 'spring',
                }}
            />`

**Comment by DarinGeorge** [comment]
The docs needs alot better documentation for handling transitions and props overall with moti, understanding its a built on top of reanimated 2, but something is needed that is specific to the way moti works.
