### ISSUE TITLE
Animation starting right away and firing onDidAnimate even if nothing moved

### ISSUE THREAD

**Issue by MSchmidt** [nandorojo/moti#317]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you want this issue prioritized?

- [ ] Yes, I have sponsored
- [X] Not urgent

### Current Behavior

There is a MoviView `<MotiView animate={{ left: pos.x, top: pos.y }} onDidAnimate={() => {}}`. `pos` is a React state. `onDidAnimate` will fire after the animation even though nothing has moved at all. Since `pos` is still at the initial values. `0` in my case.

### Expected Behavior

A bit tricky. At first I thought `onDidAnimate` should not fire if nothing moved. But one can argue that a animation to existing values is still an animation. So maybe `onDidAnimate` should have something similar to the second `finished` argument that indicates if something happened at all. An alternative could be a `autoStart` attribute to control if anything should happen right after rending at all.

### Versions

```markdown
- Moti: 0.25.3
- Reanimated: 3.4.2
- React Native: 0.72.5
```

### Reproduction

This is rather conceptual and hope the description is clear enough.

**Comment by nandorojo** [comment]
Please post all the code, I’m not sure what x and y are

**Comment by nandorojo** [comment]
It is interesting for it to fire on mount…it simply relies on reanimated for that

**Comment by nandorojo** [comment]
Got it, you may want to print the other arguments too as they could be useful for knowing where it animated to

**Comment by nandorojo** [comment]
Got it, yeah I would rely on the attemptedValue for this I think

**Comment by MSchmidt** [comment]
Yes sounds good. So it's not really a bug then? I'm fine to work around this for my use case but thought I would report it anyways. It's not really intuitive to get `onDidAnimate` triggered when nothing visible happened.

**Comment by nandorojo** [comment]
I agree it’s not that intuitive, but given that we allow any number of keys in the animate and from prop (which can change at any time) this is the way of making sure it’s the most correct I believe. I’m also just following reanimated’s behavior which does this (albeit a bit aggressively). Because each property handles its own callbacks I think it’s the best we can do. Hope this makes sense

**Comment by MSchmidt** [comment]
Yes makes sense. I'll just close this then. Maybe it's worth a mention in the docs though? Already very good to know that each property has it's own callback.

**Comment by nandorojo** [comment]
Yeah agreed would be good to mention this
