### ISSUE TITLE
Is there any way to sync translateX and translateY animations?

### ISSUE THREAD

**Issue by ReactorCSA** [nandorojo/moti#318]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you want this issue prioritized?

- [ ] Yes, I have sponsored
- [ ] Not urgent

### Current Behavior

Because of the bouncy spring animations values in sequences become desynchorized after a while

### Expected Behavior

Animate together translateX and translateY and wait until last animation ends

### Steps To Reproduce

<img width="275" alt="image" src="https://github.com/nandorojo/moti/assets/81511054/a91e5c0a-1e1e-4dcb-9bc0-533f332a0b22">
You just have to write something like this inside moti view. After a while because of the different distance — component starts his movement not diagonally, first goes x then y axis.

### Versions

```markdown
- Moti: 0.27.0
- Reanimated: 3.3.0
- React Native: 0.72.6
```

### Reproduction

no build

**Comment by nandorojo** [comment]
Probably with a timing animation instead of spring

**Comment by ReactorCSA** [comment]
Thanks for the fast response sir!
Sure you are right! But spring animations look so great! Maybe it can be handle like a transformMatrix or something like this?
I ran into moti after react-spring, which seemed to handle this well
But as far as I know its the react-reanimated issue with its way to animate translateX and translateY like a different elements.
But anyways I think it will be really cool to handle it

**Comment by nandorojo** [comment]
What if you add a duration to the spring animation? It’s indeed a reanimated issue

**Comment by ReactorCSA** [comment]
WOOOOOOWWWWW it looks like a solution 💯  thanksssssss siiir!!!!
