### ISSUE TITLE
conditional animation-states no longer working w/ reanimated@2.0.0-rc.3 and above

### ISSUE THREAD

**Issue by Johkade** [nandorojo/moti#32]
**issue description:** 
_conditional animations no longer work (animation is not done at all) with reanimated-rc.3 and above._

**env:**
RN 0.63.4 (also tested with 0.63.2)
reanimated 2.0.0-rc.0 up to 2.0.0 (see checklist below)
moti 0.6.0

I tested below code with moti 0.0.6 and the latest reanimated-versions. 
It works as expected for the checked versions, but not für rc.3 and 2.0.0

:heavy_check_mark:   2.0.0-rc.0 
:heavy_check_mark:   2.0.0-rc.1 
:heavy_check_mark:   2.0.0-rc.2 
:no_entry_sign:   2.0.0-rc.3 
:no_entry_sign:   2.0.0 

**code:** 

````
...
import {View as MotiView} from 'moti';

export default function App() {
  const [rotate, setRotate] = useState(true);

  return (
      <Pressable
          onPress={()=> setRotate(prev => !prev)}
          style={{
            alignItems: 'center',
            justifyContent: 'center',
            ...StyleSheet.absoluteFillObject
          }}>
        <MotiView
            animate={{
              rotate: rotate ? '90deg' : '0deg',
            }}
            style={{height: 30, width: 30, backgroundColor: 'red'}}
        />
      </Pressable>
  );
}
````

I'm sorry in advance, if this is not a moti-related issue but a reanimated one...
Also I know that the docs recommend reanimated@**rc.0**, 
but since reanimated@**2.0.0** has come out a few days ago I already upgraded to that in my main App.

Thank you!

**Comment by nandorojo** [comment]
Duplicate #30
