### ISSUE TITLE
Experiencing flashing when animating to any color from `transparent`

### ISSUE THREAD

**Issue by agrawal-rohit** [nandorojo/moti#330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you want this issue prioritized?

- [ ] Yes, I have sponsored
- [X] Not urgent

### Current Behavior

Animating the **backgroundColor** property from `transparent` to another color can result in a brief flash of black before the animation completes. This flash does not occur if the starting color is anything other than transparent.

### Expected Behavior

The color animation should be a smooth transition without the flash of black.

### Versions

```markdown
- Moti: 0.27.0
- Reanimated: ~3.3.0
- Expo: 49.0.0
```

### Screenshots

![2023-12-20 13 57 08](https://github.com/nandorojo/moti/assets/29514438/339389d5-b7d1-41d8-bcab-8513c629f7af)

### Reproduction

Expo Snack: https://snack.expo.dev/@agrawal-rohit/moti-color-flashing-issue

**Comment by nandorojo** [comment]
1. Be sure to use a timing transition
2. This is likely a reanimated issue not Moti
3. Maybe you can try a HEX with 0 opacity by appending `00` to your color and see what it happens there.
4. Consider absolute positioning a background and then using opacity instead

**Comment by agrawal-rohit** [comment]
The HEX with opacity 0 hack worked great, thanks! Not sure what the underlying issue with Reanimated is, but the current solution should do the job for now.

PS - 
1. The black flashing still occurred with a timing transition.
2. The reason I raised the issue here is that I am using Moti as a wrapper for Reanimated. I'm not sure if the resolution might require handling this case differently in Moti itself.
