### ISSUE TITLE
TypeError: 0, _$$_REQUIRE(_dependencyMap[0], "../..").(function imported from other file) is not a function (it is undefined), js engine: hermes

### ISSUE THREAD

**Issue by Linuhusainnk** [nandorojo/moti#331]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you want this issue prioritized?

- [ ] Yes, I have sponsored
- [X] Not urgent

### Current Behavior

App crashes and shows error when using utility function imported from external defined file

### Versions

```markdown
- Moti: 0.27.2
- Reanimated: 3.0.2
- React Native: 0.72.4
```

### Reproduction

https://github.com/Linuhusainnk/Bugs

**Comment by Linuhusainnk** [comment]
@nandorojo will be helpfull if you could go through this issue

shared github repo to reproduce the issue

**Comment by nandorojo** [comment]
Remember, you marked it as not urgent so I'll get to it when I have some free time

**Comment by nandorojo** [comment]
You misspelled Skeleton.Group

**Comment by Linuhusainnk** [comment]
@nandorojo 

spell corrected, still same issue exist

**Comment by nandorojo** [comment]
What makes you think this is a moti issue

**Comment by Linuhusainnk** [comment]
Would be, tried in 3 projects with similar folder structure

**Comment by nandorojo** [comment]
Sorry I don’t understand what you mean. There’s nothing in this error message mentioning moti, so I’m guessing this is a separate issue with your code.

**Comment by Linuhusainnk** [comment]
without moti its working fine

**Comment by Linuhusainnk** [comment]
@nandorojo any config changes needed ?

**Comment by Linuhusainnk** [comment]
@nandorojo 

issue still exist
https://github.com/Linuhusainnk/Bugs

![1](https://github.com/nandorojo/moti/assets/80395697/96285a66-7634-4efa-b4a9-71d9da97dfe3)

**Comment by nandorojo** [comment]
That error you just sent isn't even related to moti. It seems like your setup is off.

Also, in open source it's typically best not to tag someone if you choose not to sponsor just FYI

**Comment by Linuhusainnk** [comment]
Issue sorted out, by changing the babel config to choose specific root path
