### ISSUE TITLE
Expo SDK 49: Moti app crashing on iOS devices

### ISSUE THREAD

**Issue by agrawal-rohit** [nandorojo/moti#333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you want this issue prioritized?

- [ ] Yes, I have sponsored
- [X] Not urgent

### Current Behavior

I have an Expo app that uses Moti, however, when testing the app on an iOS simulator through Expo Snack or when running it on a device using the Expo Go app. The crash doesn't occur on Android devices or when running the app on a local iOS simulator.

I'm not 100% sure if this is a Moti issue, it could be a bug related to Expo Go, but I'm open to any solutions or hacks if you've encountered this before. Thanks!

### Versions

```markdown
- Moti: 0.27
- Reanimated: ~3.3.0
- React Native: 0.72.6
```

### Reproduction

https://snack.expo.dev/@agrawal-rohit/moti-crash?platform=ios

**Comment by nandorojo** [comment]
Snack doesn’t work with moti, but expo go will.

**Comment by agrawal-rohit** [comment]
@nandorojo, is that expected behavior or an incompatibility issue with Snack and Moti?

**Comment by nandorojo** [comment]
Moti works fine. But expo’s online snack editor has issues with libraries that use reanimated, which is why moti doesn’t work.

it works fine in any actual app that isn’t on snack online

**Comment by lsps9150414** [comment]
Hi @nandorojo , the installation mentioned `[Please follow Reanimated's installation instructions for v2.](https://moti.fyi/installation#if-you-arent-using-expo)` for Expo. Does reanimated v3 works? I'm running into this production only issue: #334

**Comment by nandorojo** [comment]
Yeah, though you should upgrade moti on that example
