### ISSUE TITLE
List of skeleton  is very  slow

### ISSUE THREAD

**Issue by FouadMagdy01** [nandorojo/moti#341]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you want this issue prioritized?

- [ ] Yes, I have sponsored
- [X] Not urgent

### Current Behavior

When i try to render a list of skeleton views it is very slow and  bad for ux
I think thr issue is from using linear gradient  which is being rendered natively 

Si, rendering too much skeletons become impossible to being handled 

Try to use RN reanimated  instead

### Expected Behavior

List of skeletons should be not that slow

### Steps To Reproduce

1- create a skeleton view
2- try to render more than 5 and notice the performance  issues

### Versions

```markdown
- Moti:latest
- Reanimated:latest
- React Native:latest
```

### Screenshots

Not provided

### Reproduction

Try to create list of skeleton  MotiViews

**Comment by nandorojo** [comment]
Moving to https://github.com/nandorojo/moti/issues/336
