### ISSUE TITLE
moti is not working in expo router project with Expo sdk 49

### ISSUE THREAD

**Issue by duochizhacai** [nandorojo/moti#349]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you want this issue prioritized?

- [ ] Yes, I have sponsored
- [ ] Not urgent

### Current Behavior

i was using  npx create-expo-app@latest --template tabs@49 to create a expo project with expo sdk 49, but it is not working with error (0 , _framerMotion.usePresence) is not a function

### Steps To Reproduce

1. create new Expo router project with sdk49. command:  npx create-expo-app@latest --template tabs@49
2. install moti dependency
3. use moti component
4. get into an error

(0 , _framerMotion.usePresence) is not a function

Call Stack
Moti
node_modules/moti/build/core/motify.js:14:15
renderWithHooks
node_modules/react-dom/cjs/react-dom.development.js:16307:7
updateForwardRef
node_modules/react-dom/cjs/react-dom.development.js:19229:10
beginWork
node_modules/react-dom/cjs/react-dom.development.js:21639:10
HTMLUnknownElement.callCallback
node_modules/react-dom/cjs/react-dom.development.js:4166:9
Object.invokeGuardedCallbackDev
node_modules/react-dom/cjs/react-dom.development.js:4216:16
invokeGuardedCallback
node_modules/react-dom/cjs/react-dom.development.js:4279
beginWork$1
http://localhost:8081/index.bundle

![image](https://github.com/nandorojo/moti/assets/58379214/9008e4c0-6d4e-4283-813b-0ffd85ec9834)

### Versions

```markdown
- Moti: 0.29.0
- Reanimated: 3.11.0
- React Native: 0.72.6
```

### Reproduction

https://codesandbox.io/p/devbox/qh92f2?file=%2Fapp%2Fmodal.tsx%3A3%2C42

this sandbox can not see through the problem, but it can show precise error if you reproduce in the local

**Comment by yousefturin** [comment]
having the same issue 
Versions:
    "expo": "^51.0.8",
    "moti": "^0.29.0",
    "react-native": "0.74.1",
    "react-native-reanimated": "~3.10.1"
