### ISSUE TITLE
Skeleton is not working because of null useContext from Skeleton.js

### ISSUE THREAD

**Issue by yousefturin** [nandorojo/moti#350]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you want this issue prioritized?

- [ ] Yes, I have sponsored
- [ ] Not urgent

### Current Behavior

I was using npx create-expo-app StickerSmash --template blank to create an expo project sdk 51, but it is not working with error Cannot read property 'useContext' of null

### Steps To Reproduce

1. Create a new Expo project with sdk 51. command: npx create-expo-app StickerSmash --template blank
2. Install moti dependency.  command: npx expo install moti
3. Install reanimated dependency. command: npx expo install react-native-reanimated
4. Install expo-linear-gradient dependency. command: npx expo install expo-linear-gradient
5. Use moti skeleton component
6. Run the app. command: npx expo start --tunnel
7. Get an error message:
TypeError: Cannot read property 'useContext' of null

ERROR  Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
 ERROR  Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
 ERROR  TypeError: Cannot read property 'useContext' of null

This error is located at:
    in Skeleton
    in SkeletonExpo (created by App)
    in RCTView (created by View)
    in View (created by App)
    in RCTView (created by View)
    in View (created by App)
    in App (created by withDevTools(App))
    in withDevTools(App)
    in RCTView (created by View)
    in main(RootComponent), js engine: hermes
 ERROR  TypeError: Cannot read property 'useContext' of null

### Versions

```markdown
- Moti: 0.29.0
- Reanimated: 3.10.1
- React Native: 0.74.1
- expo-linear-gradient: 13.0.2
- expo: 51.0.8
```

### Screenshots

![IMG_0206](https://github.com/nandorojo/moti/assets/94796673/cc3ae7ae-0ba0-4a73-93c3-17b4c8a22c62)

### Reproduction

https://codesandbox.io/p/github/yousefturin/Bug-report-moti/master?file=%2Fpackage.json%3A4%2C30&workspaceId=8bcfb81d-12cd-4e3c-8fa1-5b7bd94dab01
To connect a mobile the run command must be npx expo start --tunnel and the error will show.

**Comment by yousefturin** [comment]
For some reasons I have tried to use the solution from #189, but it did not work I tried again the next day with the exact same steps and it did work.
my apology.

**Comment by T-Pyat** [comment]
Same problem!

**Comment by yousefturin** [comment]
to solve the issue in my case was just to delete the node models folder and install it using 
`npm install --legacy-peer-deps`
The issue was that I had a dirty node models file and when I had to run the application after re-installing it was giving this error, and the solution was to use the legacy peer deps command when installing the packages.

**Comment by nandorojo** [comment]
Ahh yes npm always has this issue. The moti docs mention using legacy peer deps for this reason. I use yarn so I never come across it. Thanks for sharing!

**Comment by oskarnellfors** [comment]
I have this same issue, and yes this works for local install but or preview or production-build crashes, builds built on eas. Should I really change the build-command to use legacy, seems weird.

**Comment by yousefturin** [comment]
> I have this same issue, and yes this works for local install but or preview or production-build crashes, builds built on eas. Should I really change the build-command to use legacy, seems weird. 

I have no knowledge about eas build but when a package requires a specific installation guide when I dockerize other  projects I use the correct command line  mentioned by the developer.

Running legacy command is safest option, if it does not break other packages you use then use it, if you see a side effect trace the package and override the legacy only for the needed package.

**Comment by yousefturin** [comment]
> > For some reasons I have tried to use the solution from #189, but it did not work I tried again the next day with the exact same steps and it did work. my apology.
> 
> 
> 
> i tried doing that `npm i --legacy-peer-deps` and it is working when i run the app on expo go 
> 
> but when try building the preview and install the apk and when i open the apk it is crashing the application
> 
> im not sure but i think while building not know about he legacy peer deps it might be just building the apk with the latest packages or something like that , how can tell expo to go with the packages that were running on expo or is there any way and btw what does [this](https://github.com/nandorojo/moti/issues/189#issuecomment-1095085789) this do .


if you use RN for building the Apk file then there is a big chance you are using particles of some version of the package, so when you run the app in expo go you won't see the issue since your node does have the correct package installed using the legacy tag but when building then it does not, 

Solution is to delete the android file and pre build it again that way you will ensure the changes from package.json are shown in the android file correctly, you can use the:

'npx expo prebuild --platform android --clean'

then you can build the app using the 
'./gradlew assembleRelease'
this way it will solve you issues.

**Comment by Praisecodes** [comment]
I'm experiencing this exact same issue now with Moti at version 0.30.0, react at version 19, etc. basically the latest of all packages including expo sdk 53.
Any solutions, please?

**Comment by ZetMine** [comment]
> I'm experiencing this exact same issue now with Moti at version 0.30.0, react at version 19, etc. basically the latest of all packages including expo sdk 53. Any solutions, please?

I'm also having this error with the same project settings.
this is my whole package.json:
```json
{
  "name": "organized",
  "version": "1.0.0",
  "main": "expo-router/entry",
  "scripts": {
    "start": "expo start",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "2.1.2",
    "axios": "^1.10.0",
    "expo": "~53.0.17",
    "expo-blur": "~14.1.5",
    "expo-router": "~5.1.3",
    "expo-splash-screen": "~0.30.10",
    "expo-status-bar": "~2.2.3",
    "lottie-react-native": "7.2.2",
    "moti": "^0.30.0",
    "nativewind": "^4.1.23",
    "prettier-plugin-tailwindcss": "^0.5.14",
    "react": "19.0.0",
    "react-native": "0.79.5",
    "react-native-gesture-handler": "~2.24.0",
    "react-native-reanimated": "~3.17.4",
    "react-native-redash": "^18.1.3",
    "react-native-safe-area-context": "^5.4.0",
    "react-native-screens": "~4.11.1",
    "react-native-svg": "15.11.2",
    "react-native-worklets": "^0.4.1",
    "tailwindcss": "^3.4.17",
    "expo-network": "~7.1.5",
    "expo-navigation-bar": "~4.2.7",
    "expo-linear-gradient": "~14.1.5",
    "expo-linking": "~7.1.7"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "react-native-svg-transformer": "^1.5.1"
  },
  "private": true
}
```
