### ISSUE TITLE
Any imported Moti components break in React Native because of a userAgent check used by framer-motion

### ISSUE THREAD

**Issue by avivash** [nandorojo/moti#352]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you want this issue prioritized?

- [ ] Yes, I have sponsored
- [x] Not urgent

### Current Behavior

When I import any Moti component into my react native app, I see this error that `userAgent` is undefined. I traced it back to the `framer-motion` library, which I didn't think was used on native?

<img width="402" alt="image" src="https://github.com/nandorojo/moti/assets/1179291/882e6bb1-b69f-4b60-a30c-0741049db40b">

### Expected Behavior

I should be able to import components.

### Steps To Reproduce

1. add `reanimated` imports to my App.tsx 
```ts
import 'react-native-reanimated'
import 'react-native-gesture-handler
```
2. Import any Moti component into my app and I get the `navigator.userAgent` undefined error because of `framer-motion`

### Versions

```markdown
- Moti: 0.29.0
- Reanimated: 3.6.3
- React Native: 0.72.3
```

### Screenshots

<img width="404" alt="image" src="https://github.com/nandorojo/moti/assets/1179291/721648bd-8912-4c5d-a3a0-dd86c97e7676">

### Reproduction

will add

**Comment by avivash** [comment]
I was able to get this working by polyfilling `navigator.userAgent` for now, but I wonder if there's a better way?

```ts
if (!global?.navigator?.userAgent) {
  global.navigator = {
    ...global.navigator,
    userAgent: 'React Native',
  }
}
```

**Comment by nandorojo** [comment]
might be a framer version issue

**Comment by avivash** [comment]
> might be a framer version issue

thanks 👍🏼 i'll try to diagnose further

**Comment by nandorojo** [comment]
Surprised I have never faced this...is this still happening for you? Going to close for now in case you aren't

**Comment by zipme** [comment]
I got the same issue 🥲

**Comment by zipme** [comment]
Resolved the issue by overriding the framer-motion version in the pnpm configuration:

```json

"pnpm": {
    "overrides": {
     ...
      "framer-motion": "11.13.0-beta.0"
    }
  }
```
