### ISSUE TITLE
Moti infinite loop animation stops on parent's state change

### ISSUE THREAD

**Issue by caticodev** [nandorojo/moti#357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you want this issue prioritized?

- [ ] Yes, I have sponsored
- [X] Not urgent

### Current Behavior

 MotiView set to loop indefinitely stops animating after parent's state is updated.

### Expected Behavior

 MotiView set to loop indefinitely should continue animating after parent's state is updated.

### Steps To Reproduce

1. Create a parent component that will trigger a state update after some time
2. Make MotiView a child component
3. Observe that infinite loop animation stops when the parent's component state changes

### Versions

```markdown
- Moti: 0.29.0
- Reanimated: 3.10.0
- React Native: 0.74.1
```

### Screenshots

https://github.com/user-attachments/assets/544647de-a7d1-4da7-9973-f840f78f7f92

### Reproduction

Moti stopping the animation after parent update
https://stackblitz.com/edit/nextjs-besefg?file=pages%2Findex.tsx

Comparing same animation in reanimated and moti
https://github.com/caticodev/moti-test/tree/flash

**Comment by nandorojo** [comment]
can you wrap the component or props in `useMemo`

**Comment by caticodev** [comment]
Yes, that does solve the issue. Thanks!
