### ISSUE TITLE
How to loop animation with reset the value

### ISSUE THREAD

**Issue by minhchienwikipedia** [nandorojo/moti#39]
Hi, I don't know how to animate "the heart" like this. 
![Screen Recording 2021-03-19 at 10 10 24 AM](https://user-images.githubusercontent.com/20647079/111726435-8d7cb200-889b-11eb-887e-aff71428e32b.gif)
Like I understand we can create animation for the heart
- opacity 0 -> 1 -> 0
- translate  A -> B 
and then it reset value -> loop again
And in `moti` I can't reset the value to loop again like this
Can you create an example for this?

**Comment by nandorojo** [comment]
Did you try this:

```jsx 
<View
  {...}
  transition={{
    loop: true
  }}
/>
```

**Comment by minhchienwikipedia** [comment]
@nandorojo I mean the animation of the heart flying, `loop` work as well, but I want to create an animation like that. It's fade in, fade out with translate and loop again. If you try create animation like that you will see an issue, maybe

**Comment by nandorojo** [comment]
Sorry I don't understand what you want to do.

**Comment by minhchienwikipedia** [comment]
Example:
```javascript
<View
      from={{
          opacity: 0,
          scale: 0.3,
          translateY: 0,
          translateX: 0,
      }}
      animate={{
          opacity: 1,
          scale: 1,
          translateY: -150,
          translateX: -100,
      }}
      transition={{
          type: 'timing',
          loop: true,
          duration: 1000,
      }} 
  />
```
This is the full option for custom `moti` and this is what I get. 
![Screen Recording 2021-03-19 at 3 47 34 PM](https://user-images.githubusercontent.com/20647079/111754418-8faa3500-88ca-11eb-839c-71e6ed2183f8.gif)

I want it to fade out like the gift file above. It's should be fade out & reset to first step and loop. I just want to using moti to create animation like above

**Comment by godness84** [comment]
@minhchienwikipedia have you tried adding `repeatReverse={false}` in `transition` prop?

**Comment by nandorojo** [comment]
That should be the solution, I just need to publish the new version that adds support for that in the root transition object.

**Comment by minhchienwikipedia** [comment]
@godness84 @nandorojo thanks for your support, I'll try when next version updated

**Comment by nandorojo** [comment]
Try `0.6.5`

`yarn add moti`

**Comment by minhchienwikipedia** [comment]
@nandorojo it's work as well but I want it to fade out like the first gift, can you show me how to I do it?
![Screen Recording 2021-03-20 at 1 07 36 PM](https://user-images.githubusercontent.com/20647079/111860980-68f90680-897d-11eb-86f4-1e29cc22c89e.gif)

**Comment by nandorojo** [comment]
Sorry I don't see how this is related to the original gif.
