### ISSUE TITLE
support transition.type = 'linear' ?

### ISSUE THREAD

**Issue by KingAmo** [nandorojo/moti#42]
it seems that Currently we only support 'spring' and 'timing' transition; i want to use a linear animation, could you please help?

**Comment by nandorojo** [comment]
I believe you're referring to the `easing` function, which is a customization in `timing` animations.

**Comment by KingAmo** [comment]
> I believe you're referring to the `easing` function, which is a customization in `timing` animations.

yes exactly, how can i config `easing` in transition please?

**Comment by KingAmo** [comment]
oh i found it in `example` fold:

```
import {Easing} from 'react-native-reanimated';

       transition={{
          loop: true,
          type: 'timing',
          duration: 500,
          repeatReverse: false,
          easing: Easing.linear,
        }}

```

thanks a lot!

**Comment by nandorojo** [comment]
```jsx
<MotiView 
  transition={{
    type: 'timing', 
    easing: Easing.linear
  }}
/>
```

And `import { Easing } from 'react-native-reanimated`
