### ISSUE TITLE
Incorrect TS types for <Text />

### ISSUE THREAD

**Issue by nandorojo** [nandorojo/moti#46]
<img width="370" alt="Screen Shot 2021-03-29 at 4 01 10 PM" src="https://user-images.githubusercontent.com/13172299/112893360-8ed28980-90a8-11eb-8158-60b355b9974a.png">

Seems like the `TextStyle` type isn't forwarding the text keys. Not sure why.

**Comment by informsharique** [comment]
I'm still experiencing the same issue? Why this was closed though?

```ts
<MotiText
	// @ts-ignore reason: types are not properly defined on the moti package
	from={{ color: '#797979' }}
	animate={{
		@ts-ignore reason: types are not properly defined on the moti package
		color: activeButtonBasedOnControlled === button
			? colorScheme === 'dark'
			? 'black'
				: 'white'
			: '#797979',
	}}
	transition={{ duration: 200, type: 'timing' }}
	className="font-inter font-normal"
	numberOfLines={1}
>
	{button}
</MotiText>
```
					
Have to tsignore to opt out of ts errors.

**Comment by nandorojo** [comment]
you probably need to delete types/react-native from your repo and upgrade moti

**Comment by informsharique** [comment]
I'm using expo SDK 50... don't have @types/react-native installed in the repo and also on the latest release of moti version 0.28.1

**Comment by neiker** [comment]
I'm facing the same issue with a fresh install of Moti. Looks like the source of having `@types/react-native` is `@gorhom/bottom-sheet`

https://github.com/gorhom/react-native-bottom-sheet/pull/2056
