### ISSUE TITLE
Tried to synchronously call function {_definedProperty} from a different thread

### ISSUE THREAD

**Issue by khunghang16** [nandorojo/moti#48]
When I run example component Skeleton, i had bug crash app.

I don't use Expo
- Version: 
   -"@motify/skeleton": "^0.8.1"
   -"expo-linear-gradient": "^9.0.0"
   -"moti": "^0.8.1"
   -"react-native-reanimated": "^2.1.0"
   -"react-native-unimodules": "^0.12.0"
- My Code:
`import React, { useReducer } from "react";
import { StyleSheet, Pressable } from "react-native";
import { View } from "moti";
import { Skeleton } from "@motify/skeleton";

const Spacer = ({ height = 16 }) => <View style={{ height }} />;

const transition = {
  opacity: {
    duration: 300,
  },
};

export default function HelloWorld() {
  const [dark, toggle] = useReducer((s) => !s, true);

  const colorMode = dark ? "dark" : "light";

  return (
    <Pressable onPress={toggle} style={styles.container}>
      <View
        transition={{
          type: "timing",
        }}
        style={[styles.container, styles.padded]}
        animate={{ backgroundColor: dark ? "#000000" : "#ffffff" }}
      >
        <Skeleton
          transition={transition}
          colorMode={colorMode}
          radius="round"
          height={75}
          width={75}
        />
        <Spacer />
        <Skeleton
          transition={transition}
          colorMode={colorMode}
          width={250}
        />
        <Spacer height={8} />
        <Skeleton
          transition={transition}
          colorMode={colorMode}
          width={"100%"}
        />
        <Spacer height={8} />
        <Skeleton
          transition={transition}
          colorMode={colorMode}
          width={"100%"}
        />
      </View>
    </Pressable>
  );
}

const styles = StyleSheet.create({
  shape: {
    justifyContent: "center",
    height: 250,
    width: 250,
    borderRadius: 25,
    marginRight: 10,
    backgroundColor: "white",
  },
  container: {
    flex: 1,
    justifyContent: "center",
  },
  padded: {
    padding: 16,
  },
});`

![simulator_screenshot_D05A4B3C-694A-4D75-A8A3-7E887B608ACE](https://user-images.githubusercontent.com/27754944/113402770-c9516480-93cf-11eb-850f-5b0520035728.png)

**Comment by nandorojo** [comment]
Which Reanimated version are you using?

**Comment by nandorojo** [comment]
I have an idea for what is causing this. I'll look into it and get back to you shortly.

Thanks for the issue!

**Comment by ksitko** [comment]
I just stepped through Moti 8.1 to 7.1, all of which seem to have the same issue. Moti 0.6 does not have the issue.

**Comment by nandorojo** [comment]
Good to know, thanks for the heads up. I think it's related to AnimatePresence. Hopefully will be a quick fix.

**Comment by nandorojo** [comment]
I believe 0.7.2 is the cause. Could you try 0.7.1 and 0.7.2 to compare? Make sure you save exact versions to be sure.

**Comment by ksitko** [comment]
Apologies, I don't think I was clear, when I said 0.8.1 to 0.7.1 I meant inclusively. I just tested 0.7.0, and I have the same issue.

**Comment by nandorojo** [comment]
Ah got it.

**Comment by nandorojo** [comment]
Could you try 0.7.0 but make sure to fully delete node modules and clear the cache with `expo start -c` if you're using Expo? I have a feeling this one should solve it. I'm not at my computer for now but I'm reading through the commits.

**Comment by ksitko** [comment]
`0.6.5` is the latest version I can run without encountering that exact issue on app launch.

**Comment by nandorojo** [comment]
Appreciate all the testing.

It's a bit odd because the release for 0.7.0 only includes a [new hook](https://github.com/nandorojo/moti/commit/8f65da78fd913f87e089ddbc3c402fc42e41d9d2). It doesn't seem to touch the files in question (skeleton included).

Are you using the same code as the original poster, or is yours not the skeleton?

**Comment by ksitko** [comment]
I'm not using the same code as the original poster, I'm using Moti in an app I'm working on. Unfortunately after adding 0.7.0 and then running:
```
rm -rf ./node_modules
yarn
yarn start --reset-cache
```
I'm getting the same exact error.

**Comment by nandorojo** [comment]
Got it. Are you using Expo? I have no issues running the latest on my Expo SDK 41 app.

Also which Reanimated are you using? I'm on 2.0.0, maybe that could be it?

Are you using a skeleton or AnimatePresence?

**Comment by ksitko** [comment]
I'm using AnimatePresence and expo in the bareworkflow.
```
"expo": "^40.0.1",
"react-native-reanimated": "2.1.0",
```

**Comment by nandorojo** [comment]
Good to know. Could you try 2.0.0? Reanimated has an aggressive cache FYI, so you'll need to `expo start -c`

**Comment by nandorojo** [comment]
Also, if you remote the exit prop from your components, does it solve it? I know it might be annoying to try that if you use exit in many places, so if you do, don't worry about it.

**Comment by khunghang16** [comment]
I try use react native reanimated version 2.0.0 with moti version 0.8.1 in
bare react native project, but it still. Hope you can fix it soon. Thank
you.

Vào Th 6, 2 thg 4, 2021 lúc 20:19 Fernando Rojo ***@***.***>
đã viết:

**Comment by ksitko** [comment]
I can give it a shot. It's not a managed Expo app, I'm just using Expo unimodules and some select libraries.

**Comment by khunghang16** [comment]
I remote the exit prop from MotiView, it work. However, i use Skeleton
component. It dont work.

Vào Th 6, 2 thg 4, 2021 lúc 20:22 Fernando Rojo ***@***.***>
đã viết:

**Comment by ksitko** [comment]
Moti 7.0.0 and Reanimated 2.0.0 still has the issue. I'll try to remove the Exit props next.

**Comment by ksitko** [comment]
Removing exit props from my Moti Views does in fact remove the error when using Moti 7.0.0 and Reanimated 2.0.0

**Comment by nandorojo** [comment]
That's good news. I should be able to fix this today then. Thanks for your patience here.

**Comment by nandorojo** [comment]
Does it also remove the error on the latest version if you remove exit?

**Comment by nandorojo** [comment]
Just released `0.8.2`, which solves this on my end.

`yarn add moti`

Could you confirm that this fixes it?

**Comment by ksitko** [comment]
moti `0.8.2` fixes it for me. Thank you for the speedy fix.

**Comment by nandorojo** [comment]
Awesome. Thanks for the testing.

The problem was that Reanimated didn't allow me to reduce an object using Object.keys. I changed it to a .forEach and that fixed it.
