### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by nandorojo** [nandorojo/moti#5]
Let's get some good docs setup.

**Comment by jairosl** [comment]
it would be cool if they put visual examples, just like frame motion does

**Comment by uragirii** [comment]
I would love to help with docs and setup some examples just like the framer motion website. This package looks very promising.

**Comment by nandorojo** [comment]
Yeah I'd like that, it would require Expo snack to support Reanimated I think.

Unless @slorber thinks we can get React Native Web into Docusaurus somehow, including Reanimated & expo's Babel plugins.

@cmaycumber mentioned using `react-view` to show interactive examples.

Also, the docs are currently published at [moti.fyi](https://moti.fyi)

**Comment by cmaycumber** [comment]
@nandorojo I've actually got RNW working with Docusaurus before. I'm not sure about the babel plugins for reanimated or expo but I think that you can customize the babel config so I don't think it would be difficult.

**Comment by nandorojo** [comment]
Well that's certainly intriguing.

**Comment by cmaycumber** [comment]
I can create a PR and see if I can get it working.

**Comment by nandorojo** [comment]
That would be awesome.

**Comment by nandorojo** [comment]
It would also be cool to have code sandboxes, for instance with Next.js.

**Comment by cmaycumber** [comment]
I got the RNW but am running into trouble with react-native-reanimated. 

Maybe @slorber has some insight. 

I'm getting the same error as an open issue for `gatsby-plugin-react-native-web`.

Relevant issue: https://github.com/slorber/gatsby-plugin-react-native-web/issues/24

**Comment by slorber** [comment]
My long term goal is to move my blog/site to Docusaurus but unfortunately I don't have time to work on that currently 😔

Not sure what this Reanimated error is about. 

Also if you get it RNW working on Docusaurus it would likely only be client-side, because on SSR we need to extract/inline the critical css to avoid FOUC on first load. For an anim library client side only is probably fine anyway, as it's not content to be indexed for SEO

**Comment by cmaycumber** [comment]
> My long term goal is to move my blog/site to Docusaurus but unfortunately I don't have time to work on that currently 😔
> 
> Not sure what this Reanimated error is about.
> 
> Also if you get it RNW working on Docusaurus it would likely only be client-side, because on SSR we need to extract/inline the critical css to avoid FOUC on first load. For an anim library client side only is probably fine anyway, as it's not content to be indexed for SEO

Got it thanks for the feedback. I'll probably take another crack at it sometime today. 

@nandorojo Do you think that SSR is important for the docs? I'm wondering if it's possible to somehow avoid rendering the RNW content serverside, and render the rest SSR so we don't really lose anything in terms of SEO.

**Comment by nandorojo** [comment]
I think we need SEO for the content of the docs, otherwise people won't find it easily. 

We can definitely avoid SSR for the moti examples though. Animations can lazy load in if needed, that's not a problem.

**Comment by cmaycumber** [comment]
> Yeah I'd like that, it would require Expo snack to support Reanimated I think.

Do you know if snacks support reanimated? 

They could be the move. I'm struggling to get the docs working with it.

**Comment by nandorojo** [comment]
I don't think they do quite yet. I'll ask the Expo team to be sure.

**Comment by nandorojo** [comment]
https://github.com/nandorojo/moti/issues/53 added this issue for Snack examples
