### ISSUE TITLE
start and end animation with state

### ISSUE THREAD

**Issue by kickbk** [nandorojo/moti#50]
Curious how you handle starting and stopping animations with Moti. In the docs for looped animation you explain that we can't change the animation on the fly, so I figured I'll use state to switch it on and off like so:

```
import { View } from 'moti';
const [animating, setAnimating] = useState(false);
<Pressable
  onPress={() => {
    setAnimated(true);
    Run_some_api_call({...})
    .then(() => {
      setAnimating(false);
      })
      .catch(() => {
          setAnimating(false);
      });
  }}>
  {animating ? (
    <View
      from={{
        scale: 1,
      }}
      animate={{
        scale: 0.7,
      }}
      transition={{
        loop: true,
        type: 'timing',
        duration: 200,
        delay: 100,
      }}>
      <Icon
        name={favorited ? 'heart' : 'heart-o'}
        type="font-awesome"
      />
    </View>
  ) : (
    <View>
      <Icon
        name={favorited ? 'heart' : 'heart-o'}
        type="font-awesome"
        size={Sizes.x1}
        color={Colors.dineden_400}
      />
    </View>
  )}
  ...
```
But it gets stuck when it's making the api call. I even placed `setAnimating` in the response inside a `setTimeout` to create a few seconds delay. There's no animation. I see it grow smaller without animation, and after the delay it jumps back to scale 1.

Similarly, I tried setting the Skeleton component `show` property with state while loading network images and it's not smooth either.

Using Expo sdk 41 with reanimated 2.1.0

How do you handle these scenarios?

**Comment by nandorojo** [comment]
One way to reset the loop is to update the `key` of the Moti component. You could then set remove loop on the key change. Could that help?

**Comment by kickbk** [comment]
Yeah, that works 👍
Thanks
