### ISSUE TITLE
Animating position on exit

### ISSUE THREAD

**Issue by marklawlor** [nandorojo/moti#56]
I'm trying create a TabView component  that animates between sliding tabs. The components height should adjust for the current tab and not be affected by the exiting tab.

I would expect this code to work, how ever the `position: "absolute"` is not applied on exit.

```
export default function TabView({ tabIndex }) {
  const tabs = [<View style={{ height: 100 }} />, <View style={{ height: 200 }} />]

  return (
      <AnimatePresence>
        <View
          key={tabIndex}
          from={{
            translateX: "100%",
          }}
          animate={{
            translateX: "0%",
             position: "relative"
          }}
          exit={{
            translateX: "-100%",
            position: "absolute"
          }}
          transition={{
            type: "timing",
          }}
        >
          {tabs[tabIndex]
        </View>
      </AnimatePresence>
      )
}
```

I'm not sure if this is expected behaviour or not

**Comment by nandorojo** [comment]
Why not remove the absolute position and instead use `exitBeforeEnter` on `AnimatePresence`?

**Comment by marklawlor** [comment]
I'd prefer not to use `exitBeforeEnter` for stylistic reasons, as I would prefer to render both the entering and exiting tabs together.

I was able to work around this issue by manually updating the style prop on my view when tabIndex changes, but it would be nice for position to be included in the exit animated props.

**Comment by nandorojo** [comment]
Is it possible reanimated doesn't allow `position` inside of `useAnimatedStyle`? I'm not entirely sure why that wouldn't work, other than the fact that it's not an animation style

**Comment by nandorojo** [comment]
It might be because it's wrapping `withSpring('absolute')`. Maybe we can add a custom resolver for `position` that implements it directly without a spring / timing function. I'd have to think about that a little after confirming position works in `useAnimatedStyle`

**Comment by nandorojo** [comment]
For now, as you said, I would just toggle the `style` prop based on the index.
