### ISSUE TITLE
Problem with using AnimatePresence when using rotation

### ISSUE THREAD

**Issue by Stevemoretz** [nandorojo/moti#61]
Using this example : 
`https://github.com/expo/examples/blob/master/with-moti/App.js`

Just adding rotation to it :

```tsx
            from={{
                opacity: 0,
                scale: 0.2,
                rotateZ: "45deg",
            }}
            animate={{
                opacity: 1,
                scale: 1,
                rotateZ: "0deg",
            }}
            exit={{
                opacity: 0,
                scale: 0.5,
                rotateZ: "45deg",
            }}
```

Causes some unexpected results on enter animation.

**Comment by nandorojo** [comment]
Need more details to look into this. My guess is it's a reanimated bug, not dripsy.

**Comment by Stevemoretz** [comment]
I'm using this on expo sdk 41 on iOS. Just using that example but added rotateZ parts to it.
