### ISSUE TITLE
Mistake in your example

### ISSUE THREAD

**Issue by Stevemoretz** [nandorojo/moti#63]
https://moti.fyi/examples/auto-height

this example `backgroundColor: 'green'` is set in the wrong place, making it feel like a bug, what's happening is that going to 300 pixels the green view seems to be animated which actually isn't but going back to 100 feels like a bug jumping back without animating the height, but it's normal, it wasn't animating in the first place either just overflow hidden has made it look like that ,what you should have to fix this is :

```tsx
            <MotiView
                animate={{height}}
                style={{overflow: "hidden", backgroundColor: "green"}}
            >
                <View onLayout={onLayout} style={{height: open ? 100 : 300}} />
            </MotiView>
            <Button title="toggle" onPress={toggle} />
```

**Comment by nandorojo** [comment]
I'm going to get rid of this example in favor of another one soon
