### ISSUE TITLE
transitionTo Callback

### ISSUE THREAD

**Issue by chrissm79** [nandorojo/moti#67]
Hey there, I'll start by saying this library is pretty amazing 😍 

I'm currently leveraging the `useAnimationState` hook to define some different states for my View. After I've transitioned to some of these states I'd like to fire a function, but there doesn't appear to be a straightforward way to accomplish this. My current setup only requires that the callback is fired for a single state, so I have a workaround, however I could see this eventually being a need for several states in different applications. It would be great if we could so something like the following:

```js
const animationState = useAnimationState({
  from: {
    opacity: 1,
    height: 100,
  },
  expanded: {
    opacity: 1,
    height: 200,
  },
  // ...
})

const onPress = () => {
  animationState.transitionTo("expanded", () =>
    console.log("transition has completed"),
  )
}
```

**Comment by nandorojo** [comment]
Hey, I totally see the merit in this. However, since reanimated animates based on individual styles, and not for an entire set of styles, this isn't possible.

However, the components do have an `onDidAnimate` prop, which tells you which value just animated. Would this help?

It doesn't currently include the value it animated to, though, since this isn't provided by Reanimated. 

I could try to include the attempted value that the style animated to in that callback, maybe that would help?

```js
onDidAnimate: (key, finished, value?, { attemptedValue }) => key === 'opacity' && finished && attemptedValue === 1
```

Could that help?

**Comment by chrissm79** [comment]
Hey @nandorojo, yes that would be a great solution 👍 Thanks for the quick response!

**Comment by chrissm79** [comment]
@nandorojo Actually, I may have been a little quick to the request to add the extra parameter to the `onDidAnimate` callback. In my scenario, I think what I need is already provided

```
onDidAnimate={(_, completed) => {
  if (completed && animationState.current === "expanded") {
    onExpanded()
  }
}}
```

I'm going to close this as I've tested it out on my project and it works well for my requirements. Thanks again!

**Comment by nandorojo** [comment]
Got it. I'd found myself wanting that anyway, so I just published the added event object. Feel free to update and try it out if you need more granular info about the animation fallback.

**Comment by chrissm79** [comment]
Much appreciated, thanks again @nandorojo!!

**Comment by nandorojo** [comment]
No problem.

FWIW, I would usually encourage the opposite behavior: animate based on the app state, rather than trigger app state based on the animation. But the callback is there as a fail safe!
