### ISSUE TITLE
Exit animation not shown

### ISSUE THREAD

**Issue by TijsM** [nandorojo/moti#68]
## What
Exit animation not shown

## Expected
the "toast" should fade out

## Things I tried
* add animated presence (with and without exitBeforeEnter)
* add key
* add exit prop 

## docs
[mount/ unmount animations](https://moti.fyi/animations#mountunmount-animations-)
[animate presence](https://moti.fyi/examples/animate-presence)
[exit before enter](https://moti.fyi/examples/exit-before-enter)

## relevant code
```
    <Container>
      <AnimatePresence exitBeforeEnter>
        <MotiView
          key="content"
          type={type}
          from={{
            opacity: 0.3,
            translateY: 25,
          }}
          animate={{
            opacity: 1,
            translateY: 0,
          }}
          exit={{
            opacity: 0,
            translateY: 25,
          }}
          transition={{
            type: 'timing',
            duration: 100,
          }}
        >
         
             .....


        </MotiView>
      </AnimatePresence>
    </Container>
```

## Demo
https://user-images.githubusercontent.com/36442007/118603142-d970a800-b7b3-11eb-9a3e-7ab89a693b08.mov

## Versions
```
   "moti": "^0.10.1",
   "react-native-reanimated": "^2.0.0",
   "expo": "~41.0.0",
```

**Comment by nandorojo** [comment]
You should be conditionally rendering the child of animate presence. Also, if using exit before enter, you need to give a unique key to the item leaving and entering. Please see the framer motion docs on animate presence.

**Comment by nandorojo** [comment]
Example: https://www.framer.com/api/motion/animate-presence/

**Comment by TijsM** [comment]
I rendered the entire component conditionally, and not just the Motiview. 

adding the condition around the Motiview fixed it


```
<Container>
      <AnimatePresence exitBeforeEnter>
        {show ? (
          <StyledToast
            key="content"
            type={type}
            from={{
              opacity: 0.3,
              translateY: 25,
            }}
            animate={{
              opacity: 1,
              translateY: 0,
            }}
            exit={{
              opacity: 0,
              translateY: 25,
            }}
            transition={{
              type: 'timing',
              duration: 100,
            }}
          >
          
         ..... 

        ) : null}
      </AnimatePresence>
    </Container>
```

Thanks!
