### ISSUE TITLE
Cannot convert undefined or null to object while testing with Jest

### ISSUE THREAD

**Issue by Prernabudh** [nandorojo/moti#69]
I am using Moti to create animations, they are working properly, however, the test cases are failing.
My code:
![image](https://user-images.githubusercontent.com/48886463/118634986-bd3f2c00-b7f0-11eb-8f30-4c852f0315e9.png)
Jest error:
![image](https://user-images.githubusercontent.com/48886463/118635106-d811a080-b7f0-11eb-97d8-3c8622e54230.png)

React native version: 0.64.0
Moti: ^0.8.2
React native reanimated: 2.0.0

**Comment by nandorojo** [comment]
This is a reanimated problem. It seems like your testing library isn't applying the Babel plugin to @motify/core. 

I'm not familiar with testing, but you'd want to add @motify/core to the list of modules transpiled. The most help I can offer is to look at [moti.FYI/web](https://moti.fyi/web) and see if you find any ideas there.

Please share here if you solve it, thanks.

**Comment by jesuscovam** [comment]
I'm experiencing the same issue doing test with jest. Even with the proper webpack.config.js

```
const createExpoWebpackConfigAsync = require("@expo/webpack-config");

module.exports = async function (env, argv) {
  const config = await createExpoWebpackConfigAsync(
    {
      ...env,
      babel: { dangerouslyAddModulePathsToTranspile: ["moti", "@motify"] },
    },
    argv
  );

  return config;
};
```

<img width="1095" alt="Screen Shot 2021-05-20 at 11 40 52" src="https://user-images.githubusercontent.com/46403187/119017092-40cb5b00-b960-11eb-8f54-e31792e76691.png">

**Comment by nandorojo** [comment]
Hmm, I wish I could help more here. I haven't used Jest.

**Comment by jesuscovam** [comment]
> Hmm, I wish I could help more here. I haven't used Jest.

it's ok, I'm an early adopter to testing. I wish I could help too
