### ISSUE TITLE
Adding a callback after animation has been completed

### ISSUE THREAD

**Issue by zcaudate** [nandorojo/moti#70]
I'd like to be able to register a callback with MotiView so that after an enter or exit animation is done, it will call a custom function.

Is this possible to do?

**Comment by nandorojo** [comment]
Use the `onDidAnimate` prop:

https://github.com/nandorojo/moti/api/props

https://moti.fyi/animations#listen-to-animation-changes

**Comment by nandorojo** [comment]
If you want to listen to exits, pass `onExitComplete` to `AnimatePresence`.

**Comment by zcaudate** [comment]
sweet. I didn't know about exitTransition. Thanks!
