### ISSUE TITLE
Docs: Motify gives impossible example

### ISSUE THREAD

**Issue by archcorsair** [nandorojo/moti#73]
### Link to docs: [Motify](https://moti.fyi/api/motify)

Unless I am missing something, this seems incorrect

The docs are instructing to wrap a functional component with `motify`. This is impossible since under the hood motify uses `createAnimatedComponent` which only works with class components.

### Snippet
```js
import React from 'react'
import { View } from 'react-native'
import { motify } from 'moti'

function MyMotiComponent({ style }) {
  // make sure you forward the style prop
  return <View style={style} />
}

// notice that we call the function after!
const MotifiedComponent = motify(MyMotiComponent)()

export default MotifiedComponent
```

Error generated:
```
Invariant Violation: `createAnimatedComponent` does not support stateless functional components; use a class component instead.
```

**Comment by dangolbeeker** [comment]
https://moti.fyi/api/motify

**Comment by nandorojo** [comment]
Feel free to PR. Maybe we just pass motify the normal `View` from react-native instead of this custom component.
