### ISSUE TITLE
Problems with opacity in expo web

### ISSUE THREAD

**Issue by danielkv** [nandorojo/moti#74]
I'm having some issues on expo web with `opacity` prop. What I'm doing:

```tsx
<AnimatePresence>
    {selected && (
        <MotiView
              from={{ translateX: 50, opacity: 0 }}
              exit={{ translateX: 50, opacity: 0 }}
              animate={{ translateX: 0, opacity: 1 }}
              transition={{ mass: 0.15, damping: 4 }}
          >
            <SelectedIcon />
        </MotiView>
    )}
</AnimatePresence>
```

The animation and timing are perfect, **BUT** when the animation ends the `SelectedIcon` component goes back to `opacity: 0`.
When I take off the `opactity` prop, it works fine.

I tried to debug with `onDidAnimate` but the value returns as `undefined`.

**Comment by nandorojo** [comment]
Hey, thanks for the issue!

1. What version of RNW? Please upgrade, since expo web uses an old version. I've had success with 0.15.3
2. This is likely a reanimated 2 issue with web. But we can try to debug it here!

**Comment by danielkv** [comment]
> Hey, thanks for the issue!
> 
> 1. What version of RNW? Please upgrade, since expo web uses an old version. I've had success with 0.15.3
> 2. This is likely a reanimated 2 issue with web. But we can try to debug it here!

Hi, I just tested it with RNW 0.16.3, **no success**. Problem persists!

The weirdest thing is everything else works fine! The problem is only the `opacity` property. The project is almost production ready, so for now I switched to scale animation, althoug it's not the animation we've planned, it's doing the job so far.

**Comment by nandorojo** [comment]
What if you do opacity without scale? Still no luck?

**Comment by nandorojo** [comment]
Can you reproduce this in a snack?

**Comment by danielkv** [comment]
> What if you do opacity without scale? Still no luck?

Already tried, no luck!

> Can you reproduce this in a snack?

I'm a little busy today, but I'll do it ASAP.

**Comment by nandorojo** [comment]
I use opacity all over my app so this must be an issue with your setup.

https://snack.expo.io/@kellycup8/tactless-cheese

**Comment by danielkv** [comment]
I've tested in other components also, follow the same problem

Anyway, this is component:

```tsx
function ProfessionalItem({ professional, selected, onPressItem }: Props) {
    const { palette } = useTheme();

    function handlePressItem() {
        if (onPressItem) onPressItem(professional);
    }

    function Selected() {
        return (
            <MotiView
                from={{ scale: 0, opacity: 0 }}
                exit={{ scale: 0, opacity: 0 }}
                animate={{ scale: 1, opacity: 1 }}
                transition={{ mass: 0.15, damping: 4 }}
            >
                <SelectedIcon />
            </MotiView>
        );
    }

    return (
        <ProfessionalItemContainer selected={selected} onPress={handlePressItem}>
            <ProfessionalItemContent>
                <Avatar source={{ uri: professional.image }} size={30} />

                <ProfessionalTitleContainer>
                    <ProfessionalTitle>{professional.name}</ProfessionalTitle>

                    <ProfessionalRatingContainer>
                        <Icon name="star" size={18} color={palette.primary.default} />

                        <ProfessionalRating>
                            {professional.rating.toFixed(1).replace('.', ',')}
                        </ProfessionalRating>
                    </ProfessionalRatingContainer>
                </ProfessionalTitleContainer>

                <AnimatePresence>{selected && <Selected />}</AnimatePresence>
            </ProfessionalItemContent>
        </ProfessionalItemContainer>
    );
}

export default React.memo(ProfessionalItem, (prev, next) => prev.selected === next.selected);
```

**Comment by nandorojo** [comment]
You shouldn't be putting selected into its own function like that. JSX components shouldn't be created in render code. If you want to do that, call it as a function, like `{selected && Selected()}`.

But stylistically, I don't see the benefit to the syntax in your example.

In any case, I can't reproduce this in my snack, so I think something is wrong with your setup. Please make sure you're on the latest versions of reanimated and moti. If you recreate this in a snack, I can reopen.
