### ISSUE TITLE
Question: Using AnimatePresence with reanimated v1.

### ISSUE THREAD

**Issue by zyasir** [nandorojo/moti#77]
I was trying to create an AnimatePresence component for reanimated v1. I was wondering if you had any guidance on that? As I saw you use used it with reanimated v2.

Thanks for the awesome lib. When we upgrade to v2 I will definitely use this lib.

**Comment by nandorojo** [comment]
Glad to hear that.

Reanimated v2 is required for Moti. There's no compatibility for v1.

**Comment by Noitidart** [comment]
Thanks I think he understands that, I also am trying to use the AnimatePresence component for unmounting animations, but with `Animated` API of RN. As you have adapted AnimatePresence for reanimated v2, could you share your story, so we can follow similar to adapt it to our animation libs?

**Comment by nandorojo** [comment]
Sure. It's actually pretty simple. Just use the `usePresence` hook from Framer.

In useEffect:

```js
if (!present) {
  Animated.timing(..., ({ finished }) => {
  if (finished) safeToUnmount()
}
}
```

**Comment by nandorojo** [comment]
See this Twitter thread for more info on how I made it: https://twitter.com/mattgperry/status/1349474900961058818?s=21

**Comment by Noitidart** [comment]
Thanks for your fast reply! I see you used AnimatedPresence with usePresence hook. I will peak that and see how you did it. This might help the OP too.

**Comment by nandorojo** [comment]
Yeah moti's logic for this is all in one file if you need to peak.

**Comment by zyasir** [comment]
Wow fantastic thank you both and thank you @nandorojo for your support even though not related to your lib!

**Comment by nandorojo** [comment]
Happy to help.

**Comment by nandorojo** [comment]
I made a snack of how to use AnimatePresense without Moti. https://snack.expo.io/@kellycup8/a8065f

```jsx
import React, { useReducer, useEffect, useRef } from 'react'
import { StyleSheet, Pressable, Animated } from 'react-native'
import { AnimatePresence, usePresence } from 'framer-motion'

function FadeOut() {
  const [present, safeToUnmount] = usePresence()

  const opacity = useRef<Animated.Value>(new Animated.Value(1))

  const unmount = useRef(safeToUnmount)
  useEffect(() => {
    unmount.current = safeToUnmount
  })

  useEffect(
    function exit() {
      if (!present) {
        Animated.timing(opacity.current, {
          toValue: 0,
          useNativeDriver: true,
        }).start(({ finished }) => {
          if (finished && unmount.current) {
            unmount.current()
          }
        })
      }
    },
    [present]
  )

  return <Animated.View style={[styles.shape, { opacity: opacity.current }]} />
}

export default function HelloWorld() {
  const [visible, toggle] = useReducer((s) => !s, true)

  return (
    <Pressable onPress={toggle} style={styles.container}>
      <AnimatePresence>{visible && <FadeOut />}</AnimatePresence>
    </Pressable>
  )
}

const styles = StyleSheet.create({
  shape: {
    justifyContent: 'center',
    height: 250,
    width: 250,
    borderRadius: 25,
    marginRight: 10,
    backgroundColor: 'white',
  },
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    backgroundColor: '#9c1aff',
  },
})
```

**Comment by Noitidart** [comment]
A major token of appreciation for sharing that, that was too kind man

**Comment by nandorojo** [comment]
Glad it's useful. I shared it on Twitter too: https://twitter.com/FernandoTheRojo/status/1401267532942696458

**Comment by zyasir** [comment]
Extremely helpful, thank you very much.
