### ISSUE TITLE
Skeleton inside an animated BottomSheet

### ISSUE THREAD

**Issue by kickbk** [nandorojo/moti#79]
@nandorojo I'm working on a cached image with fade component. Since my images are all compressed (130KB avg.) I figured I can live without a thumbnail fading in with blur, and to make the fade easier, I am thinking to just use Skeleton vs an animated image with fade on opacity. Easy. Here's the code:

```
export function SkeletonImage(props: {
  skeletonRadius?: number;
  skeletonHeight?: number | string;
  imageSource: string;
  resizeMode: 'cover' | 'contain';
  style: ImageStyle;
}) {
  const [imageUri, setImageUri] = useState<string | null>();

  const getImageFilesystemKey = useCallback(async (remoteURI: string) => {
    const hashed = await Crypto.digestStringAsync(Crypto.CryptoDigestAlgorithm.SHA256, remoteURI);
    return `${FileSystem.cacheDirectory}${hashed}`;
  }, []);

  const loadImage = useCallback(
    async (filesystemURI: string, remoteURI: string) => {
      try {
        const metadata = await FileSystem.getInfoAsync(filesystemURI);
        if (metadata.exists) {
          // Use the cached image if it exists
          setImageUri(filesystemURI);
        } else {
          // otherwise download to cache
          const imageObject = await FileSystem.downloadAsync(remoteURI, filesystemURI);
          setImageUri(imageObject.uri);
        }
      } catch (err) {
        console.log('Image loading error:', err);
        setImageUri(remoteURI);
      }
    },
    [setImageUri]
  );

  useEffect(() => {
    getImageFilesystemKey(props.imageSource).then((filesystemURI) => {
      loadImage(filesystemURI, props.imageSource);
    });
  }, [getImageFilesystemKey, loadImage, props.imageSource]);
  return (
    <Skeleton
      show={!imageUri}
      radius={props.skeletonRadius !== undefined ? props.skeletonRadius : 4}
      height={props.skeletonHeight}
    >
      <Image
        {...props}
        source={{ uri: imageUri ? imageUri : props.imageSource }}
        style={props.style}
      />
    </Skeleton>
  );
}
```
This works really well as long as the skeleton/image is not moving while it's loading. Unfortunately, I have the images inside a carousel which is inside a BottomSheet that moves upward when results are found (think Yelp search for businesses on the map).

Can you think why the performance degrades once the component is inside a moving BottomSheet? Any suggestions for improvement?

**Comment by nandorojo** [comment]
Hm I'm not sure. One thought could be that the `show` prop is updated with React state. Is the loading happening while you're loading? Otherwise, it might be the bottom sheet that has problems with re-render performance.

Could you show a video of the issue?

**Comment by nandorojo** [comment]
And to clarify, if you remove the skeleton, there's no issue? What if you leave the skeleton and statically set `show={false}`?

**Comment by kickbk** [comment]
Here is an example of how it makes things choppy

https://user-images.githubusercontent.com/31323376/122482631-c8b77b80-cf85-11eb-8c1b-dee125b6e05d.mov

When I set statically to false it's ok:

https://user-images.githubusercontent.com/31323376/122482677-dcfb7880-cf85-11eb-93a9-31b9fb2e5c83.mov

Mind you, I am using a very large image (4.2MB) here for testing. Live I always use compressed images of around 130KB.

Your initial thought that it may be the state is correct. When I used a `const imageUri = useRef('');` it worked well, but it doesn't work when navigating to another screen with a SkeletonImage. The imageUri never gets updated.

Your second thought about rerendering inside the BottomSheet might be correct as well, but to drill into where exactly the issue is in the component tree will be tough.

**Comment by kickbk** [comment]
the ref helps but does not take care of the issue completely. Often it causes the BottomSheet not to animate upward but to just "materialize" at the end position.

**Comment by kickbk** [comment]
I also noticed that if I set `show` statically to always show, I see it effects the performance as well

**Comment by nandorojo** [comment]
I don't follow what you're saying

**Comment by nandorojo** [comment]
Okay the fact that it's slow when skeleton is always true but not when always false makes me think it's due to reanimated adding more `useAnimatedStyle` nodes

**Comment by nandorojo** [comment]
If you remove the skeleton altogether, is it fine? What if you set `fadeDuration={0}` on the image?

**Comment by kickbk** [comment]
After debugging for a while, it seems that any animation I placed inside the BottomSheet resulted in reduced performance, so this is not specific to Skeleton. Thanks for checking it out though. Closing.
