### ISSUE TITLE
Does it support animation of color?

### ISSUE THREAD

**Issue by PaulPaksGitHub** [nandorojo/moti#80]
Hello, can you tell me if it is possible to animate colors properties like <Text> color or <View> backgroundColor?

**Comment by nandorojo** [comment]
Try it out

**Comment by nandorojo** [comment]
I think so

**Comment by Tymek** [comment]
I can confirm that it does 👍🏻

**Comment by hadnet** [comment]
> I can confirm that it does 👍🏻
> 
> ```js
>   <MotiView
>     from={{ backgroundColor: '#fff' }}
>     animate={{ backgroundColor: '#000' }}
>     exit={{ backgroundColor: '#f00' }}
>   >
> ```
> 
> with opacity:
> 
> ```js
> <MotiView
>   from={{ backgroundColor: '#00000000' }}
>   animate={{ backgroundColor: '#000000ff' }}
>   exit={{ backgroundColor: '#00000000' }}
> >
> ```

So why cant I do this using MotiPressable, @nandorojo ? I just wanted a transition of colors like we do on CSS.

**Comment by nandorojo** [comment]
Reanimated color animations should work, as long as you're animating between similar colors.

**Comment by nandorojo** [comment]
If you want the ability to animate between distinct colors, I recommend opening an issue on Reanimated
