### ISSUE TITLE
Error: Element type is invalid expected a string

### ISSUE THREAD

**Issue by rahadkc** [nandorojo/moti#81]
I am trying to start with Moti, seems like a great package but stuck in `Hello world` example.

## Report Type
Bug

## Error Description
Trying to run [Moti Hello World example](https://moti.fyi/examples/hello-world).
Getting this error

```sh
Error: Element type is invalid: expected a string (for built-in components) or a class/function 
(for composite components) but got:  undefined. You likely forgot to export your component from 
 the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `Shape`.
```

## Full error
<img width="1151" alt="Screenshot 2021-06-24 at 7 10 18 AM" src="https://user-images.githubusercontent.com/8745638/123187615-50d4de00-d4bc-11eb-9b1e-b10f3daf4923.png">

## Setup/dependency

```json
"dependencies": {
    "expo": "~41.0.0",
    "framer-motion": "^3.3.0",
    "moti": "^0.4.1",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz",
    "react-native-reanimated": "~2.1.0",
    "react-native-web": "~0.13.12"
  }
```

**Comment by nandorojo** [comment]
Please follow all the instructions and install Reanimated 2: https://github.com/nandorojo/moti/installation

Or see the starter template: https://github.com/expo/examples/tree/master/with-moti

**Comment by rahadkc** [comment]
Hi @nandorojo , Thanks for the fast reply.

I am using starter template by running
`npx create-react-native-app -t with-moti`

And the starter template running fine but when I try to use `Hello World` example from separate component, getting this error.

**Comment by nandorojo** [comment]
My guess is there's an issue on your end then, since the starter is just using the hello world

**Comment by nandorojo** [comment]
Are you on the latest version?

```
yarn add moti
```

**Comment by rahadkc** [comment]
@nandorojo  Thanks

updating Moti to latest version solve the problem.

**Comment by nandorojo** [comment]
Sounds good thanks. I have a pending PR to update the example on Expo's repo, still waiting on them to merge it
