### ISSUE TITLE
Bundle size consideration

### ISSUE THREAD

**Issue by todorone** [nandorojo/moti#82]
Hey Fernando

Thanks a lot for such an amazing library with such a slick API - it's a breath of fresh air in the world of overcomplicated RN animations.

One consideration for us though is the library size. While the core of the library is pretty small - 22kb, it adds the whole `framer-motion` to the bundle which results in 120Kb total which is a bit too big. Is it possible to re-export just `AnimatePresence` component without the whole `framer-motion` bundle?
@nandorojo 

The way to reproduce:
- setup new RN project with `npx react-native init test`
- run `yarn add react-native-reanimated` and add `import 'react-native-reanimated'` at the top of the `App.js`
- run `npx react-native-bundle-visualizer`
- run `yarn add moti` and add the simple `View` from `moti` to the `App.js`
- run `npx react-native-bundle-visualizer`. Result:

![Screenshot 2021-06-25 at 16 04 19](https://user-images.githubusercontent.com/423701/123429371-8dddc500-d5cf-11eb-8b63-269e79e419a4.png)

In the above image `moti` dependency is black-underlined and the rest are red-underlined:
<img width="1827" alt="Screenshot 2021-06-25 at 16 19 17" src="https://user-images.githubusercontent.com/423701/123431060-87504d00-d5d1-11eb-90ec-65743a8940f1.png">

**Comment by nandorojo** [comment]
Try upgrading

![image](https://user-images.githubusercontent.com/13172299/123418221-c907d600-d586-11eb-83fb-7741406355e3.png)

**Comment by todorone** [comment]
@nandorojo This is the bundle size for the web, and I'm talking about the mobile bundle in React Native.

I've updated the first post with the way to see the result of bundle increase brought by `moti`. Actually, I was mistaken - it adds not just `framer-motion`, but also `popmotion` and a couple of `@emotion/*` dependencies.

The `moti`'s code is pretty small in size, but we need to be conscious and adding unneeded JS code which results in the slower startup time of the app and higher memory consumption.

**Comment by todorone** [comment]
Hi @nandorojo 

Any answer to my last comment is highly appreciated.
A bit of context: the library has super-cool API and we want to use it in our company's production application but bloating the bundle with an extra 120Kb is not acceptable for us, so I can try to contribute(not just complain 😸) if we agree on some solution to mitigate the issue.

Thanks!

**Comment by nandorojo** [comment]
I'm open to a solution, I'm just not totally sure how to get around it without getting rid of the framer motion feature. Maybe it could work via a plugin system that tree shakes? Some libraries work that way. So there would be an animate presence plugin, and if you never use AnimatePresence, you'd just not import that plugin.

**Comment by todorone** [comment]
Thanks for the reply @nandorojo 

I'll try to invest some time in it. If I'll be able to detach the `usePresence` and `AnimatePresence` code into Moti's core, will it work for You?

**Comment by nandorojo** [comment]
It would be a breaking change, so I'd have to see the implementation, but I'm open to it!

**Comment by nandorojo** [comment]
Here's an idea.

I haven't given this too much thought yet, since I don't know how the API would work.

But...

Now that reanimated has _native_ layout animations, maybe animate presence on Native should be replaced with Layout from reanimated 2.3.x?

Unifying this API with the framer motion API would be challenging. **But**, it would allow us to move the framer motion integration into a web-only plugin. This would help with your bundle size issue, and it would also result in better performance for Native :)

Since I'm familiar with the moti method of exiting, I'm happy to think through how this could work. It might make sense to open a new issue about unifying web animate presence animations with Native layout transitions. 

What do you think?

**Comment by todorone** [comment]
Sounds like a great idea to me.

Right now I'm not sure how to achieve the current `AnimatePresence` API with REA's `LayoutAnimation` API, but ready to experiment and do my best to participate...

One thing that should be taken into consideration though is the maturity of `LayoutAnimation` API. I tried to use legacy layout animation API from REA1 some time ago and it never worked in the right way on Android. Hopefully, new version will be better...😄

**Comment by nandorojo** [comment]
True, I haven't actually played with this one yet. At least they view it as a priority now.

Animate presence has worked well for me on app platforms. Sometimes on Native it lags if its child is a massive component. But besides that it's worked for me.

**Comment by nandorojo** [comment]
will re-open if there's activity here.
