### ISSUE TITLE
Side by Side views wont animate at the same time.  

### ISSUE THREAD

**Issue by nanetteCodes** [nandorojo/moti#84]
I have a use-case where two side-by-side components need to animate simultaneously.

`<View></Sidebar></Content></View>`

`Sidebar` and `Content` is at a set width on first render, on button click `Sidebar` should animate out of view and `Content` should take up full screen.  It seems like there is no way to get both of these components to animate at the same time. When I add animation only the sidebar will animate.

Code example:

```
import { ScrollView as MotiScrollView, MotiView } from 'moti';

export default function App () {

    const SIDEBAR_WIDTH = 400;
    const { width: fullWidth } = useWindowDimensions();
    const widthBasedOnSidebarState = showSidebar ? fullWidth - SIDEBAR_WIDTH : fullWidth;

    const Sidebar = ({ showSidebar }) => (
        <MotiView
            animate={{ translateX: showSidebar ? 0 : -SIDEBAR_WIDTH }}
            transition={{
            type: 'timing',
            duration: 400,
            }}
            style={{ width: SIDEBAR_WIDTH }}>
            <Text>Sidebar<Text/>
        </MotiView>
    );

    const Content = ({ showSidebar }) => (
        <MotiScrollView
            animate={{ width: widthBasedOnSidebarState }}
            transition={{
                type: 'timing',
                duration: 400,
            }}
            style={{ flexGrow: 1, width: widthBasedOnSidebarState }}>
            <Text>Content<Text/>
        </MotiScrollView>
    );

    return (
        <SafeAreaView style={{flexDirection: 'row', flex: 1}}>
            <Sidebar/>
            <Content/>
        </SafeAreaView>
    )
}
```

**Comment by nandorojo** [comment]
1) You shouldn't put the width in the `style` prop, this is probably the issue 

2) you shouldn't declare components inside of other components

**Comment by nanetteCodes** [comment]
@nandorojo those are their own components... I just put them here for a code example.  If i do not add a width to the `Content`, when `Sidebar` closes the empty space is not filled and the `Content`  is pushed to the right side... here is a video 


## Style for Container: 

```
<SafeAreaView style={{flexDirection: 'row', flex: 1}}>
 <Sidebar><Content>
</SafeAreaView
```
## Style for Sidebar: 

```
<MotiView
    animate={{
      translateX: showSidebar ? 0 : -SIDEBAR_WIDTH,
    }}
    transition={{
      type: 'timing',
      duration: 600,
    }}
    style={{ flex: 1 width: SIDEBAR_WIDTH, backgroundColor: '#1639c5', alignItems: 'center' }}
  >
  ...
  </MotiView>
```

## Style for Content:

```
<MotiScrollView
    animate={{ width: widthBasedOnSidebarState }}
      transition={{
        type: 'timing',
        duration: 600,
      }}
      style={{ backgroundColor: '#dd0d26', alignItems: 'center', flexGrow: 1 }}
    >
  ...
  </MotiScrollView>
```



https://user-images.githubusercontent.com/28736699/123849303-7e12f900-d8cd-11eb-9bf7-e9e4af93b709.mp4

**Comment by nandorojo** [comment]
I'm saying that, if you want width to animate, you should put it in the `animate` prop, _not_ the `style` prop, like you did in your example.

![image](https://user-images.githubusercontent.com/13172299/123849667-0eaa0300-d8e7-11eb-8c02-a875805dda78.jpeg)

**Comment by nandorojo** [comment]
It's also possible that flex grow would mess with the animation if you're trying to animate width.

**Comment by nanetteCodes** [comment]
@nandorojo if you look at my updated styles listed in the last comment i removed the width from the Content before sending you that screen share I updated the styles.

**Comment by nanetteCodes** [comment]
@nandorojo i also made  sure to have the components declared outside... its animating! but not to the same speed. You can see the container beneath when you switch between sidebar in and out.  


https://user-images.githubusercontent.com/28736699/123851438-08f4f300-d8d0-11eb-8aa8-12718198eef5.mp4

**Comment by nandorojo** [comment]
Works for me

Video: https://www.loom.com/share/5561da097cd946a7878b2691eb0b2a44

Snack: https://snack.expo.io/@beatgig/moti-animated-sidebar

**Comment by nandorojo** [comment]
That's because you made the `duration` 400 on one and 600 on the other.

**Comment by nanetteCodes** [comment]
seems that the issue was my CSS. thank you!

**Comment by nandorojo** [comment]
Glad it works.

Are you using this on web btw? (Out of curiosity)

**Comment by nanetteCodes** [comment]
no just on a react native app.
