### ISSUE TITLE
Color animation issue

### ISSUE THREAD

**Issue by BrandonMA** [nandorojo/moti#87]
### What's happening?

Depending on the color value you want to animate, some weird colors appear during the animation.

https://user-images.githubusercontent.com/6232522/125181736-815f8c00-e1cd-11eb-8a63-cb37b86f0d48.mov

### Expected behaviour

The color animation is smooth, like any css animation would happen on web

Example:

https://snack.expo.io/@brandonma/color-bug-reanimated

### Further information

This bug is actually happening in Reanimated 2 and not Moti itself, as I assume you are implementing the animation the same way I did in the example under the hood, the thing is, this bug doesn't happen if you use interpolateColor instead of this approach(I was building a library like Moti and had the same problem before but decided to use Moti as it seems better overall).

I created an issue a while ago but the Reanimated team did not pay much attention to it, I will create another one so if you can help getting some attention would be nice.

Also, if you are interested in more information about the workaround using interpolateColor let me know.

**Comment by BrandonMA** [comment]
The issue on the Reanimated repo has been closed, basically using interpolateColor is not a workaround but the correct way to animate colors, here is the link of the issue:

https://github.com/software-mansion/react-native-reanimated/issues/2193

**Comment by nandorojo** [comment]
Interesting. So the idea is, you shouldn't animate between two color values, right? I actually thought I had it working, but maybe this will need some magic under the hood to add interpolate color...

**Comment by BrandonMA** [comment]
> Interesting. So the idea is, you shouldn't animate between two color values, right? I actually thought I had it working, but maybe this will need some magic under the hood to add interpolate color...

Yes! Actually what I used to do in the past to animate colors was to save the previous color on a reference, and then use that to build the new array, the trickiest part is to work with the animated value of 0 and 1, you would have to make it 0 again at some re render when the new array is generated for no weird color flickering, so a "magic" extra render would have to be introduced for color animations to work.

I am curious on why they decided this approach of animating colors tho, iOS doesn't need this to perform animations natively, not sure about Android but still seems like a bug for me on their side, that being said this is the best idea I had to fix it with interpolateColor.

**Comment by nandorojo** [comment]
Yeah, one other slightly hacky solution would be to have clone elements, one with a different color, and transition the opacity from one to the next haha.

This might be a use case that will be solved by https://github.com/nandorojo/moti/pull/54

**Comment by nandorojo** [comment]
Since this is a reanimated issue, I'm going to close here.

**Comment by BrandonMA** [comment]
> Since this is a reanimated issue, I'm going to close here.

Hello! Sorry for the late reply I have been really busy at school, but as I mentioned before, is not really a problem with Reanimated, at least according to them this occurs because color animations should be performed with ```interpolateColor()```, I am not sure if you are already doing this, but just to be sure, if we do it that way colors animate as expected.

Reanimated issue:
https://github.com/software-mansion/react-native-reanimated/issues/2193

**Comment by nandorojo** [comment]
The thing is, that would require interpolating colors based on their previous value. Since moti is declarative, I’m not sure how this would work, since we don’t track the previous value, and there’s no shared value to interpolate. This use case might be best solved with using `useAnimatedStyle` and a shared value. I’m not sure how else it would work.

**Comment by BrandonMA** [comment]
It is possible to implement this feature on a declarative way if you save the previous color value on a reference, and just performing the animation if the previous value is not undefined/null and is different from the current color, I implemented this before and it worked fine, I can create a small example on how to do it if you need it because I am not that familiar with Moti's codebase

**Comment by nandorojo** [comment]
Yeah, I’m just not totally sure if Moti should be tracking the previous value that way or not. Might fall outside of the simple scope I have working now. I can look at an example and consider it.

**Comment by jparkrr** [comment]
Just wanted to say that I ran into this issue as well. It would have been amazing if it were handled by Moti, but I cannot speak to how it should be implemented.
