### ISSUE TITLE
TypeError: global.__reanimatedWorkletInit is not a function. (In 'global.__reanimatedWorkletInit(_f)', 'global.__reanimatedWorkletInit' is undefined)

### ISSUE THREAD

**Issue by BenBavar** [nandorojo/moti#88]
I've been trying to get started with `moti` without using Expo, since I'm unfamiliar with the latter. Unfortunately, simply importing `moti`—more precisely, writing the code `import { View as MotiView } from 'moti'`—always results in the following error when I run `npx react-native run-macos`.

<img width="570" alt="Screen Shot 2021-07-11 at 12 38 47 AM" src="https://user-images.githubusercontent.com/46368238/125183052-2e8fcf80-e1e1-11eb-9d85-072bd010a0e4.png">

I'm not really worried about those last two errors, as I've had them before and managed to get rid of them. As for the first error, I've tried the solutions offered on the internet (importing `react-native-reanimated`, writing `global.__reanimatedWorkletInit = () => {}` in my App.js, clearing the Metro cache and watchman watches, etc.), but to no avail. Anybody know how to fix this?

Thanks in advance!

Addendum: I got some new errors when I added `motify` to my list of components imported from `moti`. While the errors are similar, they're different enough that they may suggest solutions which the above error did not.

<img width="567" alt="Screen Shot 2021-07-11 at 1 34 38 AM" src="https://user-images.githubusercontent.com/46368238/125184002-78c87f00-e1e8-11eb-8044-deec243a8d05.png">

**Comment by nandorojo** [comment]
Hey, thanks for the issue. I haven't seen this one before, or at least not in a long time. Does it work if you just import reanimated? Maybe you need to transpile moti somewhere?

Is your React Native Reanimated Babel plugin setup properly?

**Comment by BenBavar** [comment]
Sure, thanks for responding! When I import both `moti` and `react-native-reanimated`, I get the errors above. As for when I import `react-native-reanimated` by itself—instead of `moti`—I don't get the same errors . In fact, I get no error if I comment out all my code that uses components from the Reanimated library. The only problem I experience in that case is that my (static) SVGs are duplicated when I enter 'r' in the React Native terminal window (to reload the app):

<img width="712" alt="Screen Shot 2021-07-22 at 3 37 22 PM" src="https://user-images.githubusercontent.com/46368238/126699339-277abfee-b26a-47a9-bbf3-f2a5acea057f.png">

But when I import `react-native-reanimated` and uncomment out all the code in my App.js (and still refrain from importing `moti`), I get the following error:


<img width="600" alt="Screen Shot 2021-07-22 at 3 17 00 PM" src="https://user-images.githubusercontent.com/46368238/126698100-234f5e75-4b9a-4371-8d60-fad16d445a64.png">

I will look more into your suggestion to transpile `moti`, as that is not something I've tried. If you can provide any resources that would explain how and where to transpile `moti`, that would be much appreciated. Again, I am not using Expo, nor have I been using React Native _Web_ or Next.js, so I'm not sure how relevant these resources I found are to my case:

https://moti.fyi/web
https://moti.fyi/next
https://github.com/nandorojo/moti/issues/36

My Reanimated Babel plugin is set up as specified in the Reanimated docs on installation. These are the contents of my `babel.config.js`:

<img width="600" alt="Screen Shot 2021-07-22 at 3 26 30 PM" src="https://user-images.githubusercontent.com/46368238/126698025-68f8af93-bd6b-4658-aa4c-fabfe6a1c585.png">

**Comment by BenBavar** [comment]
I've pinpointed the code which triggers the following error, which I also showed you above:

<img width="600" alt="Screen Shot 2021-07-22 at 3 17 00 PM" src="https://user-images.githubusercontent.com/46368238/126703006-23c9ec10-3d59-43a0-b53d-40a459b601be.png">

It's my use of a `${}` interpolation expression in assigning a value to the transform attribute on an SVG: 
``transform={`scale(1.2) translate(-28, ${bounce})`}``

For more context, see my code below:

<img width="1131" alt="Screen Shot 2021-07-22 at 4 20 14 PM" src="https://user-images.githubusercontent.com/46368238/126704396-0bd41efd-35d6-47dd-b931-c0a52cb1ddee.png">

**Comment by nandorojo** [comment]
I'm a bit confused, since this code doesn't have moti in it. Are you on the latest version of reanimated v2? The way you're passing animated props makes it seem like you're using `Animated` from react native. But I don't see what about that screenshot is related to Moti.

**Comment by iiagodias** [comment]
At the beginning of the main file, you do the following import.

**import 'react-native-reanimated';**

**Comment by nandorojo** [comment]
The code here should be using `animatedProps`.

**Comment by iiagodias** [comment]
I had the same error using moti, I adjusted the error with this import.

**Comment by nandorojo** [comment]
Maybe we could add a known errors section to the docs. Thanks
