### ISSUE TITLE
Auto PR

### ISSUE THREAD

**Issue by nandorojo** [nandorojo/moti#9]
I can't for the life of me get `auto` to work with GitHub actions. What am I missing here? I am new to this library. I set the env variables and followed the steps, but no dice...

**Comment by cmaycumber** [comment]
Are you using the auto action by any chance? https://github.com/marketplace/actions/auto-action

Also I'm not sure if you're currently using it or not but I've found this helpful to test GitHub actions locally: https://github.com/nektos/act

**Comment by nandorojo** [comment]
Yeah, I tried it but it seemed outdated (it was saying I had the wrong auto version.) I made my own git action but that doesn't seem to do it either.

Looks like the problem lies with `auto`. When I run `auto shipit` locally, it just says "will not publish". I'll have to keep investigating...

Thanks for the tip there! I'll def try that out.
