### ISSUE TITLE
Animate Presence "custom" attribute

### ISSUE THREAD

**Issue by ChildishForces** [nandorojo/moti#91]
Hi, nice lib!

Are there any plans to support the custom property of AnimatePresence? It appears not to currently be implemented.

Cheers

**Comment by nandorojo** [comment]
Hey thanks! I have actually thought about this. It isn't _super_ trivial, but it's something that would be nice to have. Could you document your use case? I haven't thought about it in a while, and I unfortunately didn't have time to make it when I was hoping to use it.

**Comment by ChildishForces** [comment]
Absolutely, and thanks for your lightning quick reply!

Let's say I have a component that can move back and forth. With AnimatePresence's custom attribute I can ensure that any change of state can be passed to the, in this case, MotiView before rendering an exit transition. This way I can exit in a. way that makes sense in the context of the next component animating in.

In my opinion it's one of the most powerful features of AnimatePresence in framer-motion and currently the only thing that gives me pause about implementing this library into an app I am creating.

**Comment by nandorojo** [comment]
Is there a more specific use case? Like a real world example you're building?

One I ran into was trying to make an image gallery with the exit direction being specified by the relative index of the next image.

How would this be implemented? Presumably there needs to be some getter function that can access the latest `custom` value somehow?

**Comment by ChildishForces** [comment]
Hi, it seems your use case is credibly similar to mine. The way it's done in `framer-motion` is by accepting getter functions for the style properties, as you guessed.

**Comment by ChildishForces** [comment]
Or rather, the whole style object can be a better, rather than per property getters.

**Comment by nandorojo** [comment]
I'll have to see if this is even possible with reanimated worklets. My guess is the custom field could be a primitive but not an object

**Comment by ChildishForces** [comment]
That would work fine for me, as with your use case an index is all I need, being a `number`

**Comment by nandorojo** [comment]
@ChildishForces could you please try this https://github.com/nandorojo/moti/pull/102

```sh
yarn add moti@presence
```

I added support for the `custom` prop there. Would be useful to get it tested.

**Comment by nandorojo** [comment]
Fixed in `0.12.0`

```sh
yarn add moti
```
