### ISSUE TITLE
Question: React-native-reanimated

### ISSUE THREAD

**Issue by TheEhsanSarshar** [nandorojo/moti#99]
as I found `react-native-reanimated` is not included in `perDependency` or `devDependency`. 
didn't you face a typescript error when importing 'react-native-reanimated' ?

**Comment by nandorojo** [comment]
What do you mean? Like when building internally? It is in the dev dependencies of core.

**Comment by TheEhsanSarshar** [comment]
oh I see. thank you. why are you separating every package? is it for tree shaking?

**Comment by nandorojo** [comment]
It’s called a monorepo. Both for tree shaking, but mainly it’s easier to organize as the repo grows and we add more things.

**Comment by TheEhsanSarshar** [comment]
Yeah it's monorepo 🤓. 
Thank you very much Fernando.
